@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

--CREATE TABLE TMP_INGCLIEBCACEI_UNIVNG94 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_UNIVNG94;
INSERT INTO TMP_INGCLIEBCACEI_UNIVNG94
     SELECT DISTINCT A.CODCLAVECIC, A.CODUNICOCLI,
                     CASE
                         WHEN C.CODSEGMENTO IN('ES','EJ','EM') THEN 'E'
                         WHEN C.CODSEGMENTO IN('CL','EU') THEN 'I'
                         ELSE 'C'
                     END AS TIPBANCA
     FROM ODS_V.MD_CLIENTE A
          LEFT JOIN  ODS_V.MM_DESCODIGOSUBSEGMENTO B ON A.CODSUBSEGMENTO=B.CODSUBSEGMENTO
          LEFT JOIN  ODS_V.MM_DESCODSUBSEGGEN  C ON B.CODSUBSEGGENERAL=C.CODSUBSEGGENERAL
     WHERE C.CODSEGMENTO IN ('ES','CL','EU','EJ','EM','CC','CC','CI') AND
           A.TIPPER<>'P' AND
		   A.FLGREGELIMINADO='N';

--CREATE TABLE    TMP_INGCLIEBCACEI_UNIVG94 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_UNIVG94;
INSERT INTO TMP_INGCLIEBCACEI_UNIVG94
     SELECT DISTINCT A.CODCLAVECIC, A.CODUNICOCLI,
                     CASE
                         WHEN C.CODSEGMENTO IN('ES','EJ','EM') THEN 'E'
                         WHEN C.CODSEGMENTO IN('CL','EU') THEN 'I'
                         ELSE 'C'
                     END AS TIPBANCA
     FROM ODS_V.MD_CLIENTEG94 A
          LEFT JOIN  ODS_V.MM_DESCODIGOSUBSEGMENTO B ON A.CODSUBSEGMENTO=B.CODSUBSEGMENTO
          LEFT JOIN  ODS_V.MM_DESCODSUBSEGGEN  C ON B.CODSUBSEGGENERAL=C.CODSUBSEGGENERAL
     WHERE C.CODSEGMENTO IN ('ES','CL','EU','EJ','EM','CC','CC','CI') AND
           A.TIPPER<>'P' AND
		   A.FLGREGELIMINADO='N';

--CREATE TABLE TMP_INGCLIEBCACEI_UNIVCLIE TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_UNIVCLIE;
INSERT INTO TMP_INGCLIEBCACEI_UNIVCLIE
  SELECT * FROM TMP_INGCLIEBCACEI_UNIVNG94
  UNION
  SELECT * FROM TMP_INGCLIEBCACEI_UNIVG94;

--CREATE TABLE  TMP_INGCLIEBCACEI_UNIVCTASNG94 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_UNIVCTASNG94;
INSERT INTO TMP_INGCLIEBCACEI_UNIVCTASNG94
       SELECT A.*,B.CODCLAVEOPECTA AS CODCLAVEOPECTA ,B.CODOPECTA AS CODOPECTA
       FROM TMP_INGCLIEBCACEI_UNIVNG94 A
             LEFT JOIN ODS_V.MD_CUENTA B ON A.CODCLAVECIC=B.CODCLAVECIC
       WHERE B.CODCLAVEOPECTA IS NOT NULL AND
			  B.FLGREGELIMINADO='N' AND
			  B.CODSISTEMAORIGEN IN ('SAV','IMP') AND
			  B.CODOPECTA IS NOT NULL AND
			B.CODOPECTA<>'.';

--CREATE TABLE TMP_INGCLIEBCACEI_UNIVCTASG94 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_UNIVCTASG94;
INSERT INTO TMP_INGCLIEBCACEI_UNIVCTASG94
       SELECT A.*,B.CODCLAVEOPECTA AS CODCLAVEOPECTA ,B.CODOPECTA AS CODOPECTA
       FROM TMP_INGCLIEBCACEI_UNIVG94 A
             LEFT JOIN ODS_V.MD_CUENTAG94  B ON A.CODCLAVECIC=B.CODCLAVECIC
       WHERE B.CODCLAVEOPECTA IS NOT NULL AND
			B.FLGREGELIMINADO='N' AND
			B.CODSISTEMAORIGEN IN ('SAV','IMP') AND
			B.CODOPECTA IS NOT NULL AND
			B.CODOPECTA<>'.';

--CREATE TABLE TMP_INGCLIEBCACEI_UNIVCTASCLIE TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_UNIVCTASCLIE;
INSERT INTO TMP_INGCLIEBCACEI_UNIVCTASCLIE
        SELECT * FROM TMP_INGCLIEBCACEI_UNIVCTASNG94
        UNION
        SELECT * FROM TMP_INGCLIEBCACEI_UNIVCTASG94;

COMMIT;
SPOOL OFF
quit;