@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

--*********************************************U N I E N D O   T O D O***********************************************
--CREATE TABLE TMP_INGCLIEBCACEI_TRX TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_TRX;
INSERT INTO TMP_INGCLIEBCACEI_TRX
  WITH TMP AS
  (
--AGENTE
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_AGENTE
    UNION
--VENTANILLA
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_VENTANILLA
    UNION
--TRANSFERENCIAS DEL EXTERIOR (REMESAS)
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_REMITTANCE
    UNION
--CAJERO
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_CAJERO
    UNION
--BANCA MOVIL
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_BANCAMOVIL
    UNION
--TELECREDITO
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_TELCRE
    UNION
--HOMEBANKING
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_HM
    UNION
--GGTT
    SELECT CODCLAVECIC_SOL,CODOPECTA_SOL,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA, MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN,FLG_ZAR
    FROM TMP_INGCLIEBCACEI_TRX_GGTT
  )--FILTRO LISTA BLANCA
  SELECT *
  FROM TMP
  WHERE CODCLAVECIC_BEN NOT IN (SELECT CODCLAVECIC
								FROM S55632.LISTABLANCA_CUMP);

COMMIT;
quit;