@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--********************************************************AGENTE********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA Y EXTRAEMOS LOS CODCLAVECIC BENEFICIARIOS

--CREATE TABLE TMP_INGCLIEBCACEI_AGEN_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_AGEN_BEN;
INSERT INTO TMP_INGCLIEBCACEI_AGEN_BEN
 WITH TMP_MOVAGENTE AS
 (
	SELECT
         A.CODCLAVEOPECTACARGO,A.CODUNICOCLI,A.CODCLAVEOPECTAABONO,A.fecdia, A.hortransaccion, A.codmoneda,
         A.mtotransaccion,A.tiptransaccionagenteviabcp,A.CODAGENTEVIABCP
	FROM
         S61751.tmp_movagente_i A
		 LEFT JOIN
               ODS_V.MD_AGENTEVIABCP B ON A.CODCLAVEOPECTAABONO=B.CODCLAVEOPECTA
	WHERE
		A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
		A.TIPTRANSACCIONAGENTEVIABCP IN('03','05') AND
		B.CODCLAVEOPECTA IS NULL AND
        A.CODCLAVEOPECTAABONO IN (SELECT CODCLAVEOPECTA FROM TMP_INGCLIEBCACEI_UNIVCTASCLIE)
	union all
	SELECT
         A.CODCLAVEOPECTACARGO,A.CODUNICOCLI,A.CODCLAVEOPECTAABONO,A.fecdia, A.hortransaccion, A.codmoneda,
         A.mtotransaccion,A.tiptransaccionagenteviabcp,A.CODAGENTEVIABCP
	FROM
         S61751.tmp_movagente_p A
		 LEFT JOIN
               ODS_V.MD_AGENTEVIABCP B ON A.CODCLAVEOPECTAABONO=B.CODCLAVEOPECTA
	WHERE
		A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
		A.TIPTRANSACCIONAGENTEVIABCP IN('03','05') AND
		B.CODCLAVEOPECTA IS NULL AND
        A.CODCLAVEOPECTAABONO IN (SELECT CODCLAVEOPECTA FROM TMP_INGCLIEBCACEI_UNIVCTASCLIE)
  )
  SELECT
         A.*,B.CODCLAVECIC AS CODCLAVECIC_BEN,B.CODOPECTA AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	FROM
       TMP_MOVAGENTE A
		    LEFT JOIN
                  TMP_INGCLIEBCACEI_UNIVCTASCLIE B ON A.CODCLAVEOPECTAABONO=B.CODCLAVEOPECTA;

----CODCLAVECIC SOLICITANTE - TRANSFERENCIAS
--CREATE TABLE TMP_INGCLIEBCACEI_AGEN_SOL TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_AGEN_SOL;
INSERT INTO TMP_INGCLIEBCACEI_AGEN_SOL
       WITH TMP_AGEN_SOL1 AS
       (
         SELECT
                A.*,B.CODCLAVECIC AS CODCLAVECIC_SOL,B.CODOPECTA AS CODOPECTA_SOL
         FROM
              TMP_INGCLIEBCACEI_AGEN_BEN A
              LEFT JOIN
                        ODS_V.MD_CUENTA B ON A.CODCLAVEOPECTACARGO=B.CODCLAVEOPECTA
         WHERE
               A.TIPTRANSACCIONAGENTEVIABCP in ('03')
       ),
       TMP_AGEN_SOL2 AS
       (
          SELECT
                 A.*,B.CODCLAVECIC AS CODCLAVECIC_SOL,'NO APLICA' AS CODOPECTA_SOL
          FROM
               TMP_INGCLIEBCACEI_AGEN_BEN A
               LEFT JOIN
                         ODS_V.MD_CLIENTE B ON A.CODUNICOCLI=B.CODUNICOCLI
          WHERE
                A.TIPTRANSACCIONAGENTEVIABCP in ('05')
       )
       SELECT
              A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia,
              A.HORTRANSACCION,A.CODMONEDA,A.mtotransaccion,A.tiptransaccionagenteviabcp,A.CODAGENTEVIABCP
       FROM
              TMP_AGEN_SOL1 A
       UNION
       SELECT
              B.CODCLAVECIC_SOL,B.CODOPECTA_SOL,B.CODCLAVECIC_BEN,B.CODOPECTA_BEN,B.TIPBANCA_BEN,B.fecdia,
              B.HORTRANSACCION,B.CODMONEDA,B.mtotransaccion,B.tiptransaccionagenteviabcp,B.CODAGENTEVIABCP
       FROM
              TMP_AGEN_SOL2 B;

 --CREATE TABLE TMP_INGCLIEBCACEI_TRX_AGENTE TABLESPACE D_AML_99 AS
 TRUNCATE TABLE TMP_INGCLIEBCACEI_TRX_AGENTE;
 INSERT INTO TMP_INGCLIEBCACEI_TRX_AGENTE
   SELECT
          A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia,
          A.HORTRANSACCION,A.CODMONEDA,A.mtotransaccion,A.mtotransaccion * tc.MtoCambioAlDolar AS MTO_DOLARIZADO,
          d.DESTIPTRANSACCIONAGENTEVIABCP as TIPO_TRANSACCION, 'AGENTE' as CANAL,' ' CODPAISORIGEN,
          CASE
             WHEN CODAGENTEVIABCP IN (SELECT CODAGENTEVIABCP  FROM ODS_V.MD_AGENTEVIABCP
                                      WHERE CODSUCAGE IN ('220000','220002','405000','405003','405004','405005','495000',
                                                         '540000','540002','540004','540005','565000','575000','575001')) THEN '1'
             ELSE '0'
          END FLG_ZAR
   FROM
          TMP_INGCLIEBCACEI_AGEN_SOL A
          LEFT JOIN
                    ods_v.hd_tipocambiosaldodiario tc on A.fecdia = tc.FecTipCambio and A.codmoneda = tc.CodMoneda
          LEFT JOIN
                    ods_v.md_destipotranagenteviabcp d on A.tiptransaccionagenteviabcp = d.TIPTRANSACCIONAGENTEVIABCP
   WHERE
          A.CODCLAVECIC_BEN<>0 AND
          A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************TRANSFERENCIAS DEL EXTERIOR (REMESAS)***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA

--CREATE TABLE TMP_INGCLIEBCACEI_REMITTANCE_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_REMITTANCE_BEN;
INSERT INTO TMP_INGCLIEBCACEI_REMITTANCE_BEN
  WITH TMP_MOVOPERATIVOREMITTANCE AS
  (
    SELECT
           -1 AS CODCLAVECIC_SOL, CODCLAVEOPECTAAFECTADA, FECDIA,HORTRANSACCION,CODMONEDA,MTOTRANSACCION,CODPRODUCTO,MTOTRANSACCIONDOL,CODPAISORIGEN
    FROM
          ODS_V.HD_MOVOPERATIVOREMITTANCE
    WHERE
          FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
          CODPRODUCTO IN ('TRAXAB','TRAXRE','TRAXVE') AND
          CODCLAVEOPECTAAFECTADA IN (SELECT CODCLAVEOPECTA FROM TMP_INGCLIEBCACEI_UNIVCTASCLIE)
  )
	SELECT
        A.*,B.CODCLAVECIC AS CODCLAVECIC_BEN,B.CODOPECTA AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	FROM
       TMP_MOVOPERATIVOREMITTANCE A
		   LEFT JOIN
                 TMP_INGCLIEBCACEI_UNIVCTASCLIE B ON A.CODCLAVEOPECTAAFECTADA=B.CODCLAVEOPECTA;

--TABLA FINAL (FILTRANDO CODCLAVECIC <> 0)

--CREATE TABLE TMP_INGCLIEBCACEI_TRX_REMITTANCE TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_TRX_REMITTANCE;
INSERT INTO TMP_INGCLIEBCACEI_TRX_REMITTANCE
	SELECT DISTINCT
                  A.CODCLAVECIC_SOL,'NO APLICA' AS CODOPECTA_SOL,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia, A.hortransaccion, A.codmoneda, A.mtotransaccion,
			            A.MTOTRANSACCIONDOL AS MTO_DOLARIZADO, d.DESCODPRODUCTO as TIPO_TRANSACCION, 'REMITTANCE' as CANAL,upper(P.nombrepais) as CODPAISORIGEN,'0'FLG_ZAR
	FROM
       TMP_INGCLIEBCACEI_REMITTANCE_BEN A
		   left join
                 ods_v.md_descodigoproducto d on A.codproducto = d.CODPRODUCTO
		   left join
                 s55632.md_codigopais p on trim(A.codpaisorigen) = p.codpais3
	WHERE A.CODCLAVECIC_BEN<>0;

 -- DROP TABLE TMP_MOVCAJERO;
--CREATE TABLE TMP_MOVCAJERO TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_MOVCAJERO;
INSERT INTO TMP_MOVCAJERO
	SELECT
           CODOPECTADESDE,CODCLAVECIC,CODOPECTAHACIA,FECDIA,hortransaccion,
           CASE
                WHEN MTOTRANSACCIONSOL IS NULL OR MTOTRANSACCIONME IS NULL THEN COALESCE(CODMONEDACTADESDE,CODMONEDACTAHACIA)
                ELSE CODMONEDATRAN
           END CODMONEDA,
           COALESCE(
            		   CASE
                				WHEN CODMONEDATRAN = '0001' THEN MTOTRANSACCIONSOL
                				ELSE MTOTRANSACCIONME
            		   END, MTOTRANSACCIONORIGEN
                   ) MTOTRANSACCION,
           codtrancajero,MTOTRANSACCIONSOL,MTOTRANSACCIONME,CODCAJERO
  	FROM
           ods_v.hd_movimientocajero
  	WHERE
           FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))  AND
    		   CODTRANCAJERO IN ('20','40') AND
    		   FLGVALIDA='S' AND
           CODOPECTAHACIA IN (SELECT CODOPECTA FROM TMP_INGCLIEBCACEI_UNIVCTASCLIE);

--CREATE TABLE TMP_INGCLIEBCACEI_CAJERO_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_CAJERO_BEN;
INSERT INTO TMP_INGCLIEBCACEI_CAJERO_BEN
SELECT
        A.*,B.CODCLAVECIC AS CODCLAVECIC_BEN,B.CODOPECTA AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	FROM
       TMP_MOVCAJERO A
		 LEFT JOIN
               TMP_INGCLIEBCACEI_UNIVCTASCLIE B ON A.CODOPECTAHACIA=B.CODOPECTA;

----CODCLAVECIC SOLICITANTE - TRANSFERENCIAS
--CREATE TABLE TMP_INGCLIEBCACEI_CAJERO_SOL TABLESPACE D_AML_99AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_CAJERO_SOL;
INSERT INTO TMP_INGCLIEBCACEI_CAJERO_SOL
       WITH TMP_CAJERO_SOL1 AS
       (
         SELECT
                A.*,B.CODCLAVECIC AS CODCLAVECIC_SOL,A.CODOPECTADESDE AS CODOPECTA_SOL
         FROM
              TMP_INGCLIEBCACEI_CAJERO_BEN A
              LEFT JOIN
                        ODS_V.MD_CUENTA B ON A.CODOPECTADESDE=B.CODOPECTA
         WHERE
               A.CODTRANCAJERO='40'
       ),
       TMP_CAJERO_SOL2 AS
       (
         SELECT
                 A.*, A.CODCLAVECIC AS CODCLAVECIC_SOL,'NO APLICA' AS CODOPECTA_SOL
         FROM
                 TMP_INGCLIEBCACEI_CAJERO_BEN A
         WHERE
                 A.CODTRANCAJERO='20'
       )
       SELECT
               A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,A.CODCLAVECIC_BEN,CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia,
               A.HORTRANSACCION,A.CODMONEDA,A.mtotransaccion,A.codtrancajero,MTOTRANSACCIONSOL,MTOTRANSACCIONME,A.CODCAJERO
       FROM
              TMP_CAJERO_SOL1 A
       UNION
       SELECT
               B.CODCLAVECIC_SOL,B.CODOPECTA_SOL,B.CODCLAVECIC_BEN,B.CODOPECTA_BEN,B.TIPBANCA_BEN,B.fecdia,
               B.HORTRANSACCION,B.CODMONEDA,B.mtotransaccion,B.codtrancajero,B.MTOTRANSACCIONSOL,B.MTOTRANSACCIONME,B.CODCAJERO
       FROM
              TMP_CAJERO_SOL2 B;

--CREATE TABLE TMP_INGCLIEBCACEI_TRX_CAJERO TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_TRX_CAJERO;
INSERT INTO TMP_INGCLIEBCACEI_TRX_CAJERO
    SELECT DISTINCT
                   A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,A.CODCLAVECIC_BEN,CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia, A.hortransaccion, A.codmoneda, A.mtotransaccion,
                  (CASE WHEN A.CODMONEDA = '0001' THEN COALESCE(A.MTOTRANSACCIONSOL,A.MTOTRANSACCION) ELSE COALESCE(A.MTOTRANSACCIONME,A.MTOTRANSACCION) END) * tc.MtoCambioAlDolar as MTO_DOLARIZADO,
                  d.DESCODTRANCAJERO as TIPO_TRANSACCION, 'CAJERO' as CANAL, ' ' CODPAISORIGEN,
                  CASE
                       WHEN CODCAJERO IN (SELECT CODCAJERO FROM ODS_V.MD_CAJERO
                                          WHERE CODSUCAGE IN('220000','220002','405000','405003','405004','405005','495000',
                                                             '540000','540002','540004','540005','565000','575000','575001')) THEN '1'
                       ELSE '0'
                   END FLG_ZAR
    FROM
                   TMP_INGCLIEBCACEI_CAJERO_SOL A
                  LEFT JOIN
                            ods_v.hd_tipocambiosaldodiario tc on A.fecdia = tc.FecTipCambio and A.codmoneda = tc.CodMoneda
                  LEFT JOIN
                            ods_v.mm_descodigotransaccioncajero d on A.codtrancajero = d.codtrancajero
    WHERE
          A.CODCLAVECIC_BEN<>0 AND
          A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************HOME BANKING***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA

--CREATE TABLE TMP_INGCLIEBCACEI_HM_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_HM_BEN;
INSERT INTO TMP_INGCLIEBCACEI_HM_BEN
  WITH TMP_MOVHM AS
  (
  	SELECT
           CODOPECTAORIGEN,CODOPECTADESTINO,FECDIA,HORTRANSACCION,CODMONEDA,MTOTRANSACCION,CODOPEHBCTR
  	FROM
           ods_v.hd_movhomebankingtransaccion
  	WHERE
           FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
  		   TIPRESULTADOTRANSACCION = 'OK' AND
           CODTIPOPERACIONHB='701' AND
           CODOPECTADESTINO IN(SELECT CODOPECTA FROM TMP_INGCLIEBCACEI_UNIVCTASCLIE)
  )
  SELECT
         A.*,B.CODCLAVECIC AS CODCLAVECIC_BEN,B.CODOPECTA AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	FROM
         TMP_MOVHM A
		 LEFT JOIN
               TMP_INGCLIEBCACEI_UNIVCTASCLIE B ON A.CODOPECTADESTINO=B.CODOPECTA;

--EXTRAEMOS LA INFO DE LOS SOLICITANTES

--CREATE TABLE TMP_INGCLIEBCACEI_TRX_HM TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_TRX_HM;
INSERT INTO TMP_INGCLIEBCACEI_TRX_HM
       WITH TMP_HM_SOL AS
       (
        SELECT
               A.*,COALESCE(C.CODCLAVECIC,B.CODCLAVECIC) AS CODCLAVECIC_SOL,A.CODOPECTAORIGEN AS CODOPECTA_SOL
        FROM TMP_INGCLIEBCACEI_HM_BEN A
             LEFT JOIN
                       ODS_V.MD_CUENTA B ON A.CODOPECTAORIGEN=B.CODOPECTA
             LEFT JOIN
                       ODS_V.md_cuentag94 C ON A.CODOPECTAORIGEN=C.CODOPECTA
       )
      SELECT DISTINCT
                      A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia, A.hortransaccion, A.codmoneda, A.MTOTRANSACCION,
    					        A.MTOTRANSACCION * tc.MtoCambioAlDolar as MTO_DOLARIZADO, d.DESCODOPEHBCTR AS TIPO_TRANSACCION,'HOMEBANKING' as CANAL,' ' CODPAISORIGEN, '0'FLG_ZAR
    	FROM
           TMP_HM_SOL A
    			  left join
                      ods_v.hd_tipocambiosaldodiario tc on A.fecdia = tc.FecTipCambio and A.codmoneda = tc.CodMoneda
    			  left join
                      ods_v.md_descodigoopehbctr d on A.codopehbctr = d.CODOPEHBCTR
    	WHERE
            A.CODCLAVECIC_BEN<>0 AND
    		    A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************VENTANILLA***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA

--CREATE TABLE TMP_INGCLIEBCACEI_VENT_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_VENT_BEN;
INSERT INTO TMP_INGCLIEBCACEI_VENT_BEN
  WITH TMP_MOVVENTANILLA AS
  (
  	SELECT
           A.CODCLAVEOPECTA,A.CODCLAVEOPECTADESTINO,A.fecdia, A.HORINITRANSACCION AS HORTRANSACCION,a.codmonedatransaccion as CODMONEDA,A.CODSUCAGE,A.CODSESION,
    		   CASE
      				WHEN a.mtotransaccioncta <> 0 THEN a.mtotransaccioncta
      				ELSE a.mtotransaccion
    		   END AS mtotransaccion,A.CODTRANSACCIONVENTANILLA
  	FROM
           ods_v.hd_transaccionventanilla A
  	WHERE
            FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
      		A.CODTRANSACCIONVENTANILLA in (60,62,63,159,186,187,188) AND
      		A.FLGTRANSACCIONAPROBADA = 'S'
   )
   SELECT
          A.*,B.CODCLAVECIC AS CODCLAVECIC_BEN,B.CODOPECTA AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	 FROM
          TMP_MOVVENTANILLA A
		      LEFT JOIN
                    TMP_INGCLIEBCACEI_UNIVCTASCLIE B ON A.CODCLAVEOPECTADESTINO=B.CODCLAVEOPECTA;

--DROP TABLE TMP_MOVVENTANILLA;
--CREATE TABLE  TMP_MOVVENTANILLA TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_MOVVENTANILLA;
INSERT INTO TMP_MOVVENTANILLA
 SELECT
           A.CODCLAVEOPECTA,A.CODCLAVEOPECTADESTINO,A.fecdia, A.HORINITRANSACCION AS HORTRANSACCION,a.codmonedatransaccion as CODMONEDA,A.CODSUCAGE,A.CODSESION,
    		   CASE
      				WHEN a.mtotransaccioncta <> 0 THEN a.mtotransaccioncta
      				ELSE a.mtotransaccion
    		   END AS mtotransaccion,A.CODTRANSACCIONVENTANILLA
  	FROM
           ods_v.hd_transaccionventanilla A
  	WHERE
            FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
      		A.CODTRANSACCIONVENTANILLA in (60,62,63,159,186,187,188) AND
      		A.FLGTRANSACCIONAPROBADA = 'S';

--CREATE TABLE TMP_INGCLIEBCACEI_VENT_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_VENT_BEN;
INSERT INTO TMP_INGCLIEBCACEI_VENT_BEN
SELECT
          A.*,B.CODCLAVECIC AS CODCLAVECIC_BEN,B.CODOPECTA AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	 FROM
          TMP_MOVVENTANILLA A
		      LEFT JOIN
                    TMP_INGCLIEBCACEI_UNIVCTASCLIE B ON A.CODCLAVEOPECTADESTINO=B.CODCLAVEOPECTA;

--CREATE TABLE TMP_INGCLIEBCACEI_VENTANILLA_SOL TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_VENTANILLA_SOL;
INSERT INTO TMP_INGCLIEBCACEI_VENTANILLA_SOL
       WITH TMP_VENT_SOL1 AS
       (
         SELECT
                A.*,COALESCE(CASE
                                   WHEN b.codunicoclisolicitante='.' THEN ''
                                   ELSE b.codunicoclisolicitante
                              END,
                        		  CASE
                                  WHEN b.codunicocliordenante='.' THEN ''
                                  ELSE b.codunicocliordenante
                              END) as CODUNICOCLI_SOL
          FROM
               TMP_INGCLIEBCACEI_VENT_BEN A
               INNER JOIN
                     ods_v.hd_movlavadodineroventanilla b on a.fecdia = b.fecdia and a.codsucage = b.codsucage and a.codsesion = b.codsesion
          WHERE
                A.CODTRANSACCIONVENTANILLA in (60,62,63)
       ),
       TMP_VENT_SOL2 AS
       (
         SELECT
                A.*,B.CODCLAVECIC AS CODCLAVECIC_SOL,B.CODOPECTA AS CODOPECTA_SOL
         FROM
                TMP_INGCLIEBCACEI_VENT_BEN A
                LEFT JOIN
                          ODS_V.MD_CUENTA B ON A.CODCLAVEOPECTA=B.CODCLAVEOPECTA
         WHERE
               A.CODTRANSACCIONVENTANILLA in (159,186,187,188)
       )
        SELECT
               B.CODCLAVECIC AS CODCLAVECIC_SOL,'NO APLICA' AS CODOPECTA_SOL,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,
               A.fecdia,A.HORTRANSACCION,A.CODMONEDA,A.mtotransaccion,A.CODTRANSACCIONVENTANILLA,A.CODSUCAGE
        FROM
              TMP_VENT_SOL1 A
              LEFT JOIN
                        ODS_V.MD_CLIENTE B ON A.CODUNICOCLI_SOL=B.CODUNICOCLI
        UNION
        SELECT
               B.CODCLAVECIC_SOL,B.CODOPECTA_SOL,B.CODCLAVECIC_BEN,B.CODOPECTA_BEN,B.TIPBANCA_BEN,B.fecdia,B.HORTRANSACCION,
               B.CODMONEDA,B.mtotransaccion,B.CODTRANSACCIONVENTANILLA,B.CODSUCAGE
        FROM
             TMP_VENT_SOL2 B;

--CREATE TABLE TMP_INGCLIEBCACEI_TRX_VENTANILLA TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_TRX_VENTANILLA;
INSERT INTO TMP_INGCLIEBCACEI_TRX_VENTANILLA
  SELECT
         A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia,A.HORTRANSACCION,A.CODMONEDA,A.mtotransaccion,
         A.mtotransaccion * tc.MtoCambioAlDolar AS MTO_DOLARIZADO, d.DESTRANSACCIONVENTANILLA as TIPO_TRANSACCION, 'VENTANILLA' as CANAL,' ' CODPAISORIGEN,
         CASE
                WHEN CODSUCAGE IN('220000','220002','405000','405003','405004','405005','495000',
                                     '540000','540002','540004','540005','565000','575000','575001') THEN '1'
                ELSE '0'
         END FLG_ZAR
  FROM
       TMP_INGCLIEBCACEI_VENTANILLA_SOL A
          left join
                    ods_v.hd_tipocambiosaldodiario tc on A.fecdia = tc.FecTipCambio and A.codmoneda = tc.CodMoneda
          left join
                    ods_v.md_destransaccionventanilla d on A.codtransaccionventanilla = d.CODTRANSACCIONVENTANILLA
  WHERE
        A.CODCLAVECIC_BEN<>0 AND
        A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************TELECREDITO***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA

--CREATE TABLE TMP_INGCLIEBCACEI_TELCRE_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_TELCRE_BEN;
INSERT INTO TMP_INGCLIEBCACEI_TELCRE_BEN
  WITH TMP_MOVTELCRE AS
  (
  	SELECT
           CODOPECTA,CODOPECTAABONO,FECTRANSFERENCIA AS FECDIA,HORTRANSFERENCIA AS HORTRANSACCION,CODMONEDA,
  		     MTOTRANSFERENCIA AS MTOTRANSACCION,TIPOPERACIONTELCRE
  	FROM
           ODS_V.HS_MOVIMIENTOTRANSFERENCTELCRE
  	WHERE 
           FECTRANSFERENCIA  BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
			TIPESTTRANSFERENCIATELCRE=40                           AND
    		   TIPOPERACIONTELCRE IN ('OMTRMT','OMTRTH','OMTRTN') AND
           CODOPECTAABONO IN (SELECT CODOPECTA FROM TMP_INGCLIEBCACEI_UNIVCTASCLIE)
  )
	SELECT
          A.*,B.CODCLAVECIC AS CODCLAVECIC_BEN,B.CODOPECTA AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	FROM
          TMP_MOVTELCRE A
		 LEFT JOIN
              TMP_INGCLIEBCACEI_UNIVCTASCLIE B ON A.CODOPECTAABONO=B.CODOPECTA;

--EXTRAEMOS LA INFO DE LOS SOLICITANTES

--CREATE TABLE TMP_INGCLIEBCACEI_TRX_TELCRE TABLESPACE D_AML_99 AS
TRUNCATE TABLE  TMP_INGCLIEBCACEI_TRX_TELCRE;
INSERT INTO TMP_INGCLIEBCACEI_TRX_TELCRE
       WITH TMP_TELCRE_SOL AS
       (
        	SELECT
                 A.*,COALESCE(C.CODCLAVECIC,B.CODCLAVECIC) AS CODCLAVECIC_SOL,A.CODOPECTA AS CODOPECTA_SOL
        	FROM
               TMP_INGCLIEBCACEI_TELCRE_BEN A
        		 LEFT JOIN
                       ODS_V.MD_CUENTA B ON A.CODOPECTA=B.CODOPECTA
        		 LEFT JOIN
                       ODS_V.md_cuentag94 C ON A.CODOPECTA=C.CODOPECTA
       )
    	SELECT DISTINCT
                      A.CODCLAVECIC_SOL,A.CODOPECTA_SOL ,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia, A.hortransaccion, A.codmoneda, A.MTOTRANSACCION,
    					        A.MTOTRANSACCION * tc.MtoCambioAlDolar as MTO_DOLARIZADO,d.DESTIPOPERACIONTELCRE as TIPO_TRANSACCION,'TELECREDITO' as CANAL,' ' CODPAISORIGEN,'0' FLG_ZAR
    	FROM
           TMP_TELCRE_SOL A
    			  left join
                      ods_v.hd_tipocambiosaldodiario tc on A.FECDIA = tc.FecTipCambio and A.codmoneda = tc.CodMoneda
    			  left join
                      ods_v.MS_TIPOOPERACIONTELCRE d on A.tipoperaciontelcre = d.TIPOPERACIONTELCRE
    	WHERE
            A.CODCLAVECIC_BEN<>0 AND
    		    A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************GGTT***********************************************************

--CREATE TABLE TMP_INGCLIEBCACEI_GGTT_BEN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_GGTT_BEN;
INSERT INTO TMP_INGCLIEBCACEI_GGTT_BEN
  WITH TMP_MOVGGTT AS
  (
    SELECT
           CODCLAVECICSOLICITANTE,CODCLAVECICBENEFICIARIO,FECDIA,HOREMISION,CODMONEDA,
           MTOIMPORTEOPERACION,CODPRODUCTO,CODSWIFTBCODESTINO,CODSWIFTBCOEMISOR
    FROM
           ods_v.hd_documentoemitidoggtt
    WHERE
          FECDIA between TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
          CODTIPESTADOTRANSACCION = '00' AND
          CODCLAVECICBENEFICIARIO IN (SELECT CODCLAVECIC FROM TMP_INGCLIEBCACEI_UNIVCLIE)
  )
	SELECT
          A.*,A.CODCLAVECICBENEFICIARIO AS CODCLAVECIC_BEN,'NO APLICA' AS CODOPECTA_BEN,B.TIPBANCA AS TIPBANCA_BEN
	FROM
          TMP_MOVGGTT A
		 LEFT JOIN
              TMP_INGCLIEBCACEI_UNIVCLIE B ON A.CODCLAVECICBENEFICIARIO=B.CODCLAVECIC;

--EXTRAEMOS LA INFO DE LOS SOLICITANTES

--CREATE TABLE TMP_INGCLIEBCACEI_TRX_GGTT TABLESPACE D_AML_99 AS
TRUNCATE  TABLE TMP_INGCLIEBCACEI_TRX_GGTT;
INSERT INTO TMP_INGCLIEBCACEI_TRX_GGT
       WITH TMP_GGTT_SOL AS
       (
        SELECT
               A.*,A.CODCLAVECICSOLICITANTE AS CODCLAVECIC_SOL,'NO APLICA' AS CODOPECTA_SOL
        FROM TMP_INGCLIEBCACEI_GGTT_BEN A
       )
      SELECT DISTINCT
                      A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,A.fecdia, A.HOREMISION AS HORTRANSACCION, A.codmoneda, A.MTOIMPORTEOPERACION AS MTOTRANSACCION,
    					        A.MTOIMPORTEOPERACION * tc.MtoCambioAlDolar as MTO_DOLARIZADO, d.DESCODPRODUCTO AS TIPO_TRANSACCION,'DOCUMENTO_GGTT' as CANAL,upper(p.nombrepais) as CODPAISORIGEN, '0'FLG_ZAR
    	FROM
      		TMP_GGTT_SOL A
      		left join
                    ods_v.hd_tipocambiosaldodiario tc on A.fecdia = tc.FecTipCambio and A.codmoneda = tc.CodMoneda
      		left join
                    ods_v.md_descodigoproducto d on A.codproducto = d.CODPRODUCTO
      		left join
                    s55632.md_codigopais p on substr(A.codswiftbcoemisor, 5, 2) = p.codpais2
    	WHERE
            A.CODCLAVECIC_BEN NOT IN (0,3288453) AND
    		    A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN AND
            CODCLAVECIC_SOL<>3288453;
COMMIT;
quit;