@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;


CREATE TABLE TMP_INGCLIEBCACEI_CLIE_TOTAL AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIE_TOTAL;
----INSERT INTO TMP_INGCLIEBCACEI_CLIE_TOTAL
  WITH TMP AS
  (
    SELECT DISTINCT CODCLAVECIC_BEN AS CODCLAVECIC FROM TMP_INGCLIEBCACEI_TRX
    UNION
    SELECT DISTINCT CODCLAVECIC_SOL FROM TMP_INGCLIEBCACEI_TRX
  )
  SELECT A.CODCLAVECIC,B.CODUNICOCLI
  FROM TMP A
       LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODCLAVECIC=B.CODCLAVECIC;

--VARIABLE CLIENTE-MES
CREATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT;
----INSERT INTO TMP_INGCLIEBCACEI_CLIEMES_INGRETOT
	SELECT  A.CODCLAVECIC_BEN AS CODCLAVECIC,B.CODUNICOCLI,TO_NUMBER(TO_CHAR(A.FECDIA,'YYYYMM')) NUMPERIODO,
			SUM(MTO_DOLARIZADO) AS MTO_RECIBIDO
	FROM    TMP_INGCLIEBCACEI_TRX A
		INNER JOIN TMP_INGCLIEBCACEI_CLIE_TOTAL B ON A.CODCLAVECIC_BEN=B.CODCLAVECIC
	GROUP BY  A.CODCLAVECIC_BEN,B.CODUNICOCLI,TO_CHAR(A.FECDIA,'YYYYMM');

--TIPO BANCA
CREATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT1 AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT1;
----INSERT INTO TMP_INGCLIEBCACEI_CLIEMES_INGRETOT1
   SELECT A.*,B.TIPBANCA
   FROM   TMP_INGCLIEBCACEI_CLIEMES_INGRETOT A
          LEFT JOIN TMP_INGCLIEBCACEI_UNIVCLIE B ON A.CODCLAVECIC=B.CODCLAVECIC;

--***********************************************REPRESENTANTES LEGALES , ACCIONISTAS Y GERENTES DE LAS EMPRESAS*************************************************
--******************************CODREL***************************
--GERENTES:GAD,GAP,GCO,GFI,GGR,GSP,GTE
--REPRESENTANTE LEGAL: RLG
--******************************CODTIPREL***************************
--ACCIONISTAS: AC
CREATE TABLE TMP_INGCLIEBCACEI_CIC_EMPRESAS AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CIC_EMPRESAS;
----INSERT INTO TMP_INGCLIEBCACEI_CIC_EMPRESAS
    SELECT DISTINCT CODCLAVECIC_BEN AS CODCLAVECIC_EMP
    FROM   TMP_INGCLIEBCACEI_TRX;

CREATE TABLE TMP_INGCLIEBCACEI_REL_EMPRESAS AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_REL_EMPRESAS;
----INSERT INTO TMP_INGCLIEBCACEI_REL_EMPRESAS
    SELECT CODCLAVECIC AS CODCLAVECIC_REL,CODCLAVECICCLIREL AS CODCLAVECIC_EMP
    FROM   ODS_V.MM_RELACIONCLIENTE
    WHERE  CODCLAVECICCLIREL IN (SELECT CODCLAVECIC_EMP FROM TMP_INGCLIEBCACEI_CIC_EMPRESAS) AND
           CODREL IN ('GAD','GAP','GCO','GFI','GGR','GSP','GTE','RLG') OR
           CODTIPREL IN ('AC');

CREATE TABLE TMP_INGCLIEBCACEI_REL_EMPRESAS_FINAL AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_REL_EMPRESAS_FINAL;
----INSERT INTO TMP_INGCLIEBCACEI_REL_EMPRESAS_FINAL
  SELECT A.CODCLAVECIC_EMP, A.CODCLAVECIC_REL,B.CODUNICOCLI AS CODUNICOCLI_REL
  FROM   TMP_INGCLIEBCACEI_REL_EMPRESAS A
       LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODCLAVECIC_REL=B.CODCLAVECIC;

--VARIABLE FLAG ROS HISTORICO DE LOS RELACIONADOS DE LAS EMPRESA
CREATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT2 AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT2;
----INSERT INTO TMP_INGCLIEBCACEI_CLIEMES_INGRETOT2
 WITH TMP_ROS AS
  (
    SELECT DISTINCT CODUNICOCLI
    FROM S85645.SAPY_DMINVESTIGACION
    WHERE IDRESULTADO=2
  ),
   TMP_FLGROS AS
  (
    SELECT DISTINCT A.*,
      		 CASE
               WHEN B.CODUNICOCLI IS NOT NULL THEN 1
               ELSE 0
           END FLG_ROS_REL
    FROM TMP_INGCLIEBCACEI_REL_EMPRESAS_FINAL A
         LEFT JOIN TMP_ROS B ON A.CODUNICOCLI_REL=B.CODUNICOCLI
  ),
  TMP2 AS
  (
  SELECT CODCLAVECIC_EMP,SUM(FLG_ROS_REL) AS FLG_ROS_REL
  FROM TMP_FLGROS
  GROUP BY CODCLAVECIC_EMP
  )
  SELECT DISTINCT
         A.*,
  		CASE
                     WHEN B.CODCLAVECIC_EMP IS NOT NULL THEN
		CASE
			WHEN B.FLG_ROS_REL >0 THEN 1
	       ELSE 0
		END
             ELSE 0
         END FLG_ROS_REL
  FROM TMP_INGCLIEBCACEI_CLIEMES_INGRETOT1 A
       LEFT JOIN TMP2 B ON A.CODCLAVECIC=B.CODCLAVECIC_EMP;

--NOTICIAS PERIODISTICAS
CREATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT3 AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT3;
----INSERT INTO TMP_INGCLIEBCACEI_CLIEMES_INGRETOT3
   WITH TMP_NP AS
  (
    SELECT DISTINCT codunicocli
    FROM S85645.SAPY_DMALERTA
    WHERE IDORIGEN=2
  ),
   TMP_FLG_NP AS
  (
    SELECT DISTINCT A.*,
      		 CASE
               WHEN B.codunicocli IS NOT NULL THEN 1
               ELSE 0
           END FLG_NP_REL
    FROM TMP_INGCLIEBCACEI_REL_EMPRESAS_FINAL A
         LEFT JOIN TMP_NP B ON A.CODUNICOCLI_REL=B.codunicocli
  ),
  TMP2 AS
  (
  SELECT CODCLAVECIC_EMP,SUM(FLG_NP_REL) AS FLG_NP_REL
  FROM TMP_FLG_NP
  GROUP BY CODCLAVECIC_EMP
  )
  SELECT DISTINCT
         A.*,
  		CASE
                     WHEN B.CODCLAVECIC_EMP IS NOT NULL THEN
		CASE
			WHEN B.FLG_NP_REL >0 THEN 1
		ELSE 0
		END
             ELSE 0
         END FLG_NP_REL
  FROM TMP_INGCLIEBCACEI_CLIEMES_INGRETOT2 A
       LEFT JOIN TMP2 B ON A.CODCLAVECIC=B.CODCLAVECIC_EMP;

--LSB
CREATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT4 AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT4;
----INSERT INTO TMP_INGCLIEBCACEI_CLIEMES_INGRETOT4
 WITH TMP_LSB AS
  (
    SELECT DISTINCT codunicocli
    FROM S85645.SAPY_DMALERTA
    WHERE IDORIGEN=29
  ),
   TMP_FLG_LSB AS
  (
    SELECT DISTINCT A.*,
      		 CASE
               WHEN B.codunicocli IS NOT NULL THEN 1
               ELSE 0
           END FLG_LSB_REL
    FROM TMP_INGCLIEBCACEI_REL_EMPRESAS_FINAL A
         LEFT JOIN TMP_LSB B ON A.CODUNICOCLI_REL=B.codunicocli
  ),
  TMP2 AS
  (
  SELECT CODCLAVECIC_EMP,SUM(FLG_LSB_REL) AS FLG_LSB_REL
  FROM TMP_FLG_LSB
  GROUP BY CODCLAVECIC_EMP
  )
  SELECT DISTINCT
         A.*,
  		CASE
                     WHEN B.CODCLAVECIC_EMP IS NOT NULL THEN
		CASE
			WHEN B.FLG_LSB_REL >0 THEN 1
		ELSE 0
		END
             ELSE 0
         END FLG_LSB_REL
  FROM TMP_INGCLIEBCACEI_CLIEMES_INGRETOT3 A
       LEFT JOIN TMP2 B ON A.CODCLAVECIC=B.CODCLAVECIC_EMP;

 --PERFIL TOTAL
 CREATE TABLE tmp_INGCLIEBCACEI_perfi1 AS
--TRUNCATE TABLE tmp_INGCLIEBCACEI_perfi1;
----INSERT INTO tmp_INGCLIEBCACEI_perfi1
	with temp_tab as
	(
	select codclavecic_ben,to_char(fecdia,'YYYYMM') periodo, sum(MTO_DOLARIZADO) acum_mto_dolarizado
	from 	TMP_INGCLIEBCACEI_TRX
	GROUP BY codclavecic_ben,to_char(fecdia,'YYYYMM')
	)
	select  a.codclavecic,a.numperiodo,b.periodo,
			months_between(to_date(a.numperiodo,'YYYYMM'),to_date(b.periodo,'YYYYMM')) meses,
			b.acum_mto_dolarizado
	from TMP_INGCLIEBCACEI_CLIEMES_INGRETOT4 a
		 inner join temp_tab b on (a.codclavecic=b.codclavecic_ben);

CREATE TABLE tmp_INGCLIEBCACEI_perfi2 AS
--TRUNCATE TABLE tmp_INGCLIEBCACEI_perfi2;
----INSERT INTO tmp_INGCLIEBCACEI_perfi2
  select numperiodo,codclavecic,acum_mto_dolarizado
  from tmp_INGCLIEBCACEI_perfi1 a
  where numperiodo=periodo;

CREATE TABLE tmp_INGCLIEBCACEI_perfi3 AS
--TRUNCATE TABLE tmp_INGCLIEBCACEI_perfi3;
----INSERT INTO tmp_INGCLIEBCACEI_perfi3
	with temp_tab as
	(select numperiodo,codclavecic,avg(NULLIF(acum_mto_dolarizado,0)) media_dep,STDDEV(NULLIF(acum_mto_dolarizado,0)) desv_dep 
	 from tmp_INGCLIEBCACEI_perfi1
	 where meses<=6 and meses>=1
	 group by numperiodo,codclavecic
	)
	select a.*,round(nvl(b.media_dep,0),2) media_dep,round(nvl(b.desv_dep,0),2) desv_dep from tmp_INGCLIEBCACEI_perfi2 a
		left join temp_tab b on (a.numperiodo=b.numperiodo and a.codclavecic=b.codclavecic);

--creamos el flg perfil total
CREATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT5 AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT5;
----INSERT INTO TMP_INGCLIEBCACEI_CLIEMES_INGRETOT5
	select  a.*,b.media_dep,b.desv_dep,
				case
					when b.media_dep+3*b.desv_dep<b.acum_mto_dolarizado then 1
					else 0
				end FLG_PERFIL_3DESVT_TRX
	from    TMP_INGCLIEBCACEI_CLIEMES_INGRETOT4 a
			left join tmp_INGCLIEBCACEI_perfi3 b on (a.numperiodo=b.numperiodo and a.codclavecic=b.codclavecic);

--DATASET FINAL
CREATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT6 AS
--TRUNCATE TABLE TMP_INGCLIEBCACEI_CLIEMES_INGRETOT6;
----INSERT INTO TMP_INGCLIEBCACEI_CLIEMES_INGRETOT6
	SELECT 	CODCLAVECIC,
			CODUNICOCLI,
			NUMPERIODO,
			ROUND(MTO_RECIBIDO,2) MTO_RECIBIDO,
			ROUND(media_dep,2) media_dep,
			ROUND(desv_dep,2) desv_dep,
			TIPBANCA,
			FLG_ROS_REL,
			CASE
               WHEN FLG_NP_REL=1 OR FLG_LSB_REL=1 THEN 1
               ELSE 0
			END FLG_LSB_NP_REL,
			FLG_PERFIL_3DESVT_TRX
	FROM TMP_INGCLIEBCACEI_CLIEMES_INGRETOT5
	WHERE MTO_RECIBIDO>1276 AND
	NUMPERIODO=TO_CHAR(TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-1))),'YYYYMM');
COMMIT;
quit;