@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

SET ECHO OFF
SET FEEDBACK OFF
SET HEAD OFF
SET LIN 256
SET TRIMSPOOL ON
SET WRAP OFF
SET PAGES 0
SET TERM OFF
set colsep ','

SPOOL ./data/production/01_raw.csv

PROMPT CODCLAVECIC,NUMPERIODO,MTO_RECIBIDO,TIPBANCA,FLG_ROS_REL,FLG_LSB_NP_REL,FLG_PERFIL_3DESVT_TRX;

SELECT
	CODCLAVECIC||','||
    NUMPERIODO||','||
	REPLACE(TRIM(TO_CHAR(MTO_RECIBIDO,'99999999999999999990D00')),',','.')||','||
	TIPBANCA||','||
	FLG_ROS_REL||','||
	FLG_LSB_NP_REL||','||
	FLG_PERFIL_3DESVT_TRX
FROM TMP_INGCLIEBCACEI_CLIEMES_INGRETOT6;

SPOOL OFF;
quit;