@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

DROP TABLE TMP_TRX_EPIC019_3;
CREATE TABLE TMP_TRX_EPIC019_3 AS
SELECT DISTINCT A.FECDIA,
A.CODSUCAGE,
CODSESION,
HORINITRANSACCION,
DESTRANSACCIONVENTANILLA,
CODMONEDACTA,
MTOTRANSACCIONCTA,
B.CODOPECTA AS CODOPECTA,
C.CODOPECTA AS CODOPECTADESTINO,
E.CODCLAVECIC AS CODCLAVECICSOLICITANTE,
CODUNICOCLISOLICITANTE,
TRIM(E.APEPATCLI)||' '||TRIM(E.APEMATCLI)||' '||TRIM(E.NBRCLI) AS NOMBRESOLICITANTE,
F.CODCLAVECIC AS CODCLAVECICBENEFICIARIO,
CODUNICOCLIBENEFICIARIO,
TRIM(F.APEPATCLI)||' '||TRIM(F.APEMATCLI)||' '||TRIM(F.NBRCLI) AS NOMBREBENEFICIARIO,
G.CODDEPARTAMENTO
 FROM TMP_BASETOP_DOLAUX2_1 A
 INNER JOIN ODS_V.MD_CUENTAG94 B ON A.CODCLAVEOPECTA=B.CODCLAVEOPECTA
 INNER JOIN ODS_V.MD_CUENTAG94 C ON A.CODCLAVEOPECTADESTINO=C.CODCLAVEOPECTA
 INNER JOIN ODS_V.MD_CLIENTEG94 D ON A.CODUNICOCLISOLICITANTE = D.CODUNICOCLI
 INNER JOIN ODS_V.MD_CLIENTEG94 E ON A.CODUNICOCLISOLICITANTE = E.CODUNICOCLI
 INNER JOIN ODS_V.MD_CLIENTEG94 F ON A.CODUNICOCLIBENEFICIARIO = F.CODUNICOCLI
 INNER JOIN TMP_BASETOP_DOLAUX3_1 G ON A.CODUNICOCLIBENEFICIARIO= G.codigo_cliente ;

DROP TABLE TMP_TRX_EPIC019_4;
CREATE TABLE TMP_TRX_EPIC019_4 AS
SELECT DISTINCT A.FECDIA,
A.CODSUCAGE,
CODSESION,
HORINITRANSACCION,
DESTRANSACCIONVENTANILLA,
CODMONEDACTA,
MTOTRANSACCIONCTA,
B.CODOPECTA AS CODOPECTA,
C.CODOPECTA AS CODOPECTADESTINO,
E.CODCLAVECIC AS CODCLAVECICSOLICITANTE,
CODUNICOCLISOLICITANTE,
TRIM(E.APEPATCLI)||' '||TRIM(E.APEMATCLI)||' '||TRIM(E.NBRCLI) AS NOMBRESOLICITANTE,
F.CODCLAVECIC AS CODCLAVECICBENEFICIARIO,
CODUNICOCLIBENEFICIARIO,
TRIM(F.APEPATCLI)||' '||TRIM(F.APEMATCLI)||' '||TRIM(F.NBRCLI) AS NOMBREBENEFICIARIO,
G.CODDEPARTAMENTO
 FROM TMP_BASETOP_DOLAUX2_1 A
 INNER JOIN ODS_V.MD_CUENTAG94 B ON A.CODCLAVEOPECTA=B.CODCLAVEOPECTA
 INNER JOIN ODS_V.MD_CUENTAG94 C ON A.CODCLAVEOPECTADESTINO=C.CODCLAVEOPECTA
 INNER JOIN ODS_V.MD_CLIENTEG94 D ON A.CODUNICOCLISOLICITANTE = D.CODUNICOCLI
 INNER JOIN ODS_V.MD_CLIENTEG94 E ON A.CODUNICOCLISOLICITANTE = E.CODUNICOCLI
 INNER JOIN ODS_V.MD_CLIENTEG94 F ON A.CODUNICOCLIBENEFICIARIO = F.CODUNICOCLI
 INNER JOIN TMP_BASETOP_DOLAUX3_1 G ON A.CODUNICOCLISOLICITANTE= G.codigo_cliente ;

COMMIT;
SPOOL OFF
QUIT;