@&1 --PARAMETRO DE CREDENCIALES

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

--UNIVERSO CLIENTES
--TRUNCATE TABLE TMP_CONOCMCDO_UNIVCLIE;
--INSERT INTO TMP_CONOCMCDO_UNIVCLIE 
CREATE TABLE TMP_CONOCMCDO_UNIVCLIE AS
WITH TMP AS (
        SELECT DISTINCT CODCLAVECIC
        FROM TMP_CONOCMCDO_UNIPREV03
    )
SELECT 
  A.CODCLAVECIC,
  B.CODUNICOCLI
FROM TMP A
LEFT JOIN ODS_V.MD_CLIENTEG94 B ON A.CODCLAVECIC = B.CODCLAVECIC
WHERE B.CODUNICOCLI IS NOT NULL
AND B.CODUNICOCLI <> '.'
AND B.FLGREGELIMINADO = 'N';

--UNIVERSO CUENTAS
--TRUNCATE TABLE TMP_CONOCMCDO_UNIVCTASCLIE;
--INSERT INTO TMP_CONOCMCDO_UNIVCTASCLIE
CREATE TABLE TMP_CONOCMCDO_UNIVCTASCLIE AS
SELECT A.CODCLAVECIC,
    A.CODUNICOCLI,
    B.CODCLAVEOPECTA,
    B.CODOPECTA
FROM TMP_CONOCMCDO_UNIVCLIE A
INNER JOIN ODS_V.MD_CUENTAG94 B ON A.CODCLAVECIC = B.CODCLAVECIC
WHERE B.CODSISTEMAORIGEN IN ('SAV', 'IMP')
AND B.CODOPECTA IS NOT NULL
AND B.CODOPECTA <> '.'
AND B.FLGREGELIMINADO = 'N';

QUIT;