--PARAMETRO DE CREDENCIALES
@&1 

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--***********************************************************************AGENTE***********************************************************************
--ACORTAMOS EL PERIODO DE LA TABLA Y EXTRAEMOS LOS CODCLAVECIC BENEFICIARIOS

TRUNCATE TABLE TMP_CONOCMCDO_AGEN_BEN;
INSERT INTO TMP_CONOCMCDO_AGEN_BEN
--CREATE TABLE TMP_CONOCMCDO_AGEN_BEN AS
WITH TMP_MOVAGENTE AS (
       SELECT A.CODCLAVEOPECTACARGO,
       A.CODUNICOCLI,
       A.CODCLAVEOPECTAABONO,
       A.FECDIA,
       A.HORTRANSACCION,
       A.CODMONEDA,
       A.MTOTRANSACCION,
       A.TIPTRANSACCIONAGENTEVIABCP,
       A.CODAGENTEVIABCP 
FROM T23377.TMP_MOVAGENTE_I A --ODS_V.HD_MOVIMIENTOAGENTEVIABCP A
LEFT JOIN ODS_V.MD_AGENTEVIABCP B ON A.CODCLAVEOPECTAABONO=B.CODCLAVEOPECTA
WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)))
AND A.TIPTRANSACCIONAGENTEVIABCP IN('03', '05') AND A.TIPESTTRANSACCIONAGENTEVIABCP = 'P'
AND B.CODCLAVEOPECTA IS NULL AND A.CODCLAVEOPECTAABONO IN (SELECT CODCLAVEOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE) 
UNION ALL 
SELECT A.CODCLAVEOPECTACARGO,
       A.CODUNICOCLI,
       A.CODCLAVEOPECTAABONO,
       A.FECDIA,
       A.HORTRANSACCION,
       A.CODMONEDA,
       A.MTOTRANSACCION,
       A.TIPTRANSACCIONAGENTEVIABCP,
       A.CODAGENTEVIABCP 
FROM T23377.TMP_MOVAGENTE_P A --ODS_V.HD_MOVIMIENTOAGENTEVIABCP A
LEFT JOIN ODS_V.MD_AGENTEVIABCP B ON A.CODCLAVEOPECTAABONO=B.CODCLAVEOPECTA
WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)))
AND A.TIPTRANSACCIONAGENTEVIABCP IN('03', '05') AND A.TIPESTTRANSACCIONAGENTEVIABCP = 'P'
AND B.CODCLAVEOPECTA IS NULL
AND A.CODCLAVEOPECTAABONO IN (SELECT CODCLAVEOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
)
SELECT
       A.*,
       B.CODCLAVECIC AS CODCLAVECIC_BEN,
       B.CODOPECTA   AS CODOPECTA_BEN
FROM TMP_MOVAGENTE A
LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B ON A.CODCLAVEOPECTAABONO=B.CODCLAVEOPECTA;

----CREATE INDEX TMP_CONOCMCDO_IDX_CUC_AGENTE ON TMP_CONOCMCDO_AGEN_BEN(CODUNICOCLI);

----CODCLAVECIC SOLICITANTE - TRANSFERENCIAS
TRUNCATE TABLE TMP_CONOCMCDO_AGEN_SOL;

INSERT INTO TMP_CONOCMCDO_AGEN_SOL
--CREATE TABLE TMP_CONOCMCDO_AGEN_SOL AS
WITH TMP_AGEN_SOL1 AS (
       SELECT A.*,
       B.CODCLAVECIC AS CODCLAVECIC_SOL,
       B.CODOPECTA AS CODOPECTA_SOL 
       FROM TMP_CONOCMCDO_AGEN_BEN A 
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODCLAVEOPECTACARGO=B.CODCLAVEOPECTA 
       WHERE A.TIPTRANSACCIONAGENTEVIABCP IN ('03')
),
TMP_AGEN_SOL2 AS (
       SELECT A.*,
       B.CODCLAVECIC AS CODCLAVECIC_SOL,
       'NO APLICA' AS CODOPECTA_SOL 
       FROM TMP_CONOCMCDO_AGEN_BEN A 
       LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODUNICOCLI=B.CODUNICOCLI 
       WHERE A.TIPTRANSACCIONAGENTEVIABCP IN ('05')
)
       SELECT
              A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.TIPTRANSACCIONAGENTEVIABCP,
              A.CODAGENTEVIABCP
       FROM
              TMP_AGEN_SOL1          A UNION
              SELECT
                     B.CODCLAVECIC_SOL,
                     B.CODOPECTA_SOL,
                     B.CODCLAVECIC_BEN,
                     B.CODOPECTA_BEN,
                     B.FECDIA,
                     B.HORTRANSACCION,
                     B.CODMONEDA,
                     B.MTOTRANSACCION,
                     B.TIPTRANSACCIONAGENTEVIABCP,
                     B.CODAGENTEVIABCP
              FROM
                     TMP_AGEN_SOL2          B;

TRUNCATE TABLE TMP_CONOCMCDO_TRX_AGENTE;
INSERT INTO TMP_CONOCMCDO_TRX_AGENTE
--CREATE TABLE TMP_CONOCMCDO_TRX_AGENTE AS
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESTIPTRANSACCIONAGENTEVIABCP        AS TIPO_TRANSACCION,
              'AGENTE'                               AS CANAL,
              ' '                                    CODPAISORIGEN
       FROM
              TMP_CONOCMCDO_AGEN_SOL           A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC
              ON A.FECDIA = TC.FECTIPCAMBIO
              AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESTIPOTRANAGENTEVIABCP D
              ON A.TIPTRANSACCIONAGENTEVIABCP = D.TIPTRANSACCIONAGENTEVIABCP
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************TRANSFERENCIAS DEL EXTERIOR (REMESAS)***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA
TRUNCATE TABLE TMP_CONOCMCDO_REMITTANCE_BEN;
INSERT INTO TMP_CONOCMCDO_REMITTANCE_BEN
--CREATE TABLE TMP_CONOCMCDO_REMITTANCE_BEN AS
WITH TMP_MOVOPERATIVOREMITTANCE AS (
       SELECT -1 AS CODCLAVECIC_SOL,
       CODCLAVEOPECTAAFECTADA,
       FECDIA,
       HORTRANSACCION,
       CODMONEDA,
       MTOTRANSACCION,
       CODPRODUCTO,
       MTOTRANSACCIONDOL,
       CODPAISORIGEN FROM ODS_V.HD_MOVOPERATIVOREMITTANCE
       WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)))
       AND CODPRODUCTO IN ('TRAXAB', 'TRAXRE', 'TRAXVE') AND CODCLAVEOPECTAAFECTADA IN (SELECT CODCLAVEOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
)
       SELECT
              A.*,
              B.CODCLAVECIC AS CODCLAVECIC_BEN,
              B.CODOPECTA   AS CODOPECTA_BEN
       FROM
              TMP_MOVOPERATIVOREMITTANCE A
              LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
              ON A.CODCLAVEOPECTAAFECTADA=B.CODCLAVEOPECTA;

--TABLA FINAL (FILTRANDO CODCLAVECIC <> 0)
TRUNCATE TABLE TMP_CONOCMCDO_TRX_REMITTANCE;
INSERT INTO TMP_CONOCMCDO_TRX_REMITTANCE
--CREATE TABLE TMP_CONOCMCDO_TRX_REMITTANCE AS
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              'NO APLICA'         AS CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCIONDOL AS MTO_DOLARIZADO,
              D.DESCODPRODUCTO    AS TIPO_TRANSACCION,
              'REMITTANCE'        AS CANAL,
              UPPER(P.NOMBREPAIS) AS CODPAISORIGEN
       FROM
              TMP_CONOCMCDO_REMITTANCE_BEN A
              LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D
              ON A.CODPRODUCTO = D.CODPRODUCTO
              LEFT JOIN S55632.MD_CODIGOPAIS P
              ON TRIM(A.CODPAISORIGEN) = P.CODPAIS3
       WHERE
              A.CODCLAVECIC_BEN<>0;

--***************************************************CAJERO***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA

TRUNCATE TABLE TMP_CONOCMCDO_MOVCAJERO;
INSERT INTO TMP_CONOCMCDO_MOVCAJERO
--CREATE TABLE TMP_CONOCMCDO_MOVCAJERO TABLESPACE D_AML_99 AS
SELECT
       CODOPECTADESDE,
       CODCLAVECIC,
       CODOPECTAHACIA,
       FECDIA,
       HORTRANSACCION,
       CASE
              WHEN MTOTRANSACCIONSOL IS NULL OR MTOTRANSACCIONME IS NULL THEN
                     COALESCE(CODMONEDACTADESDE, CODMONEDACTAHACIA)
              ELSE
                     CODMONEDATRAN
       END                    CODMONEDA,
       COALESCE( CASE
              WHEN CODMONEDATRAN = '0001' THEN
                     MTOTRANSACCIONSOL
              ELSE
                     MTOTRANSACCIONME
       END,
       MTOTRANSACCIONORIGEN ) MTOTRANSACCION,
       CODTRANCAJERO,
       MTOTRANSACCIONSOL,
       MTOTRANSACCIONME,
       CODCAJERO
FROM ODS_V.HD_MOVIMIENTOCAJERO
WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
AND CODTRANCAJERO IN ('20','40')
AND FLGVALIDA='S';

TRUNCATE TABLE TMP_CONOCMCDO_CAJERO_BEN;
INSERT INTO TMP_CONOCMCDO_CAJERO_BEN
       SELECT
              A.*,
              B.CODCLAVECIC AS CODCLAVECIC_BEN,
              B.CODOPECTA   AS CODOPECTA_BEN
       FROM
              TMP_CONOCMCDO_MOVCAJERO              A
              LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
              ON A.CODOPECTAHACIA=B.CODOPECTA;

----CODCLAVECIC SOLICITANTE - TRANSFERENCIAS
TRUNCATE TABLE TMP_CONOCMCDO_CAJERO_SOL;
INSERT INTO TMP_CONOCMCDO_CAJERO_SOL
--CREATE TABLE TMP_CONOCMCDO_CAJERO_SOL AS
WITH TMP_CAJERO_SOL1 AS (
       SELECT A.*,
       B.CODCLAVECIC AS CODCLAVECIC_SOL,
       A.CODOPECTADESDE AS CODOPECTA_SOL FROM TMP_CONOCMCDO_CAJERO_BEN A LEFT JOIN ODS_V.MD_CUENTA B ON A.CODOPECTADESDE=B.CODOPECTA WHERE A.CODTRANCAJERO='40'
),
TMP_CAJERO_SOL2 AS (
       SELECT A.*,
       A.CODCLAVECIC AS CODCLAVECIC_SOL,
       'NO APLICA' AS CODOPECTA_SOL FROM TMP_CONOCMCDO_CAJERO_BEN A WHERE A.CODTRANCAJERO='20'
)
       SELECT
              A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.CODTRANCAJERO,
              MTOTRANSACCIONSOL,
              MTOTRANSACCIONME,
              A.CODCAJERO
       FROM
              TMP_CAJERO_SOL1          A UNION
              SELECT
                     B.CODCLAVECIC_SOL,
                     B.CODOPECTA_SOL,
                     B.CODCLAVECIC_BEN,
                     B.CODOPECTA_BEN,
                     B.FECDIA,
                     B.HORTRANSACCION,
                     B.CODMONEDA,
                     B.MTOTRANSACCION,
                     B.CODTRANCAJERO,
                     B.MTOTRANSACCIONSOL,
                     B.MTOTRANSACCIONME,
                     B.CODCAJERO
              FROM
                     TMP_CAJERO_SOL2          B;

TRUNCATE TABLE TMP_CONOCMCDO_TRX_CAJERO;
INSERT INTO TMP_CONOCMCDO_TRX_CAJERO
--CREATE TABLE TMP_CONOCMCDO_TRX_CAJERO AS
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              (CASE
                     WHEN A.CODMONEDA = '0001' THEN
                            COALESCE(A.MTOTRANSACCIONSOL, A.MTOTRANSACCION)
                     ELSE
                            COALESCE(A.MTOTRANSACCIONME, A.MTOTRANSACCION)
              END) * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESCODTRANCAJERO         AS TIPO_TRANSACCION,
              'CAJERO'                   AS CANAL,
              ' '                        CODPAISORIGEN
       FROM
              TMP_CONOCMCDO_CAJERO_SOL            A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC
              ON A.FECDIA = TC.FECTIPCAMBIO
              AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MM_DESCODIGOTRANSACCIONCAJERO D
              ON A.CODTRANCAJERO = D.CODTRANCAJERO
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN
              AND A.CODMONEDA IS NOT NULL;

--***************************************************HOME BANKING***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA
TRUNCATE TABLE TMP_CONOCMCDO_HM_BEN;
INSERT INTO TMP_CONOCMCDO_HM_BEN
--CREATE TABLE TMP_CONOCMCDO_HM_BEN AS
WITH TMP_MOVHM AS (
       SELECT CODOPECTAORIGEN,
       CODOPECTADESTINO,
       FECDIA,
       HORTRANSACCION,
       CODMONEDA,
       MTOTRANSACCION,
       CODOPEHBCTR FROM ODS_V.HD_MOVHOMEBANKINGTRANSACCION
       WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)))
       AND TIPRESULTADOTRANSACCION = 'OK' 
       AND CODTIPOPERACIONHB='701' 
       AND CODOPECTADESTINO IN(SELECT CODOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
)
       SELECT
              A.*,
              B.CODCLAVECIC AS CODCLAVECIC_BEN,
              B.CODOPECTA   AS CODOPECTA_BEN
       FROM
              TMP_MOVHM                  A
              LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
              ON A.CODOPECTADESTINO=B.CODOPECTA;

--CREATE INDEX IDX_CONOCMCDO_CODPECTAORIGEN_HB ON TMP_CONOCMCDO_HM_BEN (CODOPECTAORIGEN);
--CREATE INDEX IDX_CONOCMCDO_CODOPECTADESTINO_HB ON TMP_CONOCMCDO_HM_BEN (CODOPECTADESTINO);

--EXTRAEMOS LA INFO DE LOS SOLICITANTES
TRUNCATE TABLE TMP_CONOCMCDO_TRX_HM;
INSERT INTO TMP_CONOCMCDO_TRX_HM
--CREATE TABLE TMP_CONOCMCDO_TRX_HM AS
WITH TMP_HM_SOL AS (
       SELECT A.*,
       COALESCE(C.CODCLAVECIC, B.CODCLAVECIC) AS CODCLAVECIC_SOL,
       A.CODOPECTAORIGEN AS CODOPECTA_SOL 
       FROM TMP_CONOCMCDO_HM_BEN A 
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODOPECTAORIGEN=B.CODOPECTA 
       LEFT JOIN ODS_V.MD_CUENTAG94 C ON A.CODOPECTAORIGEN=C.CODOPECTA
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESCODOPEHBCTR                       AS TIPO_TRANSACCION,
              'HOMEBANKING'                          AS CANAL,
              ' '                                    CODPAISORIGEN
       FROM
              TMP_HM_SOL                     A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON A.FECDIA = TC.FECTIPCAMBIO AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESCODIGOOPEHBCTR D ON A.CODOPEHBCTR = D.CODOPEHBCTR
       WHERE A.CODCLAVECIC_BEN<>0
       AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************VENTANILLA***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA
TRUNCATE TABLE TMP_CONOCMCDO_MOVVENTANILLA;
INSERT INTO TMP_CONOCMCDO_MOVVENTANILLA
--CREATE TABLE TMP_CONOCMCDO_MOVVENTANILLA TABLESPACE D_AML_99 AS
SELECT
       A.CODCLAVEOPECTA,
       A.CODCLAVEOPECTADESTINO,
       A.FECDIA,
       A.HORINITRANSACCION    AS HORTRANSACCION,
       A.CODMONEDATRANSACCION AS CODMONEDA,
       A.CODSUCAGE,
       A.CODSESION,
       CASE
              WHEN A.MTOTRANSACCIONCTA <> 0 THEN
                     A.MTOTRANSACCIONCTA
              ELSE
                     A.MTOTRANSACCION
       END                    AS MTOTRANSACCION,
       A.CODTRANSACCIONVENTANILLA
FROM ODS_V.HD_TRANSACCIONVENTANILLA A
WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
AND A.CODTRANSACCIONVENTANILLA IN (60,62,63,159,186,187,188)
AND A.FLGTRANSACCIONAPROBADA = 'S';

TRUNCATE TABLE TMP_CONOCMCDO_VENT_BEN;
INSERT INTO TMP_CONOCMCDO_VENT_BEN
SELECT
       A.*,
       B.CODCLAVECIC AS CODCLAVECIC_BEN,
       B.CODOPECTA   AS CODOPECTA_BEN
FROM TMP_CONOCMCDO_MOVVENTANILLA A
LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B ON A.CODCLAVEOPECTADESTINO=B.CODCLAVEOPECTA;

TRUNCATE TABLE TMP_CONOCMCDO_VENTANILLA_SOL;
INSERT INTO TMP_CONOCMCDO_VENTANILLA_SOL
--CREATE TABLE TMP_CONOCMCDO_VENTANILLA_SOL AS
WITH TMP_VENT_SOL1 AS (
       SELECT A.*,
       COALESCE(CASE 
       WHEN B.CODUNICOCLISOLICITANTE='.' THEN '' 
       ELSE B.CODUNICOCLISOLICITANTE END, 
       CASE WHEN B.CODUNICOCLIORDENANTE='.' THEN '' 
       ELSE B.CODUNICOCLIORDENANTE END) AS CODUNICOCLI_SOL 
       FROM TMP_CONOCMCDO_VENT_BEN A 
       INNER JOIN ODS_V.HD_MOVLAVADODINEROVENTANILLA B ON A.FECDIA = B.FECDIA AND A.CODSUCAGE = B.CODSUCAGE AND A.CODSESION = B.CODSESION 
       WHERE A.CODTRANSACCIONVENTANILLA IN (60, 62, 63)
),
TMP_VENT_SOL2 AS (
       SELECT A.*,
       B.CODCLAVECIC AS CODCLAVECIC_SOL,
       B.CODOPECTA AS CODOPECTA_SOL 
       FROM TMP_CONOCMCDO_VENT_BEN A 
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODCLAVEOPECTA=B.CODCLAVEOPECTA 
       WHERE A.CODTRANSACCIONVENTANILLA IN (159, 186, 187, 188)
)
       SELECT
              B.CODCLAVECIC AS CODCLAVECIC_SOL,
              'NO APLICA'   AS CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.CODTRANSACCIONVENTANILLA,
              A.CODSUCAGE
       FROM
              TMP_VENT_SOL1                      A
              LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODUNICOCLI_SOL=B.CODUNICOCLI 
       UNION
       SELECT
              B.CODCLAVECIC_SOL,
              B.CODOPECTA_SOL,
              B.CODCLAVECIC_BEN,
              B.CODOPECTA_BEN,
              B.FECDIA,
              B.HORTRANSACCION,
              B.CODMONEDA,
              B.MTOTRANSACCION,
              B.CODTRANSACCIONVENTANILLA,
              B.CODSUCAGE
       FROM TMP_VENT_SOL2 B;

TRUNCATE TABLE TMP_CONOCMCDO_TRX_VENTANILLA;
INSERT INTO TMP_CONOCMCDO_TRX_VENTANILLA
--CREATE TABLE TMP_CONOCMCDO_TRX_VENTANILLA AS
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESTRANSACCIONVENTANILLA             AS TIPO_TRANSACCION,
              'VENTANILLA'                           AS CANAL,
              ' '                                    CODPAISORIGEN
       FROM
              TMP_CONOCMCDO_VENTANILLA_SOL      A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON A.FECDIA = TC.FECTIPCAMBIO AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA D ON A.CODTRANSACCIONVENTANILLA = D.CODTRANSACCIONVENTANILLA
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************TELECREDITO***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA
TRUNCATE TABLE TMP_CONOCMCDO_TELCRE_BEN;
INSERT INTO TMP_CONOCMCDO_TELCRE_BEN
--CREATE TABLE TMP_CONOCMCDO_TELCRE_BEN AS
WITH TMP_MOVTELCRE AS (
       SELECT CODOPECTA,
       CODOPECTAABONO,
       FECTRANSFERENCIA AS FECDIA,
       HORTRANSFERENCIA AS HORTRANSACCION,
       CODMONEDA,
       MTOTRANSFERENCIA AS MTOTRANSACCION,
       TIPOPERACIONTELCRE 
       FROM ODS_V.HS_MOVIMIENTOTRANSFERENCTELCRE 
       WHERE FECTRANSFERENCIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
       AND TIPESTTRANSFERENCIATELCRE=40 
       AND TIPOPERACIONTELCRE IN ('OMTRMT', 'OMTRTH', 'OMTRTN') 
       AND CODOPECTAABONO IN (SELECT CODOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
)
SELECT
       A.*,
       B.CODCLAVECIC    AS CODCLAVECIC_BEN,
       B.CODOPECTA      AS CODOPECTA_BEN
FROM TMP_MOVTELCRE              A
LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B ON A.CODOPECTAABONO=B.CODOPECTA;

--EXTRAEMOS LA INFO DE LOS SOLICITANTES
TRUNCATE TABLE TMP_CONOCMCDO_TRX_TELCRE;
INSERT INTO TMP_CONOCMCDO_TRX_TELCRE
--CREATE TABLE TMP_CONOCMCDO_TRX_TELCRE AS
WITH TMP_TELCRE_SOL AS (
       SELECT A.*,
       COALESCE(C.CODCLAVECIC, B.CODCLAVECIC) AS CODCLAVECIC_SOL,
       A.CODOPECTA AS CODOPECTA_SOL FROM TMP_CONOCMCDO_TELCRE_BEN A 
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODOPECTA=B.CODOPECTA 
       LEFT JOIN ODS_V.MD_CUENTAG94 C ON A.CODOPECTA=C.CODOPECTA
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESTIPOPERACIONTELCRE                AS TIPO_TRANSACCION,
              'TELECREDITO'                          AS CANAL,
              ' '                                    CODPAISORIGEN
       FROM
              TMP_TELCRE_SOL                 A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC
              ON A.FECDIA = TC.FECTIPCAMBIO
              AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MS_TIPOOPERACIONTELCRE D
              ON A.TIPOPERACIONTELCRE = D.TIPOPERACIONTELCRE
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************GGTT***********************************************************
TRUNCATE TABLE TMP_CONOCMCDO_GGTT_BEN;
INSERT INTO TMP_CONOCMCDO_GGTT_BEN
--CREATE TABLE TMP_CONOCMCDO_GGTT_BEN AS
WITH TMP_MOVGGTT AS (
       SELECT CODCLAVECICSOLICITANTE,
       CODCLAVECICBENEFICIARIO,
       FECDIA,
       HOREMISION,
       CODMONEDA,
       MTOIMPORTEOPERACION,
       CODPRODUCTO,
       CODSWIFTBCODESTINO,
       CODSWIFTBCOEMISOR FROM ODS_V.HD_DOCUMENTOEMITIDOGGTT 
       WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
       AND CODTIPESTADOTRANSACCION = '00' AND CODCLAVECICBENEFICIARIO IN (SELECT CODCLAVECIC FROM TMP_CONOCMCDO_UNIVCLIE)
)
SELECT
       A.*,
       A.CODCLAVECICBENEFICIARIO AS CODCLAVECIC_BEN,
       'NO APLICA'               AS CODOPECTA_BEN
FROM TMP_MOVGGTT            A
LEFT JOIN TMP_CONOCMCDO_UNIVCLIE B ON A.CODCLAVECICBENEFICIARIO=B.CODCLAVECIC;

--EXTRAEMOS LA INFO DE LOS SOLICITANTES
TRUNCATE TABLE TMP_CONOCMCDO_TRX_GGTT;
INSERT INTO TMP_CONOCMCDO_TRX_GGTT
--CREATE TABLE TMP_CONOCMCDO_TRX_GGTT AS
WITH TMP_GGTT_SOL AS (
       SELECT A.*,
       A.CODCLAVECICSOLICITANTE AS CODCLAVECIC_SOL,
       'NO APLICA' AS CODOPECTA_SOL FROM TMP_CONOCMCDO_GGTT_BEN A
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODOPECTA_SOL,
              A.CODCLAVECIC_BEN,
              A.CODOPECTA_BEN,
              A.FECDIA,
              A.HOREMISION                                AS HORTRANSACCION,
              A.CODMONEDA,
              A.MTOIMPORTEOPERACION                       AS MTOTRANSACCION,
              A.MTOIMPORTEOPERACION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESCODPRODUCTO                            AS TIPO_TRANSACCION,
              'DOCUMENTO_GGTT'                            AS CANAL,
              UPPER(P.NOMBREPAIS)                         AS CODPAISORIGEN
       FROM
              TMP_GGTT_SOL                   A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON A.FECDIA = TC.FECTIPCAMBIO AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D ON A.CODPRODUCTO = D.CODPRODUCTO
              LEFT JOIN S55632.MD_CODIGOPAIS P ON SUBSTR(A.CODSWIFTBCOEMISOR, 5, 2) = P.CODPAIS2
       WHERE
              A.CODCLAVECIC_BEN NOT IN (0, 3288453)
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN
              AND CODCLAVECIC_SOL<>3288453;

QUIT;