--PARAMETRO DE CREDENCIALES
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--***************************************************BANCA MOVIL***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA Y EXTRAEMOS LOS CODCLAVECIC BENEFICIARIOS

TRUNCATE TABLE TMP_CONOCMCDO_BANCAMOVIL_SOL_2;
INSERT INTO TMP_CONOCMCDO_BANCAMOVIL_SOL_2
--CREATE TABLE TMP_CONOCMCDO_BANCAMOVIL_SOL_2 AS
	SELECT
		A.CODCLAVEOPECTAORIGEN,
		A.CODCLAVEOPECTADESTINO,
		A.FECTRANSACCION       AS FECDIA,
		A.HORTRANSACCION,
		A.CODMONEDATRANSACCION AS CODMONEDA,
		A.MTOTRANSACCION,
		A.TIPTRANSACCIONBCAMOVIL,
		B.CODCLAVECIC          AS CODCLAVECIC_SOL
	FROM
		T23377.TMP_MOVBCAMOVIL_I          A
		INNER JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
		ON A.CODCLAVEOPECTAORIGEN=B.CODCLAVEOPECTA
	WHERE A.FECTRANSACCION BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
	AND TIPTRANSACCIONBCAMOVIL=2 
	UNION ALL
	SELECT
		A.CODCLAVEOPECTAORIGEN,
		A.CODCLAVEOPECTADESTINO,
		A.FECTRANSACCION       AS FECDIA,
		A.HORTRANSACCION,
		A.CODMONEDATRANSACCION AS CODMONEDA,
		A.MTOTRANSACCION,
		A.TIPTRANSACCIONBCAMOVIL,
		B.CODCLAVECIC          AS CODCLAVECIC_SOL
	FROM T23377.TMP_MOVBCAMOVIL_P          A
	INNER JOIN TMP_CONOCMCDO_UNIVCTASCLIE B ON A.CODCLAVEOPECTAORIGEN=B.CODCLAVEOPECTA
	WHERE A.FECTRANSACCION BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)))
	AND TIPTRANSACCIONBCAMOVIL=2;

--EXTRAEMOS LA INFO DE LOS SOLICITANTES
TRUNCATE TABLE TMP_CONOCMCDO_TRX_BANCAMOVIL_2;
INSERT INTO TMP_CONOCMCDO_TRX_BANCAMOVIL_2
--CREATE TABLE TMP_CONOCMCDO_TRX_BANCAMOVIL_2 AS
WITH TMP_BANCAMOVIL_BEN AS (
	SELECT A.*,
	B.CODCLAVECIC AS CODCLAVECIC_BEN 
	FROM TMP_CONOCMCDO_BANCAMOVIL_SOL_2 A 
	LEFT JOIN ODS_V.MD_CUENTA B ON A.CODCLAVEOPECTADESTINO=B.CODCLAVEOPECTA
)
	SELECT
		DISTINCT A.CODCLAVECIC_SOL,
		A.CODCLAVECIC_BEN,
		A.FECDIA,
		A.HORTRANSACCION,
		A.CODMONEDA,
		A.MTOTRANSACCION,
		A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
		D.DESTIPTRANSACCIONBCAMOVIL            AS TIPO_TRANSACCION,
		'BANCA MOVIL'                          AS CANAL,
		' '                                    CODPAISORIGEN
	FROM
		TMP_BANCAMOVIL_BEN                 A
		LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON A.FECDIA = TC.FECTIPCAMBIO AND A.CODMONEDA = TC.CODMONEDA
		LEFT JOIN ODS_V.MM_DESTIPTRANSACCIONBCAMOVIL D ON A.TIPTRANSACCIONBCAMOVIL = D.TIPTRANSACCIONBCAMOVIL
	WHERE A.CODCLAVECIC_BEN<>0
	AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

QUIT;