--PARAMETRO DE CREDENCIALES
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--*******************************************************************AGENTE*******************************************************************
--ACORTAMOS EL PERIODO DE LA TABLA Y EXTRAEMOS LOS CODCLAVECIC BENEFICIARIOS
--TRUNCATE TABLE TMP_CONOCMCDO_SOL;
--INSERT INTO TMP_CONOCMCDO_SOL 
CREATE TABLE TMP_CONOCMCDO_SOL AS
WITH TMP_MOVAGENTE_SOL1 AS (
       SELECT A.CODCLAVEOPECTACARGO,
       A.CODUNICOCLI,
       A.CODCLAVEOPECTAABONO,
       A.FECDIA,
       A.HORTRANSACCION,
       A.CODMONEDA,
       A.MTOTRANSACCION,
       A.TIPTRANSACCIONAGENTEVIABCP,
       A.CODAGENTEVIABCP 
       FROM S61751.TMP_MOVAGENTE_I A --ODS_V.hd_MOVIMIENTOAGENTEVIABCP A
 WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
 AND A.TIPTRANSACCIONAGENTEVIABCP IN('03') AND A.TIPESTTRANSACCIONAGENTEVIABCP = 'P' 
 AND A.CODCLAVEOPECTACARGO IN (SELECT CODCLAVEOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
UNION ALL 
SELECT A.CODCLAVEOPECTACARGO,
       A.CODUNICOCLI,
       A.CODCLAVEOPECTAABONO,
       A.FECDIA,
       A.HORTRANSACCION,
       A.CODMONEDA,
       A.MTOTRANSACCION,
       A.TIPTRANSACCIONAGENTEVIABCP,
       A.CODAGENTEVIABCP 
       FROM S61751.TMP_MOVAGENTE_P A --ODS_V.hd_MOVIMIENTOAGENTEVIABCP A
 WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
 AND A.TIPTRANSACCIONAGENTEVIABCP IN('03') AND A.TIPESTTRANSACCIONAGENTEVIABCP = 'P' 
 AND A.CODCLAVEOPECTACARGO IN (SELECT CODCLAVEOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
),
TMP_MOVAGENTE_SOL2 AS (
       SELECT A.CODCLAVEOPECTACARGO,
       A.CODUNICOCLI,
       A.CODCLAVEOPECTAABONO,
       A.FECDIA,
       A.HORTRANSACCION,
       A.CODMONEDA,
       A.MTOTRANSACCION,
       A.TIPTRANSACCIONAGENTEVIABCP,
       A.CODAGENTEVIABCP FROM S61751.TMP_MOVAGENTE_I A -- ODS_V.hd_MOVIMIENTOAGENTEVIABCP A
 WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
 AND A.TIPTRANSACCIONAGENTEVIABCP IN('05') AND A.TIPESTTRANSACCIONAGENTEVIABCP = 'P' 
 AND A.CODUNICOCLI IN (SELECT CODUNICOCLI FROM TMP_CONOCMCDO_UNIVCLIE) UNION ALL SELECT A.CODCLAVEOPECTACARGO,
       A.CODUNICOCLI,
       A.CODCLAVEOPECTAABONO,
       A.FECDIA,
       A.HORTRANSACCION,
       A.CODMONEDA,
       A.MTOTRANSACCION,
       A.TIPTRANSACCIONAGENTEVIABCP,
       A.CODAGENTEVIABCP FROM S61751.TMP_MOVAGENTE_P A -- ODS_V.hd_MOVIMIENTOAGENTEVIABCP A
 WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
 AND A.TIPTRANSACCIONAGENTEVIABCP IN('05') AND A.TIPESTTRANSACCIONAGENTEVIABCP = 'P' 
 AND A.CODUNICOCLI IN (SELECT CODUNICOCLI FROM TMP_CONOCMCDO_UNIVCLIE)
)
       SELECT
              A.*,
              B.CODCLAVECIC CODCLAVECIC_SOL
       FROM
              TMP_MOVAGENTE_SOL1         A
              LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
              ON A.CODCLAVEOPECTACARGO=B.CODCLAVEOPECTA UNION
              SELECT
                     A.*,
                     B.CODCLAVECIC CODCLAVECIC_SOL
              FROM
                     TMP_MOVAGENTE_SOL2         A
                     LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
                     ON A.CODUNICOCLI=B.CODUNICOCLI;

--TRUNCATE TABLE TMP_CONOCMCDO_TRX_AGENTE_2;
--INSERT INTO TMP_CONOCMCDO_TRX_AGENTE_2 
CREATE TABLE TMP_CONOCMCDO_TRX_AGENTE_2 AS
WITH TMP_MOVAGENTE_BEN AS (
       SELECT A.*,
       B.CODCLAVECIC AS CODCLAVECIC_BEN FROM TMP_CONOCMCDO_SOL A 
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODCLAVEOPECTAABONO=B.CODCLAVEOPECTA
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODCLAVECIC_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESTIPTRANSACCIONAGENTEVIABCP        AS TIPO_TRANSACCION,
              'AGENTE'                               AS CANAL,
              ' '                                    CODPAISORIGEN
       FROM
              TMP_MOVAGENTE_BEN                A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC
              ON A.FECDIA = TC.FECTIPCAMBIO
              AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESTIPOTRANAGENTEVIABCP D
              ON A.TIPTRANSACCIONAGENTEVIABCP = D.TIPTRANSACCIONAGENTEVIABCP
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--*******************************************************************HOME BANKING*******************************************************************
--TRUNCATE TABLE TMP_CONOCMCDO_HM_SOL;
--INSERT INTO TMP_CONOCMCDO_HM_SOL 
CREATE TABLE TMP_CONOCMCDO_HM_SOL AS
WITH TMP_MOVHM AS (
       SELECT CODOPECTAORIGEN,
       CODOPECTADESTINO,
       FECDIA,
       HORTRANSACCION,
       CODMONEDA,
       MTOTRANSACCION,
       CODOPEHBCTR FROM ODS_V.HD_MOVHOMEBANKINGTRANSACCION
       WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)))
       AND TIPRESULTADOTRANSACCION = 'OK' AND CODTIPOPERACIONHB='701' AND CODOPECTAORIGEN IN(SELECT CODOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
)
       SELECT
              A.*,
              B.CODCLAVECIC AS CODCLAVECIC_SOL
       FROM
              TMP_MOVHM                  A
              LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
              ON A.CODOPECTAORIGEN=B.CODOPECTA;

--TRUNCATE TABLE TMP_CONOCMCDO_TRX_HM_2;
--INSERT INTO TMP_CONOCMCDO_TRX_HM_2 
CREATE TABLE TMP_CONOCMCDO_TRX_HM_2 AS
WITH TMP_MOVHM_BEN AS (
       SELECT A.*,
       COALESCE(C.CODCLAVECIC, B.CODCLAVECIC) AS CODCLAVECIC_BEN
       FROM TMP_CONOCMCDO_HM_SOL A
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODOPECTADESTINO=B.CODOPECTA LEFT JOIN ODS_V.MD_CUENTAG94 C ON A.CODOPECTADESTINO=C.CODOPECTA
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODCLAVECIC_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESCODOPEHBCTR                       AS TIPO_TRANSACCION,
              'HOMEBANKING'                          AS CANAL,
              ' '                                    CODPAISORIGEN
       FROM
              TMP_MOVHM_BEN                  A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC
              ON A.FECDIA = TC.FECTIPCAMBIO
              AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESCODIGOOPEHBCTR D
              ON A.CODOPEHBCTR = D.CODOPEHBCTR
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************CAJERO***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA
--TRUNCATE TABLE TMP_CONOCMCDO_CAJERO_SOL_2;
--INSERT INTO TMP_CONOCMCDO_CAJERO_SOL_2 
CREATE TABLE TMP_CONOCMCDO_CAJERO_SOL_2 AS
WITH TMP_MOVCAJERO_SOL1 AS (
       SELECT CODOPECTADESDE,
       CODCLAVECIC,
       CODOPECTAHACIA,
       FECDIA,
       HORTRANSACCION,
       CASE WHEN MTOTRANSACCIONSOL IS NULL OR MTOTRANSACCIONME IS NULL THEN COALESCE(CODMONEDACTADESDE, CODMONEDACTAHACIA) ELSE CODMONEDATRAN END CODMONEDA,
       COALESCE( CASE WHEN CODMONEDATRAN = '0001' THEN MTOTRANSACCIONSOL ELSE MTOTRANSACCIONME END, MTOTRANSACCIONORIGEN ) MTOTRANSACCION,
       CODTRANCAJERO,
       MTOTRANSACCIONSOL,
       MTOTRANSACCIONME,
       CODCAJERO 
       FROM ODS_V.HD_MOVIMIENTOCAJERO 
       WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM')  AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
       AND CODTRANCAJERO IN ('40') AND FLGVALIDA='S' AND CODOPECTADESDE IN (SELECT CODOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
),
TMP_MOVCAJERO_SOL2 AS (
       SELECT CODOPECTADESDE,
       CODCLAVECIC,
       CODOPECTAHACIA,
       FECDIA,
       HORTRANSACCION,
       CASE WHEN MTOTRANSACCIONSOL IS NULL OR MTOTRANSACCIONME IS NULL THEN COALESCE(CODMONEDACTADESDE, CODMONEDACTAHACIA) ELSE CODMONEDATRAN END CODMONEDA,
       COALESCE( CASE WHEN CODMONEDATRAN = '0001' THEN MTOTRANSACCIONSOL ELSE MTOTRANSACCIONME END, MTOTRANSACCIONORIGEN ) MTOTRANSACCION,
       CODTRANCAJERO,
       MTOTRANSACCIONSOL,
       MTOTRANSACCIONME,
       CODCAJERO 
       FROM ODS_V.HD_MOVIMIENTOCAJERO 
       WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
       AND CODTRANCAJERO IN ('20') AND FLGVALIDA='S' AND CODCLAVECIC IN (SELECT CODCLAVECIC FROM TMP_CONOCMCDO_UNIVCLIE)
)
       SELECT
              A.*,
              B.CODCLAVECIC          AS CODCLAVECIC_SOL
       FROM
              TMP_MOVCAJERO_SOL1         A
              LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B
              ON A.CODOPECTADESDE=B.CODOPECTA UNION
              SELECT
                     A.*,
                     A.CODCLAVECIC          AS CODCLAVECIC_SOL
              FROM TMP_MOVCAJERO_SOL2 A;

--TRUNCATE TABLE TMP_CONOCMCDO_TRX_CAJERO_2;
--INSERT INTO TMP_CONOCMCDO_TRX_CAJERO_2 
CREATE TABLE --INSERT INTO TMP_CONOCMCDO_TRX_CAJERO_2 AS
WITH TMP_CAJERO_BEN AS (
       SELECT A.*,
       B.CODCLAVECIC AS CODCLAVECIC_BEN 
       FROM TMP_CONOCMCDO_CAJERO_SOL_2 A 
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODOPECTAHACIA=B.CODOPECTA
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODCLAVECIC_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              (CASE
                     WHEN A.CODMONEDA = '0001' THEN
                            COALESCE(A.MTOTRANSACCIONSOL, A.MTOTRANSACCION)
                     ELSE
                            COALESCE(A.MTOTRANSACCIONME, A.MTOTRANSACCION)
              END) * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESCODTRANCAJERO         AS TIPO_TRANSACCION,
              'CAJERO'                   AS CANAL,
              ' '                        CODPAISORIGEN
       FROM
              TMP_CAJERO_BEN                      A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON A.FECDIA = TC.FECTIPCAMBIO AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MM_DESCODIGOTRANSACCIONCAJERO D ON A.CODTRANCAJERO = D.CODTRANCAJERO
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN
              AND A.CODMONEDA IS NOT NULL;

--***************************************************TELECREDITO***************************************************
--TRUNCATE TABLE TMP_CONOCMCDO_TELCRE_SOL;
--INSERT INTO TMP_CONOCMCDO_TELCRE_SOL 
CREATE TABLE TMP_CONOCMCDO_TELCRE_SOL AS
WITH TMP_MOVTELCRE_SOL AS (
       SELECT CODOPECTA,
       CODOPECTAABONO,
       FECTRANSFERENCIA AS FECDIA,
       HORTRANSFERENCIA AS HORTRANSACCION,
       CODMONEDA,
       MTOTRANSFERENCIA AS MTOTRANSACCION,
       TIPOPERACIONTELCRE 
       FROM ODS_V.HS_MOVIMIENTOTRANSFERENCTELCRE 
       WHERE FECTRANSFERENCIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
       AND TIPESTTRANSFERENCIATELCRE=40 AND TIPOPERACIONTELCRE IN ('OMTRMT', 'OMTRTH', 'OMTRTN') AND CODOPECTA IN (SELECT CODOPECTA FROM TMP_CONOCMCDO_UNIVCTASCLIE)
)
       SELECT
              A.*,
              B.CODCLAVECIC    AS CODCLAVECIC_SOL
       FROM TMP_MOVTELCRE_SOL          A
       LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B ON A.CODOPECTA=B.CODOPECTA;

--TRUNCATE TABLE TMP_CONOCMCDO_TRX_TELCRE_2;
--INSERT INTO TMP_CONOCMCDO_TRX_TELCRE_2 
CREATE TABLE TMP_CONOCMCDO_TRX_TELCRE_2 AS
WITH TMP_BEN AS (
       SELECT A.*,
       COALESCE(C.CODCLAVECIC, B.CODCLAVECIC) AS CODCLAVECIC_BEN 
       FROM TMP_CONOCMCDO_TELCRE_SOL A 
       LEFT JOIN ODS_V.MD_CUENTA B ON A.CODOPECTAABONO=B.CODOPECTA 
       LEFT JOIN ODS_V.MD_CUENTAG94 C ON A.CODOPECTAABONO=C.CODOPECTA
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODCLAVECIC_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESTIPOPERACIONTELCRE                AS TIPO_TRANSACCION,
              'TELECREDITO'                          AS CANAL,
              ' '                                    CODPAISORIGEN
       FROM
              TMP_BEN                        A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC
              ON A.FECDIA = TC.FECTIPCAMBIO
              AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MS_TIPOOPERACIONTELCRE D
              ON A.TIPOPERACIONTELCRE = D.TIPOPERACIONTELCRE
       WHERE
              A.CODCLAVECIC_BEN<>0
              AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************GGTT***************************************************
--TRUNCATE TABLE TMP_CONOCMCDO_GGTT_SOL;
--INSERT INTO TMP_CONOCMCDO_GGTT_SOL 
CREATE TABLE TMP_CONOCMCDO_GGTT_SOL AS
WITH TMP_MOVGGTT_SOL AS (
       SELECT CODCLAVECICSOLICITANTE,
       CODCLAVECICBENEFICIARIO,
       FECDIA,
       HOREMISION,
       CODMONEDA,
       MTOIMPORTEOPERACION,
       CODPRODUCTO,
       CODSWIFTBCODESTINO,
       CODSWIFTBCOEMISOR 
       FROM ODS_V.HD_DOCUMENTOEMITIDOGGTT 
       WHERE FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1), 'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) 
       AND CODTIPESTADOTRANSACCION = '00' AND CODCLAVECICSOLICITANTE IN (SELECT CODCLAVECIC FROM TMP_CONOCMCDO_UNIVCLIE)
)
       SELECT
              A.*,
              A.CODCLAVECICSOLICITANTE AS CODCLAVECIC_SOL
       FROM
              TMP_MOVGGTT_SOL A;

--TRUNCATE TABLE TMP_CONOCMCDO_TRX_GGTT_2;
--INSERT INTO TMP_CONOCMCDO_TRX_GGTT_2 
CREATE TABLE TMP_CONOCMCDO_TRX_GGTT_2 AS
WITH TMP_GGTT_BEN AS (
       SELECT A.*,
       A.CODCLAVECICBENEFICIARIO AS CODCLAVECIC_BEN FROM TMP_CONOCMCDO_GGTT_SOL A
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODCLAVECIC_BEN,
              A.FECDIA,
              A.HOREMISION                                AS HORTRANSACCION,
              A.CODMONEDA,
              A.MTOIMPORTEOPERACION                       AS MTOTRANSACCION,
              A.MTOIMPORTEOPERACION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESCODPRODUCTO                            AS TIPO_TRANSACCION,
              'DOCUMENTO_GGTT'                            AS CANAL,
              UPPER(P.NOMBREPAIS)                         AS CODPAISORIGEN
       FROM
              TMP_GGTT_BEN                   A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC
              ON A.FECDIA = TC.FECTIPCAMBIO
              AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D
              ON A.CODPRODUCTO = D.CODPRODUCTO
              LEFT JOIN S55632.MD_CODIGOPAIS P
              ON SUBSTR(A.CODSWIFTBCOEMISOR,5,2) = P.CODPAIS2
       WHERE A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

--***************************************************BANNI***************************************************
--TRUNCATE TABLE TMP_CONOCMCDO_BANNI_SOL;
--INSERT INTO TMP_CONOCMCDO_BANNI_SOL
CREATE TABLE TMP_CONOCMCDO_BANNI_SOL AS
       SELECT
              A.HORTRANSACCION,
              B.FECDIA,
              B.CODMONEDA,
              B.MTOOPERACION,
              B.MTOOPERACIONDOL AS MTO_DOLARIZADO,
              CL.CODCLAVECIC    AS CODCLAVECIC_SOL,
              B.CODPAISBENEFICIARIO,
              B.CODPRODUCTO
       FROM
              ODS_V.HD_MOVIMIENTOBANNI   A
              LEFT JOIN ODS_V.MD_OPERACIONBAN B
              ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA
              INNER JOIN TMP_CONOCMCDO_UNIVCLIE CL
              ON CL.CODCLAVECIC=B.CODCLAVECIC
              LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE CGRE
              ON A.CODCLAVEOPECTAAFECTADA = CGRE.CODCLAVEOPECTA
       WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
       AND A.CODPRODUCTO = 'TRAEXT'
       AND B.FLGREGELIMINADO='N';

--TRUNCATE TABLE TMP_CONOCMCDO_TRX_BANNI_2;
--INSERT INTO TMP_CONOCMCDO_TRX_BANNI_2
CREATE TABLE TMP_CONOCMCDO_TRX_BANNI_2 AS
WITH TMP_BEN_BANNI AS (
       SELECT A.*,
       -1 AS CODCLAVECIC_BEN FROM TMP_CONOCMCDO_BANNI_SOL A
)
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODCLAVECIC_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOOPERACION      AS MTOTRANSACCION,
              A.MTO_DOLARIZADO,
              D.DESCODPRODUCTO    AS TIPO_TRANSACCION,
              'BANNI'             AS CANAL,
              UPPER(P.NOMBREPAIS) AS CODPAISORIGEN
       FROM
              TMP_BEN_BANNI              A
              LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D
              ON A.CODPRODUCTO = D.CODPRODUCTO
              LEFT JOIN S55632.MD_CODIGOPAIS P
              ON TRIM(A.CODPAISBENEFICIARIO) = P.CODPAIS3;

--***************************************************VENTANILLA***********************************************************
--ACORTAMOS EL PERIODO DE LA TABLA
--TRUNCATE TABLE TMP_CONOCMCDO_MOVVENTANILLA_SOL1;
--INSERT INTO TMP_CONOCMCDO_MOVVENTANILLA_SOL1
CREATE TABLE TMP_CONOCMCDO_MOVVENTANILLA_SOL1 AS
       SELECT
              A.CODCLAVEOPECTA,
              A.CODCLAVEOPECTADESTINO,
              A.FECDIA,
              A.HORINITRANSACCION    AS HORTRANSACCION,
              A.CODMONEDATRANSACCION AS CODMONEDA,
              A.CODSUCAGE,
              A.CODSESION,
              CASE
                     WHEN A.MTOTRANSACCIONCTA <> 0 THEN
                            A.MTOTRANSACCIONCTA
                     ELSE A.MTOTRANSACCION
              END                    AS MTOTRANSACCION,
              A.CODTRANSACCIONVENTANILLA,
              COALESCE(CASE
                     WHEN B.CODUNICOCLISOLICITANTE='.' THEN
                            ''
                     ELSE B.CODUNICOCLISOLICITANTE
              END,
              CASE
                     WHEN B.CODUNICOCLIORDENANTE='.' THEN
                            ''
                     ELSE B.CODUNICOCLIORDENANTE
              END)                   AS CODUNICOCLI_SOL
       FROM
              ODS_V.HD_TRANSACCIONVENTANILLA     A
              INNER JOIN ODS_V.HD_MOVLAVADODINEROVENTANILLA B
              ON A.FECDIA = B.FECDIA
              AND A.CODSUCAGE = B.CODSUCAGE
              AND A.CODSESION = B.CODSESION
       WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
       AND A.CODTRANSACCIONVENTANILLA IN (60,62,63)
       AND A.FLGTRANSACCIONAPROBADA = 'S';

--TRUNCATE TABLE TMP_CONOCMCDO_MOVVENTANILLA_SOL2;
--INSERT INTO TMP_CONOCMCDO_MOVVENTANILLA_SOL2
CREATE TABLE TMP_CONOCMCDO_MOVVENTANILLA_SOL2 AS
       SELECT
              A.CODCLAVEOPECTA,
              A.CODCLAVEOPECTADESTINO,
              A.FECDIA,
              A.HORINITRANSACCION    AS HORTRANSACCION,
              A.CODMONEDATRANSACCION AS CODMONEDA,
              A.CODSUCAGE,
              A.CODSESION,
              CASE
                     WHEN A.MTOTRANSACCIONCTA <> 0 THEN
                            A.MTOTRANSACCIONCTA
                     ELSE A.MTOTRANSACCION
              END                    AS MTOTRANSACCION,
              A.CODTRANSACCIONVENTANILLA
       FROM
              ODS_V.HD_TRANSACCIONVENTANILLA A
       WHERE
              FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
              AND A.CODTRANSACCIONVENTANILLA IN (159,186, 187, 188)
              AND A.FLGTRANSACCIONAPROBADA = 'S'
              AND A.CODCLAVEOPECTA IN (
                     SELECT CODCLAVEOPECTA
                     FROM TMP_CONOCMCDO_UNIVCTASCLIE
              );

--ACORTAMOS EL PERIODO DE LA TABLA
--TRUNCATE TABLE TMP_CONOCMCDO_VENT_SOL;
--INSERT INTO TMP_CONOCMCDO_VENT_SOL
CREATE TABLE TMP_CONOCMCDO_VENT_SOL AS
       SELECT
              DISTINCT A.CODCLAVEOPECTA,
              A.CODCLAVEOPECTADESTINO,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.CODSUCAGE,
              A.CODSESION,
              A.MTOTRANSACCION,
              A.CODTRANSACCIONVENTANILLA,
              B.CODCLAVECIC AS CODCLAVECIC_SOL
       FROM TMP_CONOCMCDO_MOVVENTANILLA_SOL1 A
       LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B ON A.CODUNICOCLI_SOL=B.CODUNICOCLI 
       UNION
       SELECT
              DISTINCT A.*,
              B.CODCLAVECIC AS CODCLAVECIC_SOL
       FROM TMP_CONOCMCDO_MOVVENTANILLA_SOL2 A
       LEFT JOIN TMP_CONOCMCDO_UNIVCTASCLIE B ON A.CODCLAVEOPECTA=B.CODCLAVEOPECTA;

--TRUNCATE TABLE TMP_CONOCMCDO_VENT_BEN_2;
--INSERT INTO TMP_CONOCMCDO_VENT_BEN_2
CREATE TABLE TMP_CONOCMCDO_VENT_BEN_2 AS
       SELECT
              A.*,
              COALESCE(C.CODCLAVECIC,B.CODCLAVECIC) AS CODCLAVECIC_BEN
       FROM
              TMP_CONOCMCDO_VENT_SOL A
              LEFT JOIN ODS_V.MD_CUENTA B ON A.CODCLAVEOPECTADESTINO=B.CODCLAVEOPECTA
              LEFT JOIN ODS_V.MD_CUENTAG94 C ON A.CODCLAVEOPECTADESTINO=C.CODCLAVEOPECTA;

--TRUNCATE TABLE TMP_CONOCMCDO_TRX_VENTANILLA_2;
--INSERT INTO TMP_CONOCMCDO_TRX_VENTANILLA_2
CREATE TABLE TMP_CONOCMCDO_TRX_VENTANILLA_2 AS
       SELECT
              DISTINCT A.CODCLAVECIC_SOL,
              A.CODCLAVECIC_BEN,
              A.FECDIA,
              A.HORTRANSACCION,
              A.CODMONEDA,
              A.MTOTRANSACCION,
              A.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTO_DOLARIZADO,
              D.DESTRANSACCIONVENTANILLA             AS TIPO_TRANSACCION,
              'VENTANILLA'                           AS CANAL,
              ' '                                    CODPAISORIGEN,
              CASE
                     WHEN CODSUCAGE IN('220000', '220002', '405000', '405003', '405004', 
                     '405005', '495000', '540000', '540002', '540004', '540005', '565000', 
                     '575000', '575001') THEN '1'
                     ELSE '0'
              END                                    FLG_ZAR
       FROM
              TMP_CONOCMCDO_VENT_BEN_2          A
              LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON A.FECDIA = TC.FECTIPCAMBIO AND A.CODMONEDA = TC.CODMONEDA
              LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA D ON A.CODTRANSACCIONVENTANILLA = D.CODTRANSACCIONVENTANILLA
       WHERE A.CODCLAVECIC_BEN<>0
       AND A.CODCLAVECIC_SOL<>A.CODCLAVECIC_BEN;

QUIT;