--PARAMETRO DE CREDENCIALES
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

-- ============================ TABLA DE ALERTAS ============================

TRUNCATE TABLE TMP_CONOCMCDO_ALERTAS;
INSERT INTO TMP_CONOCMCDO_ALERTAS
--CREATE TABLE TMP_CONOCMCDO_ALERTAS TABLESPACE D_AML_99 AS
SELECT
    DISTINCT COALESCE (B.APEPATCLI,C.APEPATCLI )   AS APEPATCLI,
    COALESCE (B.APEMATCLI,C.APEMATCLI )   AS APEMATCLI,
    COALESCE (B.NBRCLI,C.NBRCLI )      AS NBRCLI,
    COALESCE (B.CODUNICOCLI,C.CODUNICOCLI ) AS CODUNICOCLI,
    A.*
FROM TMP_CONOCMCDO_OUTPUTMODEL A
LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODCLAVECIC=B.CODCLAVECIC
LEFT JOIN ODS_V.MD_CLIENTEG94 C ON A.CODCLAVECIC=C.CODCLAVECIC
WHERE OUTLIER=-1;


TRUNCATE TABLE TMP_CONOCMCDO_CIC_ALERTAS;
INSERT INTO TMP_CONOCMCDO_CIC_ALERTAS
--CREATE TABLE TMP_CONOCMCDO_CIC_ALERTAS TABLESPACE D_AML_99 AS
SELECT DISTINCT CODCLAVECIC
FROM TMP_CONOCMCDO_ALERTAS;

-- ============================ EECC ============================

TRUNCATE TABLE TMP_CONOCMCDO_CIC_ALERTAS_INI;
INSERT INTO TMP_CONOCMCDO_CIC_ALERTAS_INI
--CREATE TABLE TMP_CONOCMCDO_CIC_ALERTAS_INI TABLESPACE D_AML_99 AS
SELECT A.CODCLAVECIC,
    CODUNICOCLI,
    TIPPER,
    CASE
        WHEN TIPPER = 'E' THEN
                TRIM(APEPATCLI) || TRIM(APEMATCLI) || TRIM(NBRCLI)
            WHEN TIPPER = 'P' THEN
                TRIM(APEPATCLI) || ' ' || TRIM(APEMATCLI) || ' ' || TRIM(NBRCLI)
        END AS NOMBRE
FROM ODS_V.MD_CLIENTE A
INNER JOIN TMP_CONOCMCDO_CIC_ALERTAS B ON A.CODCLAVECIC = B.CODCLAVECIC
AND A.CODCLAVECIC NOT IN ( SELECT CODCLAVECIC FROM ODS_V.MD_EMPLEADOG94 ) 
UNION
SELECT A.CODCLAVECIC,
    CODUNICOCLI,
    'P',
    TRIM(APEPATEMPLEADO) || ' ' || TRIM(APEMATEMPLEADO) || ' ' || TRIM(NBREMPLEADO)
FROM ODS_V.MD_EMPLEADOG94      A
INNER JOIN TMP_CONOCMCDO_CIC_ALERTAS B ON A.CODCLAVECIC = B.CODCLAVECIC;

--CREATE INDEX IDX_CONOCMCDO_EECC_CODCLAVECIC ON TMP_CONOCMCDO_CIC_ALERTAS_INI (CODCLAVECIC) TABLESPACE D_AML_99;

TRUNCATE TABLE TMP_CONOCMCDO_CTAS_ALERT;
INSERT INTO TMP_CONOCMCDO_CTAS_ALERT
--CREATE TABLE TMP_CONOCMCDO_CTAS_ALERT TABLESPACE D_AML_99 AS
SELECT
    CTA.CODCLAVECIC,
    B.CODUNICOCLI,
    B.NOMBRE,
    CTA.CODCLAVEOPECTA,
    CODSISTEMAORIGEN,
    CODOPECTA,
    CASE
        WHEN CTA.CODSISTEMAORIGEN = 'SAV' THEN
            SUBSTR(CODOPECTA, 1, 3)
                || '-'
                || TRIM(TO_CHAR(MOD(TO_NUMBER(SUBSTR(CODOPECTA, 5, 16)), 100000000), '00000009'))
                || '-'
                || SUBSTR(CODMONEDA, 1, 1)
                || '-'
                || TRIM(TO_CHAR(
                CASE
                    WHEN SUBSTR(CODOPECTA, 1, 3) IN ('191', '192', '193', '194') THEN
                        MOD(TO_NUMBER(SUBSTR(CODOPECTA, 13, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 15, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 17, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 19, 2)), 100)
                    ELSE
                        MOD(-20 + TO_NUMBER(SUBSTR(CODOPECTA, 1, 1)) + TO_NUMBER(SUBSTR(CODOPECTA, 2, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 13, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 15, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 17, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 19, 2)), 100)
                END, '09')) WHEN CTA.CODSISTEMAORIGEN = 'IMP' THEN SUBSTR(CODOPECTA,1,3) || '-' || TRIM(TO_CHAR(MOD(TO_NUMBER(SUBSTR(CODOPECTA,5,16)),10000000),'0000009')) || '-' || SUBSTR(CODMONEDA,1,1) || '-' || TRIM(TO_CHAR( CASE
        WHEN SUBSTR(CODOPECTA, 1, 3) IN ('191', '192', '193', '194') AND CODMONEDA='0001' THEN
            MOD(TO_NUMBER(SUBSTR(CODOPECTA, 14, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 16, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 18, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 20, 1))*10, 100)
        WHEN SUBSTR(CODOPECTA, 1, 3) IN ('191', '192', '193', '194') AND CODMONEDA='1001' THEN
            MOD(TO_NUMBER(SUBSTR(CODOPECTA, 14, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 16, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 18, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 20, 1))*10+10, 100)
        WHEN SUBSTR(CODOPECTA, 1, 3) NOT IN ('191', '192', '193', '194') AND CODMONEDA='0001' THEN
            MOD(TO_NUMBER(SUBSTR(CODOPECTA, 1, 1)) + TO_NUMBER(SUBSTR(CODOPECTA, 2, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 14, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 16, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 18, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 20, 1))*10, 100)
        WHEN SUBSTR(CODOPECTA, 1, 3) NOT IN ('191', '192', '193', '194') AND CODMONEDA='1001' THEN
            MOD(10 + TO_NUMBER(SUBSTR(CODOPECTA, 1, 1)) + TO_NUMBER(SUBSTR(CODOPECTA, 2, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 14, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 16, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 18, 2)) + TO_NUMBER(SUBSTR(CODOPECTA, 20, 1))*10, 100)
    END,
        '09')) END AS CUENTACOMERCIAL
FROM ODS_V.MD_CUENTAG94 CTA
INNER JOIN TMP_CONOCMCDO_CIC_ALERTAS_INI B ON CTA.CODCLAVECIC = B.CODCLAVECIC
WHERE CTA.CODSISTEMAORIGEN IN ('SAV', 'IMP');

--CREATE INDEX IDX_CONOCMCDO_EECC_CTAS ON TMP_CONOCMCDO_CTAS_ALERT (CODCLAVEOPECTA) TABLESPACE D_AML_99;

TRUNCATE TABLE TMP_CONOCMCDO_SAV_ALERTAS;
INSERT INTO TMP_CONOCMCDO_SAV_ALERTAS
--CREATE TABLE TMP_CONOCMCDO_SAV_ALERTAS TABLESPACE D_AML_99 AS
SELECT
    B.CODCLAVECIC,
    B.CODUNICOCLI,
    B.NOMBRE,
    A.CODCLAVEOPECTA,
    B.CODOPECTA,
    B.CUENTACOMERCIAL,
    A.FECDIA,
    A.HORTRANSACCION,
    A.DESOPETRANSACCIONSAVINGDETALLE,
    F.GRUPO,
    C.DESCANAL,
    D.NBRSUCAGE,
    A.CODMONEDA,
    A.MTOTRANSACCION,
    A.TIPCARGOABONO,
    ROUND(A.MTOTRANSACCION * E.MTOCAMBIOALDOLAR, 2) AS MTODOLARIZADO
FROM ODS_V.HD_MOVIMIENTOSAVING      A
INNER JOIN TMP_CONOCMCDO_CTAS_ALERT B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA AND B.CODSISTEMAORIGEN = 'SAV'
LEFT JOIN ODS_V.MD_DESCODIGOCANAL C ON A.CODCANAL = C.CODCANAL
LEFT JOIN ODS_V.MD_AGENCIA D ON A.CODSUCAGE = D.CODSUCAGE
LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO E ON A.FECDIA = E.FECTIPCAMBIO AND A.CODMONEDA = E.CODMONEDA
LEFT JOIN S55632.TMP_EQUIVAL_TIPOPE_EECC F ON TRIM(A.DESOPETRANSACCIONSAVINGDETALLE) LIKE (TRIM(F.GLOSA)|| '%')
WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

TRUNCATE TABLE TMP_CONOCMCDO_IMP_ALERTAS_X;
INSERT INTO TMP_CONOCMCDO_IMP_ALERTAS_X
--CREATE TABLE TMP_CONOCMCDO_IMP_ALERTAS_X TABLESPACE D_AML_99 AS
WITH IMPS AS (
    SELECT CODCLAVEOPECTA,
    CODCLAVECIC,
    CODUNICOCLI,
    NOMBRE,
    CODOPECTA,
    CUENTACOMERCIAL FROM TMP_CONOCMCDO_CTAS_ALERT WHERE CODSISTEMAORIGEN = 'IMP'
)
SELECT
    B.CODCLAVECIC,
    B.CODUNICOCLI,
    B.NOMBRE,
    A.CODCLAVEOPECTA,
    B.CODOPECTA,
    B.CUENTACOMERCIAL,
    A.FECDIA,
    A.HORTRANSACCION,
    TRIM(A.DESOPETRANSACCIONIMPACDETALLE) AS DESOPETRANSACCIONIMPACDETALLE,
    A.CODMONEDA,
    A.MTOTRANSACCION,
    A.TIPCARGOABONO,
    A.CODCANAL,
    A.CODSUCAGE
FROM ODS_V.HD_MOVIMIENTOIMPAC A
INNER JOIN IMPS B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA
WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

TRUNCATE TABLE TMP_CONOCMCDO_IMP_ALERTAS;
INSERT INTO TMP_CONOCMCDO_IMP_ALERTAS
--CREATE TABLE TMP_CONOCMCDO_IMP_ALERTAS TABLESPACE D_AML_99 AS
SELECT
    X.CODCLAVECIC,
    X.CODUNICOCLI,
    X.NOMBRE,
    X.CODCLAVEOPECTA,
    X.CODOPECTA,
    X.CUENTACOMERCIAL,
    X.FECDIA,
    X.HORTRANSACCION,
    X.DESOPETRANSACCIONIMPACDETALLE,
    F.GRUPO,
    C.DESCANAL,
    D.NBRSUCAGE,
    X.CODMONEDA,
    X.MTOTRANSACCION,
    X.TIPCARGOABONO,
    ROUND(X.MTOTRANSACCION * E.MTOCAMBIOALDOLAR,2) AS MTODOLARIZADO
FROM TMP_CONOCMCDO_IMP_ALERTAS_X    X
LEFT JOIN ODS_V.MD_DESCODIGOCANAL C ON X.CODCANAL = C.CODCANAL
LEFT JOIN ODS_V.MD_AGENCIA D ON X.CODSUCAGE = D.CODSUCAGE
LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO E ON X.FECDIA = E.FECTIPCAMBIO AND X.CODMONEDA = E.CODMONEDA
LEFT JOIN S55632.TMP_EQUIVAL_TIPOPE_EECC F ON X.DESOPETRANSACCIONIMPACDETALLE LIKE (TRIM(F.GLOSA)|| '%');

TRUNCATE TABLE TMP_CONOCMCDO_EECC_ALERTAS;
INSERT INTO TMP_CONOCMCDO_EECC_ALERTAS
--CREATE TABLE TMP_CONOCMCDO_EECC_ALERTAS TABLESPACE D_AML_99 AS
SELECT *
FROM TMP_CONOCMCDO_SAV_ALERTAS A
UNION ALL
SELECT *
FROM TMP_CONOCMCDO_IMP_ALERTAS;

-- ============================ TRANSACCIONES ============================

TRUNCATE TABLE TMP_CONOCMCDO_TRX_INGRESOCLIE;
INSERT INTO TMP_CONOCMCDO_TRX_INGRESOCLIE
--CREATE TABLE TMP_CONOCMCDO_TRX_INGRESOCLIE TABLESPACE D_AML_99 AS
WITH TMP AS (
    SELECT DISTINCT COALESCE (B.APEPATCLI, C.APEPATCLI ) AS APEPATCLI_BEN,
    COALESCE (B.APEMATCLI, C.APEMATCLI ) AS APEMATCLI_BEN,
    COALESCE (B.NBRCLI, C.NBRCLI ) AS NBRCLI_BEN,
    COALESCE (B.CODUNICOCLI, C.CODUNICOCLI ) AS CODUNICOCLI_BEN,
    A.*
    FROM TMP_CONOCMCDO_UNIVTRX A
    LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODCLAVECIC_BEN=B.CODCLAVECIC
    LEFT JOIN ODS_V.MD_CLIENTEG94 C ON A.CODCLAVECIC_BEN=C.CODCLAVECIC
    WHERE A.CODCLAVECIC_BEN IN (SELECT * FROM TMP_CONOCMCDO_CIC_ALERTAS)
)
SELECT
    DISTINCT COALESCE (B.CODUNICOCLI, C.CODUNICOCLI ) AS CODUNICOCLI_SOL,
    COALESCE (B.APEPATCLI, C.APEPATCLI )   AS APEPATCLI_SOL,
    COALESCE (B.APEMATCLI, C.APEMATCLI )   AS APEMATCLI_SOL,
    COALESCE (B.NBRCLI, C.NBRCLI )      AS NBRCLI_SOL,
    A.CODCLAVECIC_SOL,
    A.CODOPECTA_SOL,
    A.CODUNICOCLI_BEN,
    A.APEPATCLI_BEN,
    A.APEMATCLI_BEN,
    A.NBRCLI_BEN,
    A.CODCLAVECIC_BEN,
    A.CODOPECTA_BEN,
    A.FECDIA,
    A.HORTRANSACCION,
    A.CODMONEDA,
    A.MTOTRANSACCION,
    A.MTO_DOLARIZADO,
    A.TIPO_TRANSACCION,
    A.CANAL,
    A.CODPAISORIGEN
FROM TMP A
LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODCLAVECIC_SOL=B.CODCLAVECIC
LEFT JOIN ODS_V.MD_CLIENTEG94 C ON A.CODCLAVECIC_BEN=C.CODCLAVECIC;

QUIT;