SET TERM OFF;
--PARAMETRO DE CREDENCIALES
@&1

COL LOGNAME NEW_VALUE LOGNAME
SELECT '.\logs\04_deploy\ ' || TO_CHAR(SYSDATE, 'YYYYMMDD_HHMMSS') || '_packages.log' LOGNAME FROM DUAL;
SPOOL '&LOGNAME'
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH:MM:SS') AS "FECHA Y HORA DE CORRIDA:" FROM DUAL;
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

SET ECHO OFF;
SET FEEDBACK OFF;
SET HEAD OFF;
SET LIN 256;
SET TRIMSPOOL ON;
SET WRAP OFF;
SET PAGES 0;
SET TERM OFF;
SET SERVEROUTPUT ON;

ALTER session disable parallel query;
alter session set NLS_NUMERIC_CHARACTERS='.,';

--EPIC016 - Paquetes de transacciones del cliente

SPOOL ./src/04_deploy/packages/packages_loop.sql;

PROMPT VAR CODCLAVECIC NUMBER;

BEGIN
  FOR TARGET_POINTER IN (SELECT DISTINCT CODCLAVECIC, CODUNICOCLI FROM TMP_CONOCMCDO_ALERTAS )
  LOOP
	  DBMS_OUTPUT.PUT_LINE('DEFINE CODUNICOCLI = '''||TARGET_POINTER.CODUNICOCLI||''';');
    DBMS_OUTPUT.PUT_LINE('EXEC :CODCLAVECIC := '''||TARGET_POINTER.CODCLAVECIC||''';');
    DBMS_OUTPUT.PUT_LINE('@@./src/04_deploy/packages/packages_trx.sql;');
  END LOOP;
END;
/

SPOOL OFF;

@@./src/04_deploy/packages/packages_loop.sql;

--EPIC016 - Paquetes de EECC del cliente

SPOOL ./src/04_deploy/packages/packages_loop.sql;

PROMPT VAR CODCLAVECIC NUMBER;

BEGIN
  FOR TARGET_POINTER IN (SELECT DISTINCT CODCLAVECIC, CODUNICOCLI FROM TMP_CONOCMCDO_ALERTAS )
  LOOP
	  DBMS_OUTPUT.PUT_LINE('DEFINE CODUNICOCLI = '''||TARGET_POINTER.CODUNICOCLI||''';');
    DBMS_OUTPUT.PUT_LINE('EXEC :CODCLAVECIC := '''||TARGET_POINTER.CODCLAVECIC||'''; ');
    DBMS_OUTPUT.PUT_LINE('@@./src/04_deploy/packages/packages_eecc.sql;');
  END LOOP;
END;
/

SPOOL OFF;

@@./src/04_deploy/packages/packages_loop.sql;

SPOOL OFF

quit;