ALTER SESSION DISABLE PARALLEL QUERY;

CREATE TABLE TMP_EPIC003_OUTPUTMODEL
(
    PERIODO NUMBER,
    CODCLAVECIC NUMBER,
    NBRCLIORDENANTE VARCHAR2(77),
    SEGMENTO VARCHAR2(35),
    MTO_TRANSF NUMBER,
    CTD_OPE NUMBER,
    FLG_PEP NUMBER,
    FLG_PROF NUMBER,
    FLG_PAR NUMBER,
    FLG_PERFIL NUMBER,
    CTDEVAL NUMBER,
    FLG_PAIS NUMBER,
    N_CLUSTER NUMBER,
    OUTLIER NUMBER
)TABLESPACE D_AML_99;