--PARAMETRO DE CREDENCIALES
@&1 

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

-- ========================================== SEGMENTOS =====================================================

--CREATE TABLE TMP_TTEE_CLIENTE_SEGEMENTO TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_CLIENTE_SEGEMENTO;
INSERT INTO TMP_TTEE_CLIENTE_SEGEMENTO
SELECT DISTINCT B.CODSUBSEGMENTO, B.DESSUBSEGMENTO,D.CODSEGMENTO,D.DESSEGMENTO
FROM 
ODS_V.MM_DESCODIGOSUBSEGMENTO B 
	LEFT JOIN ODS_V.MM_DESCODSUBSEGGEN C ON TRIM(B.CODSUBSEGGENERAL)=TRIM(C.CODSUBSEGGENERAL)
	LEFT JOIN ODS_V.MM_DESCODIGOSEGMENTO D ON TRIM(C.CODSEGMENTO)=TRIM(D.CODSEGMENTO);

-- ========================================== GGTT =====================================================

-- OBTENCION PARA BANCA PRIVADA GGTT----
--CREATE TABLE TMP_TTEE_GGTT_1 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_GGTT_1;
INSERT INTO TMP_TTEE_GGTT_1
SELECT 
	GGT.CODDOCGGTT AS CODIGO_OPERACION,
	GGT.CODCLAVECICORDENANTE AS CODCLAVECIC,
  TRIM(CL.APEPATCLI ) || ' ' ||TRIM(CL.APEMATCLI)    || ' ' ||TRIM(CL.NBRCLI)  AS NBRCLIORDENANTE,
	GGT.CODUNICOCLIORDENANTE AS CODUNICOCLI,
	GGT.CODUNICOCLIBENEFICIARIO,
	CASE WHEN GGT.CODMONEDA='1001' THEN 'DOLARES' ELSE 'SOLES' END AS MONEDA ,
	CASE WHEN GGT.CODMONEDA='1001' THEN GGT.MTOIMPORTEOPERACION  ELSE GGT.MTOIMPORTEOPERACION/MTOCAMBIOALNUEVOSOL END  AS MONTO_DOLAR,
	GGT.MTOIMPORTEOPERACION AS MTOTRX,
	GGT.CODMONEDA AS CODMONEDATRX,
	PN.CODPAISNACIONALIDAD AS NACIONALIDAD,
	GGT.FECDIA AS FECHA_OPERACION,
	DTC.DESTIPPER AS TIPO_PERSONA,
	GGT.CODPAISBCODESTINO AS PAIS_DESTINO,
	CL.TIPMARCACLI,
	CASE  WHEN CL.TIPMARCACLI='P' THEN 'SI' ELSE 'NO' END AS FLGPEP ,
	CA.DESCANAL AS CANAL, 
	E.DESSEGMENTO,
	GGT.NBRCLIBENEFICIARIO,
  TRIM(CL.CODSECTORISTA) || ' - ' || TRIM(SC.NBRSECTORISTA) AS CODSECTORISTA
FROM ODS_V.HD_DOCUMENTOEMITIDOGGTT GGT 
	 LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TP ON TP.CODMONEDA=GGT.CODMONEDA AND TP.FECTIPCAMBIO=GGT.FECDIA
	 LEFT JOIN ODS_V.MD_DESCODIGOCANAL  CA ON GGT.CODCANAL=CA.CODCANAL
	 LEFT JOIN ODS_V.MD_CLIENTE CL ON CL.CODCLAVECIC=GGT.CODCLAVECICORDENANTE
	 LEFT JOIN ODS_V.MD_PERSONANATURAL PN ON PN.CODCLAVECIC=GGT.CODCLAVECICORDENANTE
	 LEFT JOIN ODS_V.MM_DESCODACTIVIDADECONOMICA  AC ON AC.CODACTECONOMICA=CL.CODACTECONOMICA
	 LEFT JOIN ODS_V.MM_DESTIPOPERSONA DTC ON DTC.TIPPER=CL.TIPPER 
	 LEFT JOIN TMP_TTEE_CLIENTE_SEGEMENTO E ON E.CODSUBSEGMENTO=CL.CODSUBSEGMENTO
	 LEFT JOIN ODS_V.UD_SECTORISTA SC ON TRIM(SC.CODSECTORISTA) = TRIM(CL.CODSECTORISTA)
WHERE 
 GGT.CODPRODUCTO IN ('TRAEXT','GIREXT')
 AND DTC.DESTIPPER = 'NATURAL'
 AND GGT.FECDIA  BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
 AND CL.FLGREGELIMINADO='N' 
 AND (E.DESSEGMENTO = 'PRIVADA' AND NOT (
           (TRIM(GGT.NBRCLIBENEFICIARIO)   LIKE '%'||TRIM(GGT.APEPATCLISOLICITANTE)||'%'
              AND TRIM(GGT.NBRCLIBENEFICIARIO)   LIKE '%'||TRIM(GGT.APEMATCLISOLICITANTE)||'%' 
              AND TRIM(GGT.NBRCLIBENEFICIARIO)  LIKE'%'||TRIM(GGT.NBRCLISOLICITANTE)||'%')
          OR (TRIM(GGT.NBRCLIBENEFICIARIO)   LIKE '%'||TRIM(GGT.APEPATCLIORDENANTE)||'%' 
              AND TRIM(GGT.NBRCLIBENEFICIARIO)   LIKE '%'||TRIM(GGT.APEMATCLIORDENANTE)||'%'
              AND TRIM(GGT.NBRCLIBENEFICIARIO) LIKE '%'||TRIM(GGT.NBRCLIORDENANTE)||'%')));


--- OBTENCION PARA NO BANCA PRIVADA GGTT---
--CREATE TABLE TMP_TTEE_GGTT_2 TABLESPACE D_AML_99 AS 
TRUNCATE TABLE TMP_TTEE_GGTT_2;
INSERT INTO TMP_TTEE_GGTT_2
SELECT 
	GGT.CODDOCGGTT AS CODIGO_OPERACION,
	GGT.CODCLAVECICORDENANTE AS CODCLAVECIC,
  TRIM(CL.APEPATCLI) || ' ' ||TRIM(CL.APEMATCLI)    || ' ' ||TRIM(CL.NBRCLI)  AS NBRCLIORDENANTE,
	GGT.CODUNICOCLIORDENANTE AS CODUNICOCLI,
	GGT.CODUNICOCLIBENEFICIARIO,
	CASE WHEN GGT.CODMONEDA='1001' THEN 'DOLARES' ELSE 'SOLES' END AS MONEDA ,
	CASE WHEN GGT.CODMONEDA='1001' THEN GGT.MTOIMPORTEOPERACION  ELSE GGT.MTOIMPORTEOPERACION/MTOCAMBIOALNUEVOSOL END  AS MONTO_DOLAR,
	GGT.MTOIMPORTEOPERACION AS MTOTRX,
	GGT.CODMONEDA AS CODMONEDATRX,
	PN.CODPAISNACIONALIDAD AS NACIONALIDAD,
	GGT.FECDIA AS FECHA_OPERACION,
	DTC.DESTIPPER AS TIPO_PERSONA,
	GGT.CODPAISBCODESTINO AS PAIS_DESTINO,
	CL.TIPMARCACLI,
	CASE  WHEN CL.TIPMARCACLI='P' THEN 'SI' ELSE 'NO' END AS FLGPEP ,
	CA.DESCANAL AS CANAL, 
	E.DESSEGMENTO,
	GGT.NBRCLIBENEFICIARIO,
  TRIM(CL.CODSECTORISTA) || ' - ' || TRIM(SC.NBRSECTORISTA) AS CODSECTORISTA
FROM ODS_V.HD_DOCUMENTOEMITIDOGGTT GGT 
	 LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TP ON TP.CODMONEDA=GGT.CODMONEDA AND TP.FECTIPCAMBIO=GGT.FECDIA
	 LEFT JOIN ODS_V.MD_DESCODIGOCANAL  CA ON GGT.CODCANAL=CA.CODCANAL
	 LEFT JOIN ODS_V.MD_CLIENTE CL ON CL.CODCLAVECIC=GGT.CODCLAVECICORDENANTE
	 LEFT JOIN ODS_V.MD_PERSONANATURAL PN ON PN.CODCLAVECIC=GGT.CODCLAVECICORDENANTE
	 LEFT JOIN ODS_V.MM_DESCODACTIVIDADECONOMICA  AC ON AC.CODACTECONOMICA=CL.CODACTECONOMICA
	 LEFT JOIN ODS_V.MM_DESTIPOPERSONA DTC ON DTC.TIPPER=CL.TIPPER 
	 LEFT JOIN TMP_TTEE_CLIENTE_SEGEMENTO E ON E.CODSUBSEGMENTO=CL.CODSUBSEGMENTO
	 LEFT JOIN ODS_V.UD_SECTORISTA SC ON TRIM(SC.CODSECTORISTA) = TRIM(CL.CODSECTORISTA)
WHERE 
 GGT.CODPRODUCTO IN ('TRAEXT','GIREXT')
 AND DTC.DESTIPPER = 'NATURAL'
 AND GGT.FECDIA  BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
 AND CL.FLGREGELIMINADO='N'
 AND E.DESSEGMENTO <> 'PRIVADA'; 

--TABLA DE GGTT----
--CREATE TABLE TMP_TTEE_GGTT TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_GGTT;
INSERT INTO TMP_TTEE_GGTT
SELECT * FROM TMP_TTEE_GGTT_1
UNION ALL
SELECT * FROM TMP_TTEE_GGTT_2;

-- ========================================== BANNI =====================================================

-- OBTENCION DE BANCA PRIVADA BANNI ---
--CREATE TABLE TMP_TTEE_BANNI_1 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_BANNI_1;
INSERT INTO TMP_TTEE_BANNI_1
SELECT 
	CAST(NUMREGISTRO AS VARCHAR(25))  AS CODIGO_OPERACION,
	B.CODCLAVECIC, 
  TRIM(CL.APEPATCLI) || ' ' ||TRIM(CL.APEMATCLI)  || ' ' ||TRIM(CL.NBRCLI)  AS NOMBRE_CLIENTE,
	CL.CODUNICOCLI ,
	' ' AS CODUNICOCLIBENEFICIARIO,
	CASE WHEN B.CODMONEDA='1001' THEN 'DOLARES' ELSE 'SOLES' END AS MONEDA,
	B.MTOOPERACIONDOL AS MONTO_DOLAR,
	B.MTOOPERACIONSOL  AS MTOTRX,
	B.CODMONEDA AS CODMONEDATRX,
	PN.CODPAISNACIONALIDAD AS NACIONALIDAD,
	B.FECDIA AS FECHA_OPERACION,
	DTC.DESTIPPER AS TIPO_PERSONA ,      
	B.CODPAISBENEFICIARIO AS PAIS_DESTINO,
	CL.TIPMARCACLI,
	CASE  WHEN CL.TIPMARCACLI='P' THEN 'SI' ELSE 'NO' END AS FLGPEP ,
	' ' AS CANAL ,
	E.DESSEGMENTO,
	B.NBRCLIBENEFICIARIO,
	TRIM(CL.CODSECTORISTA) || ' - ' || TRIM(SC.NBRSECTORISTA) AS CODSECTORISTA
FROM ODS_V.HD_MOVIMIENTOBANNI  A
	 LEFT JOIN ODS_V.MD_OPERACIONBAN B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA
	 LEFT JOIN ODS_V.MD_CLIENTE CL ON CL.CODCLAVECIC=B.CODCLAVECIC
	 LEFT JOIN ODS_V.MD_PERSONANATURAL PN ON PN.CODCLAVECIC=B.CODCLAVECIC
	 LEFT JOIN ODS_V.MM_DESCODACTIVIDADECONOMICA  AC ON AC.CODACTECONOMICA=CL.CODACTECONOMICA
	 LEFT JOIN ODS_V.MM_DESTIPOPERSONA DTC ON DTC.TIPPER=CL.TIPPER
	 LEFT JOIN TMP_TTEE_CLIENTE_SEGEMENTO E ON E.CODSUBSEGMENTO=CL.CODSUBSEGMENTO
	 LEFT JOIN ODS_V.UD_SECTORISTA SC ON TRIM(SC.CODSECTORISTA) = TRIM(CL.CODSECTORISTA)
WHERE  B.FECDIA  BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
	AND DTC.DESTIPPER = 'NATURAL'
  AND  A.CODPRODUCTO = 'TRAEXT'
  AND B.FLGREGELIMINADO='N' 
  AND TRIM(B.NBRCLISOLICITANTE) <> TRIM(B.NBRCLIBENEFICIARIO)  
  AND (E.DESSEGMENTO = 'PRIVADA' AND NOT (
           (TRIM(B.NBRCLIBENEFICIARIO)   LIKE '%'||TRIM(CL.APEPATCLI)||'%'
              AND TRIM(B.NBRCLIBENEFICIARIO)   LIKE '%'||TRIM(CL.APEMATCLI)||'%' 
              AND TRIM(B.NBRCLIBENEFICIARIO)  LIKE'%'||TRIM(CL.NBRCLI)||'%')));


--OBTENCION PARA NO BANCA PRIVADA BANNI---
--CREATE TABLE TMP_TTEE_BANNI_2 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_BANNI_2;
INSERT INTO TMP_TTEE_BANNI_2
SELECT 
	CAST(NUMREGISTRO AS VARCHAR(25))  AS CODIGO_OPERACION,
	B.CODCLAVECIC, 
  TRIM(CL.APEPATCLI) || ' ' ||TRIM(CL.APEMATCLI) || ' ' ||TRIM(CL.NBRCLI)  AS NOMBRE_CLIENTE,
	CL.CODUNICOCLI ,
	' ' AS CODUNICOCLIBENEFICIARIO,
	CASE WHEN B.CODMONEDA='1001' THEN 'DOLARES' ELSE 'SOLES' END AS MONEDA,
	B.MTOOPERACIONDOL AS MONTO_DOLAR,
	B.MTOOPERACIONSOL  AS MTOTRX,
	B.CODMONEDA AS CODMONEDATRX,
	PN.CODPAISNACIONALIDAD AS NACIONALIDAD,
	B.FECDIA AS FECHA_OPERACION,
	DTC.DESTIPPER AS TIPO_PERSONA ,      
	B.CODPAISBENEFICIARIO AS PAIS_DESTINO,
	CL.TIPMARCACLI,
	CASE  WHEN CL.TIPMARCACLI='P' THEN 'SI' ELSE 'NO' END AS FLGPEP ,
	' ' AS CANAL ,
	E.DESSEGMENTO,
	B.NBRCLIBENEFICIARIO,
	TRIM(CL.CODSECTORISTA) || ' - ' || TRIM(SC.NBRSECTORISTA) AS CODSECTORISTA
FROM ODS_V.HD_MOVIMIENTOBANNI  A
	 LEFT JOIN ODS_V.MD_OPERACIONBAN B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA
	 LEFT JOIN ODS_V.MD_CLIENTE CL ON CL.CODCLAVECIC=B.CODCLAVECIC
	 LEFT JOIN ODS_V.MD_PERSONANATURAL PN ON PN.CODCLAVECIC=B.CODCLAVECIC
	 LEFT JOIN ODS_V.MM_DESCODACTIVIDADECONOMICA  AC ON AC.CODACTECONOMICA=CL.CODACTECONOMICA
	 LEFT JOIN ODS_V.MM_DESTIPOPERSONA DTC ON DTC.TIPPER=CL.TIPPER
	 LEFT JOIN TMP_TTEE_CLIENTE_SEGEMENTO E ON E.CODSUBSEGMENTO=CL.CODSUBSEGMENTO
	 LEFT JOIN ODS_V.UD_SECTORISTA SC ON TRIM(SC.CODSECTORISTA) = TRIM(CL.CODSECTORISTA)
WHERE  B.FECDIA  BETWEEN TRUNC(ADD_MONTHS(SYSDATE,:INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
  AND DTC.DESTIPPER = 'NATURAL'  
  AND A.CODPRODUCTO = 'TRAEXT'
  AND B.FLGREGELIMINADO='N' 
  AND TRIM(B.NBRCLISOLICITANTE) <> TRIM(B.NBRCLIBENEFICIARIO)  
  AND (E.DESSEGMENTO <> 'PRIVADA');

--TABLA DE BANNI----
--CREATE TABLE TMP_TTEE_BANNI TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_BANNI;
INSERT INTO TMP_TTEE_BANNI
SELECT * FROM TMP_TTEE_BANNI_1
UNION ALL
SELECT * FROM TMP_TTEE_BANNI_2;


-- ========================================== UNIVERSO =====================================================

--TABLON FINAL
--CREATE TABLE TMP_TTEE_FINAL TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_FINAL;
INSERT INTO TMP_TTEE_FINAL
SELECT * FROM TMP_TTEE_GGTT
UNION ALL
SELECT * FROM TMP_TTEE_BANNI;

--CREATE TABLE TMP_TTEE_UNIVERSO TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_TTEE_UNIVERSO;
INSERT INTO TMP_TTEE_UNIVERSO
SELECT TO_NUMBER(TO_CHAR(FECHA_OPERACION,'YYYYMM')) AS PERIODO, CODCLAVECIC, SUM(MONTO_DOLAR) AS MTO_TRANSF, COUNT(CODCLAVECIC) AS CTD_OPE
FROM TMP_TTEE_FINAL
GROUP BY TO_NUMBER(TO_CHAR(FECHA_OPERACION,'YYYYMM')),CODCLAVECIC;

QUIT;
