--PARAMETRO DE CREDENCIALES
@&1

ALTER SESSION DISABLE PARALLEL QUERY;

SET ECHO OFF
SET FEEDBACK OFF
SET HEAD OFF
SET LIN 9999
SET TRIMSPOOL ON
SET WRAP OFF
SET PAGES 0
SET TERM OFF

SPOOL '.\data\production\01_raw.csv';


PROMPT PERIODO|CODCLAVECIC|NBRCLIORDENANTE|SEGMENTO|MTO_TRANSF|CTD_OPE|FLG_PEP|FLG_PROF|FLG_PAR|FLG_PERFIL|CTDEVAL;

SELECT
    PERIODO||'|'||
    CODCLAVECIC||'|'||
    TRIM(NBRCLIORDENANTE)||'|'||
    TRIM(SEGMENTO)||'|'||
    REPLACE(TRIM(TO_CHAR(MTO_TRANSF,'99999999999999999990D00')),',','.')||'|'||
    CTD_OPE||'|'||
    FLG_PEP||'|'||
    FLG_PROF||'|'||
    FLG_PAR||'|'||
    FLG_PERFIL||'|'||
    CTDEVAL
FROM TMP_TTEE_TABLON_FINAL;

SPOOL OFF;

QUIT;