--PARAMETRO DE CREDENCIALES
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--TABLA DE ALERTAS

--DROP TABLE TMP_ESCPEP_ALERTAS;
TRUNCATE TABLE TMP_ESCPEP_ALERTAS;
INSERT INTO TMP_ESCPEP_ALERTAS
--CREATE TABLE TMP_ESCPEP_ALERTAS TABLESPACE D_AML_99 AS
SELECT DISTINCT B.CODUNICOCLI, B.APEPATCLI || ' ' || B.APEMATCLI || ' ' || B.NBRCLI AS NBRCLI, A.*
FROM TMP_ESCPEP_SALIDA_MODELO A
LEFT JOIN (SELECT CODCLAVECIC, CODUNICOCLI, APEPATCLI, APEMATCLI, NBRCLI FROM ODS_V.MD_CLIENTEG94 WHERE FLGREGELIMINADO = 'N') B ON A.CODCLAVECIC = B.CODCLAVECIC
WHERE N_CLUSTER IN (2,3,4,5);

--EXTRACCION DE TRANSACCIONES

--DROP TABLE TMP_ESCPEP_TRXS_ALERTAS_AUX;
--CREATE TABLE TMP_ESCPEP_TRXS_ALERTAS_AUX TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRXS_ALERTAS_AUX;
INSERT INTO TMP_ESCPEP_TRXS_ALERTAS_AUX
SELECT A.* FROM TMP_ESCPEP_TRXS A INNER JOIN  TMP_ESCPEP_ALERTAS B ON A.CODCLAVECICSOURCE = B.CODCLAVECIC
UNION ALL
SELECT A.* FROM TMP_ESCPEP_TRXS A INNER JOIN  TMP_ESCPEP_ALERTAS B ON A.CODCLAVECICTARGET = B.CODCLAVECIC;


--DROP TABLE TMP_ESCPEP_TRXS_ALERTAS_AUX2;
--CREATE TABLE TMP_ESCPEP_TRXS_ALERTAS_AUX2 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRXS_ALERTAS_AUX2;
INSERT INTO TMP_ESCPEP_TRXS_ALERTAS_AUX2
SELECT DISTINCT
A.PERIODO,A.NUMREGISTRO,A.CODCLAVECICSOURCE,A.CODCLAVEOPECTASOURCE,
B.APEPATCLIORDENANTE||B.APEMATCLIORDENANTE||B.NBRCLIORDENANTE AS DATOSOURCE,A.PAISSOURCE,
A.FECDIA,A.HORTRANSACCION,A.CODMONEDA,A.MTOTRANSACCION,A.MTODOLARIZADO,A.TIPOTRANSACCION,A.CANAL,A.CODCLAVECICTARGET,A.CODCLAVEOPECTATARGET,
B.NBRCLIBENEFICIARIO AS DATOTARGET,A.PAISTARGET,
A.TIPOINGRESOEGRESO,A.FLGCASH
FROM TMP_ESCPEP_TRXS_ALERTAS_AUX A
LEFT JOIN ODS_V.HD_DOCUMENTOEMITIDOGGTT B ON A.NUMREGISTRO = B.CODDOCGGTT
WHERE A.CANAL = 'DOCUMENTOGGTT'
UNION ALL
SELECT DISTINCT
A.PERIODO,A.NUMREGISTRO,A.CODCLAVECICSOURCE,A.CODCLAVEOPECTASOURCE,
B.NBRCLISOLICITANTE AS DATOSOURCE,A.PAISSOURCE,
A.FECDIA,A.HORTRANSACCION,A.CODMONEDA,A.MTOTRANSACCION,A.MTODOLARIZADO,A.TIPOTRANSACCION,A.CANAL,A.CODCLAVECICTARGET,A.CODCLAVEOPECTATARGET,
A.DATOTARGET,A.PAISTARGET,
TIPOINGRESOEGRESO,FLGCASH
FROM TMP_ESCPEP_TRXS_ALERTAS_AUX A
LEFT JOIN ODS_V.HD_MOVOPERATIVOREMITTANCE B ON A.NUMREGISTRO = B.NUMOPERACIONREMITTANCE AND A.FECDIA = B.FECDIA AND A.HORTRANSACCION = B.HORTRANSACCION
WHERE A.CANAL = 'REMITTANCE'
UNION ALL
SELECT DISTINCT
A.PERIODO,A.NUMREGISTRO,A.CODCLAVECICSOURCE,A.CODCLAVEOPECTASOURCE,
B.NBRCLIORDENANTE AS DATOSOURCE,B.CODCTAINTERBANORDENANTE AS PAISSOURCE,
A.FECDIA,A.HORTRANSACCION,A.CODMONEDA,A.MTOTRANSACCION,A.MTODOLARIZADO,A.TIPOTRANSACCION,A.CANAL,A.CODCLAVECICTARGET,A.CODCLAVEOPECTATARGET,
B.NBRCLIBENEFICIARIO AS DATOTARGET,B.CODCTAINTERBANBENEFICIARIO AS PAISTARGET,
A.TIPOINGRESOEGRESO,A.FLGCASH
FROM TMP_ESCPEP_TRXS_ALERTAS_AUX A
LEFT JOIN ODS_V.HD_MOVIMIENTOTTIB B ON A.NUMREGISTRO = B.NUMSECUENCIAL AND A.FECDIA = B.FECTRANSACCION AND A.HORTRANSACCION = B.HORTRANSACCION
WHERE A.CANAL = 'TTIB'
UNION ALL
SELECT A.PERIODO,A.NUMREGISTRO,A.CODCLAVECICSOURCE,A.CODCLAVEOPECTASOURCE,
A.DATOSOURCE,A.PAISSOURCE,
A.FECDIA,A.HORTRANSACCION,A.CODMONEDA,A.MTOTRANSACCION,A.MTODOLARIZADO,A.TIPOTRANSACCION,A.CANAL,A.CODCLAVECICTARGET,A.CODCLAVEOPECTATARGET,
A.DATOTARGET,A.PAISTARGET,
A.TIPOINGRESOEGRESO,A.FLGCASH
FROM TMP_ESCPEP_TRXS_ALERTAS_AUX A
WHERE A.CANAL NOT IN ('TTIB','REMITTANCE','DOCUMENTOGGTT');

--DROP TABLE TMP_ESCPEP_TRXS_ALERTAS_INFOCLIS;
TRUNCATE TABLE TMP_ESCPEP_TRXS_ALERTAS_INFOCLIS;
INSERT INTO TMP_ESCPEP_TRXS_ALERTAS_INFOCLIS
--CREATE TABLE TMP_ESCPEP_TRXS_ALERTAS_INFOCLIS TABLESPACE D_AML_99 AS

SELECT
A.CODCLAVECIC,
B.CODUNICOCLI,
B.APEPATCLI||' '||B.APEMATCLI||' '||B.NBRCLI AS NBRCLI
FROM (
  SELECT CODCLAVECICSOURCE AS CODCLAVECIC FROM TMP_ESCPEP_TRXS_ALERTAS_AUX
  UNION 
  SELECT CODCLAVECICTARGET AS CODCLAVECIC FROM TMP_ESCPEP_TRXS_ALERTAS_AUX
) A
LEFT JOIN (SELECT * FROM ODS_V.MD_CLIENTEG94 ) B ON A.CODCLAVECIC = B.CODCLAVECIC
WHERE A.CODCLAVECIC <> -1;

--DROP TABLE TMP_ESCPEP_TRXS_ALERTAS_INFOCUENTAS;
--CREATE TABLE TMP_ESCPEP_TRXS_ALERTAS_INFOCUENTAS TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRXS_ALERTAS_INFOCUENTAS;
INSERT INTO TMP_ESCPEP_TRXS_ALERTAS_INFOCUENTAS
SELECT DISTINCT
A.CODCLAVEOPECTA,
B.CODOPECTA
FROM (
  SELECT CODCLAVEOPECTASOURCE AS CODCLAVEOPECTA FROM TMP_ESCPEP_TRXS_ALERTAS_AUX
  UNION
  SELECT CODCLAVEOPECTATARGET AS CODCLAVEOPECTA FROM TMP_ESCPEP_TRXS_ALERTAS_AUX
) A
LEFT JOIN (SELECT * FROM ODS_V.MD_CUENTAG94 WHERE FLGREGELIMINADO = 'N') B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA;

--DROP TABLE TMP_ESCPEP_TRXS_ALERTAS;
--CREATE TABLE TMP_ESCPEP_TRXS_ALERTAS TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRXS_ALERTAS;
INSERT INTO TMP_ESCPEP_TRXS_ALERTAS
SELECT A.PERIODO,A.NUMREGISTRO,
CASE WHEN A.CODCLAVECICSOURCE = -1 THEN NULL ELSE A.CODCLAVECICSOURCE END AS CODCLAVECICORIGEN,G1.CODUNICOCLI AS CODUNICOCLIORIGEN,G1.NBRCLI AS NBRCLIORIGEN,
CASE WHEN A.CODCLAVEOPECTASOURCE = -1 THEN NULL ELSE A.CODCLAVEOPECTASOURCE END AS CODCLAVEOPECTAORIGEN,C1.CODOPECTA AS CODOPECTAORIGEN,
A.DATOSOURCE AS DATOORIGEN1_NBRCLI,A.PAISSOURCE AS DATOORIGEN2_PAIS_CTACCI,
A.FECDIA,A.HORTRANSACCION,A.CODMONEDA,A.MTOTRANSACCION,A.MTODOLARIZADO,A.TIPOTRANSACCION,A.CANAL,
CASE WHEN A.CODCLAVECICTARGET = -1 THEN NULL ELSE A.CODCLAVECICTARGET END AS CODCLAVECICDESTINO,G2.CODUNICOCLI AS CODUNICOCLIDESTINO,G2.NBRCLI AS NBRCLIDESTINO,
CASE WHEN A.CODCLAVEOPECTATARGET = -1 THEN NULL ELSE A.CODCLAVEOPECTATARGET END AS CODCLAVEOPECTADESTINO,C2.CODOPECTA AS CODOPECTADESTINO,
A.DATOTARGET AS DATODESTINO1_NBRCLI,A.PAISTARGET AS DATODESTINO2_PAIS_CTACCI,
A.TIPOINGRESOEGRESO,A.FLGCASH
FROM TMP_ESCPEP_TRXS_ALERTAS_AUX2 A
LEFT JOIN TMP_ESCPEP_TRXS_ALERTAS_INFOCLIS G1 ON A.CODCLAVECICSOURCE = G1.CODCLAVECIC
LEFT JOIN TMP_ESCPEP_TRXS_ALERTAS_INFOCLIS G2 ON A.CODCLAVECICTARGET = G2.CODCLAVECIC
LEFT JOIN TMP_ESCPEP_TRXS_ALERTAS_INFOCUENTAS C1 ON A.CODCLAVEOPECTASOURCE = C1.CODCLAVEOPECTA
LEFT JOIN TMP_ESCPEP_TRXS_ALERTAS_INFOCUENTAS C2 ON A.CODCLAVEOPECTATARGET = C2.CODCLAVEOPECTA;

--EXTRACCION DE LOS EECC

--ESTADO DE CUENTA

--DROP TABLE TMP_ESCPEP_CODCLAVECICS_ALERTAS;
--CREATE TABLE TMP_ESCPEP_CODCLAVECICS_ALERTAS TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_CODCLAVECICS_ALERTAS;
INSERT INTO TMP_ESCPEP_CODCLAVECICS_ALERTAS
SELECT DISTINCT CODCLAVECIC AS CODCLAVECIC FROM TMP_ESCPEP_ALERTAS;

--LISTAR EECC:

--DROP TABLE TMP_ESCPEP_INICIAL;
--CREATE TABLE TMP_ESCPEP_INICIAL TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_INICIAL;
INSERT INTO TMP_ESCPEP_INICIAL
SELECT A.CODCLAVECIC, CODUNICOCLI, TIPPER,
       CASE WHEN TIPPER = 'E' THEN TRIM(APEPATCLI) || TRIM(APEMATCLI) || TRIM(NBRCLI)
            WHEN TIPPER = 'P' THEN TRIM(APEPATCLI) || ' ' || TRIM(APEMATCLI) || ' ' || TRIM(NBRCLI)
       END AS NOMBRE
FROM ODS_V.MD_CLIENTE A
INNER JOIN TMP_ESCPEP_CODCLAVECICS_ALERTAS B ON A.CODCLAVECIC = B.CODCLAVECIC
     AND A.CODCLAVECIC NOT IN (SELECT CODCLAVECIC FROM ODS_V.MD_EMPLEADOG94)
UNION
SELECT A.CODCLAVECIC, CODUNICOCLI, 'P', TRIM(APEPATEMPLEADO) || ' ' || TRIM(APEMATEMPLEADO) || ' ' || TRIM(NBREMPLEADO)
FROM ODS_V.MD_EMPLEADOG94 A
INNER JOIN TMP_ESCPEP_CODCLAVECICS_ALERTAS B ON A.CODCLAVECIC = B.CODCLAVECIC;

--CREATE INDEX IDX_PAGOALSANT_EECC_CODCLAVECIC ON TMP_ESCPEP_INICIAL (CODCLAVECIC) TABLESPACE D_AML_99;

--DROP TABLE TMP_ESCPEP_CTAS;
--CREATE TABLE TMP_ESCPEP_CTAS TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_CTAS;
INSERT INTO TMP_ESCPEP_CTAS
SELECT CTA.CODCLAVECIC, B.CODUNICOCLI, B.NOMBRE, CTA.CODCLAVEOPECTA, CODSISTEMAORIGEN, CODOPECTA,
       CASE WHEN CTA.CODSISTEMAORIGEN = 'SAV' THEN
            SUBSTR(CODOPECTA,1,3) || '-' ||
            TRIM(TO_CHAR(MOD(TO_NUMBER(SUBSTR(CODOPECTA,5,16)),100000000), '00000009')) || '-' ||
            SUBSTR(CODMONEDA,1,1) || '-' ||
            TRIM(TO_CHAR(
            CASE WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') THEN
                MOD(TO_NUMBER(SUBSTR(CODOPECTA,13,2)) + TO_NUMBER(SUBSTR(CODOPECTA,15,2)) +
                TO_NUMBER(SUBSTR(CODOPECTA,17,2)) + TO_NUMBER(SUBSTR(CODOPECTA,19,2)), 100)
            ELSE
                MOD(-20 + TO_NUMBER(SUBSTR(CODOPECTA,1,1)) + TO_NUMBER(SUBSTR(CODOPECTA,2,2)) + TO_NUMBER(SUBSTR(CODOPECTA,13,2)) +
                TO_NUMBER(SUBSTR(CODOPECTA,15,2)) + TO_NUMBER(SUBSTR(CODOPECTA,17,2)) + TO_NUMBER(SUBSTR(CODOPECTA,19,2)), 100)
            END, '09'))
       WHEN CTA.CODSISTEMAORIGEN = 'IMP' THEN
            SUBSTR(CODOPECTA,1,3) || '-' ||
            TRIM(TO_CHAR(MOD(TO_NUMBER(SUBSTR(CODOPECTA,5,16)),10000000), '0000009')) || '-' ||
            SUBSTR(CODMONEDA,1,1) || '-' ||
            TRIM(TO_CHAR(
            CASE WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') AND CODMONEDA='0001' THEN
            			MOD(TO_NUMBER(SUBSTR(CODOPECTA,14,2)) + TO_NUMBER(SUBSTR(CODOPECTA,16,2)) +
            			TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10, 100)
            		WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') AND CODMONEDA='1001' THEN
            			MOD(TO_NUMBER(SUBSTR(CODOPECTA,14,2)) + TO_NUMBER(SUBSTR(CODOPECTA,16,2)) +
            			TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10+10, 100)
            		WHEN SUBSTR(CODOPECTA,1,3) NOT IN ('191','192','193','194') AND CODMONEDA='0001' THEN
            			MOD(TO_NUMBER(SUBSTR(CODOPECTA,1,1)) + TO_NUMBER(SUBSTR(CODOPECTA,2,2)) + TO_NUMBER(SUBSTR(CODOPECTA,14,2)) +
                  TO_NUMBER(SUBSTR(CODOPECTA,16,2)) + TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10, 100)
            		WHEN SUBSTR(CODOPECTA,1,3) NOT IN ('191','192','193','194') AND CODMONEDA='1001' THEN
            			MOD(10 + TO_NUMBER(SUBSTR(CODOPECTA,1,1)) + TO_NUMBER(SUBSTR(CODOPECTA,2,2)) + TO_NUMBER(SUBSTR(CODOPECTA,14,2)) +
                  TO_NUMBER(SUBSTR(CODOPECTA,16,2)) + TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10, 100)
            	   END, '09'))
        END AS CUENTACOMERCIAL
FROM ODS_V.MD_CUENTA CTA
     INNER JOIN TMP_ESCPEP_INICIAL B ON CTA.CODCLAVECIC = B.CODCLAVECIC
WHERE CTA.CODSISTEMAORIGEN IN ('SAV','IMP')
      AND CTA.CODCLAVEOPECTA NOT IN (SELECT CODCLAVEOPECTA FROM ODS_V.MD_CUENTAG94)
UNION
SELECT CTA.CODCLAVECIC, B.CODUNICOCLI, B.NOMBRE, CTA.CODCLAVEOPECTA, CODSISTEMAORIGEN, CODOPECTA,
       CASE WHEN CTA.CODSISTEMAORIGEN = 'SAV' THEN
            SUBSTR(CODOPECTA,1,3) || '-' ||
            TRIM(TO_CHAR(MOD(TO_NUMBER(SUBSTR(CODOPECTA,5,16)),100000000), '00000009')) || '-' ||
            SUBSTR(CODMONEDA,1,1) || '-' ||
            TRIM(TO_CHAR(
            CASE WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') THEN
                MOD(TO_NUMBER(SUBSTR(CODOPECTA,13,2)) + TO_NUMBER(SUBSTR(CODOPECTA,15,2)) +
                TO_NUMBER(SUBSTR(CODOPECTA,17,2)) + TO_NUMBER(SUBSTR(CODOPECTA,19,2)), 100)
            ELSE
                MOD(-20 + TO_NUMBER(SUBSTR(CODOPECTA,1,1)) + TO_NUMBER(SUBSTR(CODOPECTA,2,2)) + TO_NUMBER(SUBSTR(CODOPECTA,13,2)) +
                TO_NUMBER(SUBSTR(CODOPECTA,15,2)) + TO_NUMBER(SUBSTR(CODOPECTA,17,2)) + TO_NUMBER(SUBSTR(CODOPECTA,19,2)), 100)
            END, '09'))
       WHEN CTA.CODSISTEMAORIGEN = 'IMP' THEN
            SUBSTR(CODOPECTA,1,3) || '-' ||
            TRIM(TO_CHAR(MOD(TO_NUMBER(SUBSTR(CODOPECTA,5,16)),10000000), '0000009')) || '-' ||
            SUBSTR(CODMONEDA,1,1) || '-' ||
            TRIM(TO_CHAR(
            CASE WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') AND CODMONEDA='0001' THEN
            			MOD(TO_NUMBER(SUBSTR(CODOPECTA,14,2)) + TO_NUMBER(SUBSTR(CODOPECTA,16,2)) +
            			TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10, 100)
            		WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') AND CODMONEDA='1001' THEN
            			MOD(TO_NUMBER(SUBSTR(CODOPECTA,14,2)) + TO_NUMBER(SUBSTR(CODOPECTA,16,2)) +
            			TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10+10, 100)
            		WHEN SUBSTR(CODOPECTA,1,3) NOT IN ('191','192','193','194') AND CODMONEDA='0001' THEN
            			MOD(TO_NUMBER(SUBSTR(CODOPECTA,1,1)) + TO_NUMBER(SUBSTR(CODOPECTA,2,2)) + TO_NUMBER(SUBSTR(CODOPECTA,14,2)) +
                  TO_NUMBER(SUBSTR(CODOPECTA,16,2)) + TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10, 100)
            		WHEN SUBSTR(CODOPECTA,1,3) NOT IN ('191','192','193','194') AND CODMONEDA='1001' THEN
            			MOD(10 + TO_NUMBER(SUBSTR(CODOPECTA,1,1)) + TO_NUMBER(SUBSTR(CODOPECTA,2,2)) + TO_NUMBER(SUBSTR(CODOPECTA,14,2)) +
                  TO_NUMBER(SUBSTR(CODOPECTA,16,2)) + TO_NUMBER(SUBSTR(CODOPECTA,18,2)) + TO_NUMBER(SUBSTR(CODOPECTA,20,1))*10, 100)
            	   END, '09'))
        END AS CUENTACOMERCIAL
FROM ODS_V.MD_CUENTAG94 CTA
     INNER JOIN TMP_ESCPEP_INICIAL B ON CTA.CODCLAVECIC = B.CODCLAVECIC
WHERE CTA.CODSISTEMAORIGEN IN ('SAV','IMP');

--CREATE INDEX IDX_PAGOALSANT_EECC_CTAS ON TMP_ESCPEP_CTAS (CODCLAVEOPECTA) TABLESPACE D_AML_99;

--DROP TABLE TMP_ESCPEP_SAVING;
--CREATE TABLE TMP_ESCPEP_SAVING TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_SAVING;
INSERT INTO TMP_ESCPEP_SAVING
SELECT B.CODCLAVECIC, B.CODUNICOCLI, B.NOMBRE, A.CODCLAVEOPECTA, B.CODOPECTA, B.CUENTACOMERCIAL, A.FECDIA, A.HORTRANSACCION, A.DESOPETRANSACCIONSAVINGDETALLE, F.GRUPO,
       C.DESCANAL, D.NBRSUCAGE, A.CODMONEDA, A.MTOTRANSACCION, A.TIPCARGOABONO, ROUND(A.MTOTRANSACCION * E.MTOCAMBIOALDOLAR, 2) AS MTODOLARIZADO
FROM ODS_V.HD_MOVIMIENTOSAVING A
     INNER JOIN TMP_ESCPEP_CTAS B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA AND B.CODSISTEMAORIGEN = 'SAV'
     LEFT JOIN ODS_V.MD_DESCODIGOCANAL C ON A.CODCANAL = C.CODCANAL
     LEFT JOIN ODS_V.MD_AGENCIA D ON A.CODSUCAGE = D.CODSUCAGE
     LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO E ON A.FECDIA = E.FECTIPCAMBIO AND A.CODMONEDA = E.CODMONEDA
     LEFT JOIN S55632.RM_EQUIVAL_TIPOPE_EECC_TMP F ON TRIM(A.DESOPETRANSACCIONSAVINGDETALLE) LIKE (TRIM(F.GLOSA) || '%')
WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) ;

--DROP TABLE TMP_ESCPEP_IMPAC;
--CREATE TABLE TMP_ESCPEP_IMPAC TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_IMPAC;
INSERT INTO TMP_ESCPEP_IMPAC
SELECT B.CODCLAVECIC, B.CODUNICOCLI, B.NOMBRE, A.CODCLAVEOPECTA, B.CODOPECTA, B.CUENTACOMERCIAL, A.FECDIA, A.HORTRANSACCION, A.DESOPETRANSACCIONIMPACDETALLE, F.GRUPO,
       C.DESCANAL, D.NBRSUCAGE, A.CODMONEDA, A.MTOTRANSACCION, A.TIPCARGOABONO, ROUND(A.MTOTRANSACCION * E.MTOCAMBIOALDOLAR, 2) AS MTODOLARIZADO
FROM ODS_V.HD_MOVIMIENTOIMPAC A
     INNER JOIN TMP_ESCPEP_CTAS B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA AND B.CODSISTEMAORIGEN = 'IMP'
     LEFT JOIN ODS_V.MD_DESCODIGOCANAL C ON A.CODCANAL = C.CODCANAL
     LEFT JOIN ODS_V.MD_AGENCIA D ON A.CODSUCAGE = D.CODSUCAGE
     LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO E ON A.FECDIA = E.FECTIPCAMBIO AND A.CODMONEDA = E.CODMONEDA
     LEFT JOIN S55632.RM_EQUIVAL_TIPOPE_EECC_TMP F ON TRIM(A.DESOPETRANSACCIONIMPACDETALLE) LIKE (TRIM(F.GLOSA) || '%')
WHERE A.FECDIA BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

--DROP TABLE TMP_ESCPEP_EECC_ALERTAS;
--CREATE TABLE TMP_ESCPEP_EECC_ALERTAS TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_EECC_ALERTAS;
INSERT INTO TMP_ESCPEP_EECC_ALERTAS
SELECT * FROM TMP_ESCPEP_SAVING A
UNION ALL
SELECT * FROM TMP_ESCPEP_IMPAC;

COMMIT;
SPOOL OFF
QUIT;