@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

--Tabla sobre Escenario de PEPs

CREATE TABLE TMP_ESCPEP_SALIDA_MODELO
(	PERIODO NUMBER,
	CODCLAVECIC NUMBER,
	CTDNP NUMBER,
	CTDLSB NUMBER,
	CTDEVALS NUMBER,
	FLGARCHIVONEGATIVO NUMBER,
	CTD_CTAS_NUEVAS NUMBER,
	MTO_TOTAL NUMBER,
	MTO_CASH NUMBER,
	MTO_TIB NUMBER,
	MTO_DEL_TTEE NUMBER,
	MTO_EMP_REL_NOPDH NUMBER,
	FLG_INGR_TER_NP_LSB NUMBER,
	FLG_INGR_TER_AN NUMBER,
	CTD_DEPO_10K NUMBER,
	CTD_INGR_REL_NPLSP NUMBER,
	MTO_EGRESO NUMBER,
	MTO_AL_TTEE NUMBER,
	FLG_PERFIL_INGTOTAL_3DS NUMBER,
	FLG_PERFIL_INGCASH_3DS NUMBER,
	FLG_PERFIL_EGR_3DS NUMBER,
	FLG_PERFIL_ING_EGR_3DS NUMBER,
	FLG_PERFIL_AL_DEL_TTEE_3DS NUMBER,
	FLG_PERFIL_INGR_VS_ESTIM NUMBER,
	N_Cluster NUMBER
) TABLESPACE D_AML_99 ;

COMMIT;
quit;