ALTER SESSION DISABLE PARALLEL QUERY;

SET ECHO OFF
SET FEEDBACK OFF
SET HEAD OFF
SET LIN 256
SET TRIMSPOOL ON
SET WRAP OFF
SET PAGES 0
SET TERM OFF
set colsep ','

SPOOL \\Pfilep11\lavadoactivos\99_Procesos_BI\0_SapycWeb\PAQUETES_ADHOC\99999999_MODEM_EPIC019_TRXS_&&CODUNICOCLI..CSV;

PROMPT FECDIA,CODSUCAGE,CODSESION,HORINITRANSACCION,DESTRANSACCIONVENTANILLA,CODMONEDACTA,MTOTRANSACCIONCTA,CODOPECTA,CODOPECTADESTINO,CODCLAVECICSOLICITANTE,CODUNICOCLISOLICITANTE,NOMBRESOLICITANTE,CODCLAVECICBENEFICIARIO,CODUNICOCLIBENEFICIARIO,NOMBREBENEFICIARIO,CODDEPARTAMENTO;

SELECT
	FECDIA||','||
	CODSUCAGE||','||
	CODSESION||','||
	HORINITRANSACCION||','||
	DESTRANSACCIONVENTANILLA||','||
	CODMONEDACTA||','||
	REPLACE(TRIM(TO_CHAR(MTOTRANSACCIONCTA,'99999999999999999990D00')),',','.')||','||
	CODOPECTA||','||
	CODOPECTADESTINO||','||
	CODCLAVECICSOLICITANTE||','||
	CODUNICOCLISOLICITANTE||','||
	NOMBRESOLICITANTE||','||
	CODCLAVECICBENEFICIARIO||','||
	CODUNICOCLIBENEFICIARIO||','||
	NOMBREBENEFICIARIO||','||
	CODDEPARTAMENTO
FROM TMP_TRX_EPIC019_3
WHERE CODCLAVECICBENEFICIARIO = :CODCLAVECIC
UNION ALL
SELECT
	FECDIA||','||
	CODSUCAGE||','||
	CODSESION||','||
	HORINITRANSACCION||','||
	DESTRANSACCIONVENTANILLA||','||
	CODMONEDACTA||','||
	REPLACE(TRIM(TO_CHAR(MTOTRANSACCIONCTA,'99999999999999999990D00')),',','.')||','||
	CODOPECTA||','||
	CODOPECTADESTINO||','||
	CODCLAVECICSOLICITANTE||','||
	CODUNICOCLISOLICITANTE||','||
	NOMBRESOLICITANTE||','||
	CODCLAVECICBENEFICIARIO||','||
	CODUNICOCLIBENEFICIARIO||','||
	NOMBREBENEFICIARIO||','||
	CODDEPARTAMENTO
FROM TMP_TRX_EPIC019_4
WHERE CODCLAVECICSOLICITANTE = :CODCLAVECIC ;

SPOOL OFF;