@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--Lista de clientes por departamento que tuvieron depositos o no y si fue en un departamento zaed o no
TRUNCATE table TMP_BASETOP_DOLAUX3_1;
INSERT INTO TMP_BASETOP_DOLAUX3_1
--CREATE TABLE TMP_BASETOP_DOLAUX3_1 AS
select periodo, 'BEN' AS TIPO,A.CODDEPARTAMENTO,A.codigo_cliente,A.ROW_NUM,
	case when f.zaed='No'  then 0	else 1 end flgZAED,
	 A.MTODEPOCTA,A.OTROMTO,A.TOTAL
FROM (
      SELECT extract(year from g.fecdia)*100+extract(month from g.fecdia) as periodo, g.CODUNICOCLIBENEFICIARIO codigo_cliente,TRIM(C.CODDEPARTAMENTO) CODDEPARTAMENTO,
        row_number () OVER (PARTITION BY C.CODDEPARTAMENTO ORDER BY SUM(MTOTRANSACCIONCTA) DESC) ROW_NUM,
    		SUM(CASE WHEN g.CODTRANSACCIONVENTANILLA IN (59,60,61,62,63,64,113,114,115,116,117) THEN g.MTOTRANSACCIONCTA ELSE 0 END) MTODEPOCTA,
    		SUM(CASE WHEN g.CODTRANSACCIONVENTANILLA not IN (59,60,61,62,63,64,113,114,115,116,117) THEN g.MTOTRANSACCIONCTA ELSE 0 END) OTROMTO,
    		SUM(MTOTRANSACCIONCTA) TOTAL
    	FROM T23377.qry_efectparticipe g
    		LEFT JOIN ODS_V.MD_CLIENTE A ON G.CODUNICOCLIBENEFICIARIO=A.CODUNICOCLI AND A.FLGREGELIMINADO='N'
        inner join ods_v.md_agencia B on trim(G.CODSUCAGE)=trim(B.CODSUCAGE)
        inner join ods_v.mm_distrito C on trim(B.CODDISTRITO)=trim(C.CODDISTRITO)
    	where g.CODUNICOCLIBENEFICIARIO not in ('.','0000000000001','0000000000006') AND A.TIPBANCA NOT IN ('C','E')
    		and g.fecdia between TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') and TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
    	GROUP BY extract(year from g.fecdia)*100+extract(month from g.fecdia), g.CODUNICOCLIBENEFICIARIO,C.CODDEPARTAMENTO
) A
inner join T23377.efe_dimdepartamento f on trim(A.coddepartamento)=trim(f.coddepartamento)
--WHERE (A.ROW_NUM<=20 AND F.ZAED<>'No') or (A.ROW_NUM<=10 AND F.ZAED='No')
UNION
select periodo,'SOL' AS TIPO,A.CODDEPARTAMENTO,A.codigo_cliente,A.ROW_NUM,
	case when f.zaed='No'  then 0	else 1 end flgZAED,
	A.MTODEPOCTA,A.OTROMTO,A.TOTAL
FROM (
      SELECT extract(year from g.fecdia)*100+extract(month from g.fecdia) as periodo, g.CODUNICOCLISOLICITANTE codigo_cliente,TRIM(C.CODDEPARTAMENTO) CODDEPARTAMENTO,
        row_number () OVER (PARTITION BY C.CODDEPARTAMENTO ORDER BY SUM(MTOTRANSACCIONCTA) DESC) ROW_NUM,
    		SUM(CASE WHEN g.CODTRANSACCIONVENTANILLA IN (59,60,61,62,63,64,113,114,115,116,117) THEN g.MTOTRANSACCIONCTA ELSE 0 END) MTODEPOCTA,
    		SUM(CASE WHEN g.CODTRANSACCIONVENTANILLA not IN (59,60,61,62,63,64,113,114,115,116,117) THEN g.MTOTRANSACCIONCTA ELSE 0 END) OTROMTO,
    		SUM(MTOTRANSACCIONCTA) TOTAL
    	FROM T23377.qry_efectparticipe g
    		LEFT JOIN ODS_V.MD_CLIENTE A ON G.CODUNICOCLISOLICITANTE=A.CODUNICOCLI AND A.FLGREGELIMINADO='N'
        inner join ods_v.md_agencia B on trim(G.CODSUCAGE)=trim(B.CODSUCAGE)
        inner join ods_v.mm_distrito C on trim(B.CODDISTRITO)=trim(C.CODDISTRITO)
    	where g.CODUNICOCLISOLICITANTE not in ('.','0000000000001','0000000000006') AND A.TIPBANCA NOT IN ('C','E')
    		and g.fecdia between TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') and TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
    	GROUP BY extract(year from g.fecdia)*100+extract(month from g.fecdia), g.CODUNICOCLISOLICITANTE,C.CODDEPARTAMENTO
) A
inner join T23377.efe_dimdepartamento f on trim(A.coddepartamento)=trim(f.coddepartamento);

--Trxs que realizaron los clientes de la tabla anterior en un departamento
TRUNCATE table TMP_BASETOP_DOLAUX2_1;
INSERT INTO TMP_BASETOP_DOLAUX2_1
--CREATE TABLE TMP_BASETOP_DOLAUX2_1 AS
SELECT D.TIPO,A.FECDIA,A.CODSUCAGE,A.CODSESION,A.HORINITRANSACCION,E.DESTRANSACCIONVENTANILLA,A.CODMONEDACTA,
       A.MTOTRANSACCIONCTA,A.CODMONEDATRANSACCION,A.MTOTRANSACCION,A.CODCLAVEOPECTA,A.CODCLAVEOPECTADESTINO,
       A.NUMCHEQUE,A.CODUNICOCLISOLICITANTE,A.CODUNICOCLIBENEFICIARIO,A.PERIODO,D.CODIGO_CLIENTE,F.NBRCLIENTE,
       D.MTODEPOCTA,D.OTROMTO,D.TOTAL, d.flgzaed
FROM T23377.qry_efectparticipe a
     inner join ods_v.md_agencia B on TRIM(A.CODSUCAGE)=TRIM(B.CODSUCAGE)
     inner join ods_v.mm_distrito C on TRIM(B.CODDISTRITO)=TRIM(C.CODDISTRITO)
     INNER JOIN TMP_BASETOP_DOLAUX3_1 D ON A.CODUNICOCLIBENEFICIARIO=D.CODIGO_CLIENTE AND TRIM(C.CODDEPARTAMENTO)=D.CODDEPARTAMENTO and a.periodo = d.periodo
     LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA E ON A.CODTRANSACCIONVENTANILLA=E.CODTRANSACCIONVENTANILLA
     LEFT JOIN T23377.EFE_DIMCLIENTE F ON D.CODIGO_CLIENTE=F.CODUNICOCLI
WHERE D.TIPO='BEN'
UNION
SELECT D.TIPO,A.FECDIA,A.CODSUCAGE,A.CODSESION,A.HORINITRANSACCION,E.DESTRANSACCIONVENTANILLA,A.CODMONEDACTA,
       A.MTOTRANSACCIONCTA,A.CODMONEDATRANSACCION,A.MTOTRANSACCION,A.CODCLAVEOPECTA,A.CODCLAVEOPECTADESTINO,
       A.NUMCHEQUE,A.CODUNICOCLISOLICITANTE,A.CODUNICOCLIBENEFICIARIO,A.PERIODO,D.CODIGO_CLIENTE,F.NBRCLIENTE,
       D.MTODEPOCTA,D.OTROMTO,D.TOTAL, d.flgzaed
FROM T23377.qry_efectparticipe a
     inner join ods_v.md_agencia B on TRIM(A.CODSUCAGE)=TRIM(B.CODSUCAGE)
     inner join ods_v.mm_distrito C on TRIM(B.CODDISTRITO)=TRIM(C.CODDISTRITO)
     INNER JOIN TMP_BASETOP_DOLAUX3_1 D ON A.CODUNICOCLISOLICITANTE=D.CODIGO_CLIENTE AND TRIM(C.CODDEPARTAMENTO)=D.CODDEPARTAMENTO and a.periodo =  d.periodo
     LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA E ON A.CODTRANSACCIONVENTANILLA=E.CODTRANSACCIONVENTANILLA
     LEFT JOIN T23377.EFE_DIMCLIENTE F ON D.CODIGO_CLIENTE=F.CODUNICOCLI
WHERE D.TIPO='SOL';

----------RELACIONADOS---------
--Extrae la lista de relacionados de los clientes, a nivel cliente
TRUNCATE table TMP_BASETOP_DOLAUX1_1;
INSERT INTO TMP_BASETOP_DOLAUX1_1
--CREATE TABLE TMP_BASETOP_DOLAUX1_1 AS
WITH TEMP AS (
  SELECT A.CODIGO_CLIENTE,
  	row_number () OVER (PARTITION BY A.CODIGO_CLIENTE ORDER BY C.CODREL DESC) ROW_NUM,
  	CASE WHEN G.NBRCLIENTE IS NULL THEN TRIM(F.APEPATCLI)||' '||TRIM(F.APEMATCLI)||' '||TRIM(F.NBRCLI) ELSE TRIM(G.NBRCLIENTE) END NBRCLIENTE,
  	D.DESCODTIPREL,E.DESCODREL
  FROM (SELECT DISTINCT CODIGO_CLIENTE FROM TMP_BASETOP_DOLAUX3_1) A
  	LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODIGO_CLIENTE=B.CODUNICOCLI AND B.FLGREGELIMINADO='N'
  	LEFT JOIN ODS_V.MD_RELACIONCLIENTE C ON B.CODCLAVECIC=C.CODCLAVECIC AND C.FLGVIGENCIAREL='S'
  	LEFT JOIN ODS_V.MM_DESCODTIPORELACIONCLIENTE D ON C.CODTIPREL=D.CODTIPREL
  	LEFT JOIN ODS_V.MM_DESCODIGORELACIONCLIENTE E ON C.CODREL=E.CODREL
  	LEFT JOIN ODS_V.MD_CLIENTE F ON C.CODCLAVECICCLIREL=F.CODCLAVECIC AND F.FLGREGELIMINADO='N'
  	LEFT JOIN T23377.EFE_DIMCLIENTE G ON F.CODUNICOCLI=G.CODUNICOCLI
  WHERE C.CODTIPREL IN ('AC','PA','CY') OR C.CODREL IN ('APD','RLG') OR C.CODREL LIKE 'G%'
)
SELECT A.CODIGO_CLIENTE,
	LISTAGG(ROW_NUM||' '||A.NBRCLIENTE, '||') WITHIN GROUP (ORDER BY A.CODIGO_CLIENTE) NBRCLIENTE_REL,
	LISTAGG(ROW_NUM||' '||A.DESCODTIPREL||' '||A.DESCODREL, '||') WITHIN GROUP (ORDER BY A.CODIGO_CLIENTE) CARGO_REL
FROM TEMP A
WHERE A.ROW_NUM<=4
GROUP BY A.CODIGO_CLIENTE;

TRUNCATE table TMP_BASETOP_DOLAUX_1;
INSERT INTO TMP_BASETOP_DOLAUX_1
--CREATE TABLE TMP_BASETOP_DOLAUX_1 AS
with temp as(
  select a.CODIGO_CLIENTE,
  	sum(CASE WHEN C.CODSISTEMAORIGEN='IMP' or C.CODSISTEMAORIGEN='SAV' THEN 1 ELSE 0 END) CTAPASIVA,
  	sum(CASE WHEN C.CODSISTEMAORIGEN='VP' or C.CODSISTEMAORIGEN='ALS' THEN 1 ELSE 0 END) CTAACTIVA
  from (SELECT DISTINCT CODIGO_CLIENTE FROM TMP_BASETOP_DOLAUX3_1) a
       left join ODS_V.MD_CLIENTE b on a.CODIGO_CLIENTE=b.CODUNICOCLI
       left join ODS_V.UM_RESUMENSALDO C on b.CODCLAVECIC=c.CODCLAVECIC
  GROUP BY a.CODIGO_CLIENTE
)
select DISTINCT
  a.periodo,
  CASE WHEN D.NBRCLIENTE IS NULL THEN TRIM(B.APEPATCLI)||' '||TRIM(B.APEMATCLI)||' '||TRIM(B.NBRCLI) ELSE TRIM(D.NBRCLIENTE) END NBRCLIENTE,
	A.CODIGO_CLIENTE,
	A.BENEFICIARIO,
	A.SOLICITANTE,
	A.CODDEPARTAMENTO, a.flgzaed, C.CODPAISNACIONALIDAD,
	case when h.FECCONSTITUCION is not null then h.FECCONSTITUCION else c.FECNACIMIENTO end FECNACIMIENTO,
	C.CODPROFESION,B.CODACTECONOMICA,B.CODSUBSEGMENTO,B.CODSECTORISTA, case when b.codsectorista iN (null, '.', 'BEX000','BEX001','U000001','U000002','U000003','U000004','U000005','U000006','U000007','U000008','U000009')	 then 0 else 1 end as FLGFFNN,
	I.NBRCLIENTE_REL,I.CARGO_REL,
	CASE WHEN F2.CODCLAVECIC IS NOT NULL THEN 'Si' ELSE 'No' END AN_Cumplimiento,
	CASE WHEN G.CTAPASIVA>=1 THEN 'Si' else 'No' end Cuenta_pasiva,
	CASE WHEN G.CTAACTIVA>=1 THEN 'Si' else 'No' end Cuenta_activa
from (
      SELECT a.periodo,A.CODIGO_CLIENTE,A.CODDEPARTAMENTO, a.flgzaed , MAX(CASE WHEN A.TIPO='BEN' THEN A.TOTAL ELSE 0 END) BENEFICIARIO,
	            MAX(CASE WHEN A.TIPO='SOL' THEN A.TOTAL ELSE 0 END) SOLICITANTE
      FROM TMP_BASETOP_DOLAUX3_1 A GROUP BY a.periodo,A.CODIGO_CLIENTE,A.CODDEPARTAMENTO, a.flgzaed 
) A
left join ods_v.md_cliente b on a.CODIGO_CLIENTE=trim(b.CODUNICOCLI) AND b.FLGREGELIMINADO='N'
left join ods_v.md_personanatural c on b.CODCLAVECIC=c.CODCLAVECIC
LEFT JOIN T23377.EFE_DIMCLIENTE D ON A.CODIGO_CLIENTE=D.CODUNICOCLI
left join ods_v.md_clientenegativo f1 on b.codclavecic = f1.codclavecic and f1.TIPESTCLINEGATIVO <> 'H'
left join ods_v.md_motivodetalleclinegativo f2 on f1.codclavecic = f2.codclavecic and f2.TIPMOTIVONEGATIVO = '013'
left join temp G ON A.CODIGO_CLIENTE=G.CODIGO_CLIENTE
left join ods_v.mm_empresa h ON b.CODCLAVECIC=h.CODCLAVECIC
LEFT JOIN TMP_BASETOP_DOLAUX1_1 I ON A.CODIGO_CLIENTE=I.CODIGO_CLIENTE;

TRUNCATE table TMP_BASETOP_DOL_1;
INSERT INTO TMP_BASETOP_DOL_1
--CREATE TABLE TMP_BASETOP_DOL_1 AS
WITH TEMP AS (
	SELECT A.CODIGO_CLIENTE,
		MAX(CASE WHEN A.TIPO='INV' THEN A.f_Fin||' - '||RESULTADO ELSE NULL END )FEC_INV,
		MAX(CASE WHEN A.TIPO='INV' THEN B.NBRORIGEN ELSE NULL END )ORIGEN_INV,
		MAX(CASE WHEN A.TIPO='EVA' THEN A.f_Fin||' - '||RESULTADO ELSE NULL END )FEC_EVA,
		MAX(CASE WHEN A.TIPO='EVA' THEN B.NBRORIGEN ELSE NULL END) ORIGEN_EVA
		FROM ( 
          SELECT 'INV' TIPO,A.CODIGO_CLIENTE,B.IDCASO,C.FECFININV AS f_Fin,C.NOMRESULTADOSUPERVISOR RESULTADO,
      			row_number () OVER (PARTITION BY B.CODUNICOCLI ORDER BY C.FECFININV DESC) ROW_NUM
      		FROM (SELECT DISTINCT CODIGO_CLIENTE FROM TMP_BASETOP_DOLAUX3_1) A
      		LEFT JOIN S61751.SAPY_DMCASO B ON A.CODIGO_CLIENTE=B.CODUNICOCLI
			LEFT JOIN S61751.SAPY_DMINVESTIGACION C ON B.IDCASO = C.IDCASO
      		WHERE C.FECFININV IS NOT NULL AND B.NBREMPRESA='BCP' AND C.IDRESULTADOSUPERVISOR IN (1,2)
      		UNION
      		SELECT 'EVA' TIPO, A.CODIGO_CLIENTE,B.IDCASO,C.FECFINEVAL f_Fin,C.NOMRESULTADO RESULTADO,
      		   row_number () OVER (PARTITION BY B.CODUNICOCLI ORDER BY C.FECFINEVAL DESC) ROW_NUM
      		FROM (SELECT DISTINCT CODIGO_CLIENTE FROM TMP_BASETOP_DOLAUX3_1) A
      		LEFT JOIN S61751.SAPY_DMCASO B ON A.CODIGO_CLIENTE=B.CODUNICOCLI
      		LEFT JOIN S61751.SAPY_DMEVALUACION C ON B.IDCASO = C.IDCASO
      		WHERE C.FECFINEVAL IS NOT NULL AND B.NBREMPRESA='BCP' AND C.IDRESULTADO=6
    ) A
		LEFT JOIN S61751.SAPY_DMALERTA B ON A.IDCASO=B.IDCASO WHERE A.ROW_NUM=1 GROUP BY A.CODIGO_CLIENTE
)
SELECT a.periodo,A.NBRCLIENTE,A.CODIGO_CLIENTE,a.coddepartamento,TRIM(C.NBRUBICACION) NBRUBICACION,a.flgzaed,A.BENEFICIARIO,A.SOLICITANTE,TO_NUMBER(A.BENEFICIARIO)+TO_NUMBER(A.SOLICITANTE) TOTAL,
G.DESCODPAISNACIONALIDAD NACIONALIDAD,
CASE WHEN a.flgzaed=0 AND a.coddepartamento=30 THEN 1
WHEN a.flgzaed=1 THEN 2 ELSE 0 END CATFLGZAED,
CASE WHEN G.DESCODPAISNACIONALIDAD IN ('VENEZUELA','ECUADOR','COLOMBIA') THEN 3
WHEN G.DESCODPAISNACIONALIDAD IS NULL OR G.DESCODPAISNACIONALIDAD='NO DIO INFORMACION' OR G.DESCODPAISNACIONALIDAD='.'  THEN 2
WHEN G.DESCODPAISNACIONALIDAD='PERU' THEN 1 ELSE 0 END CATNACIONAL,
CASE WHEN L.DESSEGMENTO IN ('CONSUMO','PEQ. EMPRESA','NO BANCO') THEN 3
WHEN L.DESSEGMENTO IN ('EXCLUSIVO','NEGOCIOS') THEN 2
WHEN L.DESSEGMENTO IN ('ENALTA','INSTITUCIONES','PRIVADA') THEN 1 ELSE 1 END CATSEGMENTO,
CASE WHEN TRIM(H.DESCODPROFESION) IN ('AMA DE CASA','VARIOS','ESTUDIANTE','VENDEDOR AMBULANTE','COMERCIANTE / VENDEDOR','SECRETARIA, RECEPCIONISTA, TELEFONISTA','CONDUCTOR, CHOFER / TAXISTA','COSMETOLOGO, PELUQUERO Y BARBERO',
'OBRERO / OPERADOR','COCINERO / CHEF','JUBILADO, PENSIONISTA','ALBA¿IL, OBRERO DE CONSTRUCCION','PINTOR','CARPINTERO','PELUQUERO','COCINERO','CAMBISTA','MASAJISTA','PANADERO / PASTELERO','COBRADOR','CONSERJE / PORTERO') THEN 1
WHEN H.DESCODPROFESION LIKE '%TEC %' OR TRIM(H.DESCODPROFESION) = 'TECNICO' THEN 1
WHEN H.DESCODPROFESION IS NULL OR TRIM(H.DESCODPROFESION)='NO DIO INFORMACION SOLICITADA' THEN 2
ELSE 3 END CATPROFESION,
A.FECNACIMIENTO,
TRUNC(MONTHS_BETWEEN(sysdate, A.FECNACIMIENTO)/12) AS EDAD
,TRIM(H.DESCODPROFESION) PROFESION,TRIM(I.DESACTECONOMICA) CIIU,
TRIM(L.DESSEGMENTO) SEGMENTO,A.CODSECTORISTA FFNN,A.FLGFFNN,A.NBRCLIENTE_REL,A.CARGO_REL,A.AN_Cumplimiento,A.Cuenta_pasiva,A.Cuenta_activa,
B.FEC_INV,B.ORIGEN_INV,B.FEC_EVA,B.ORIGEN_EVA
FROM TMP_BASETOP_DOLAUX_1 A
LEFT JOIN temp B ON A.CODIGO_CLIENTE=B.CODIGO_CLIENTE
LEFT JOIN T23377.EFE_DIMDEPARTAMENTO C ON A.CODDEPARTAMENTO=TRIM(C.CODDEPARTAMENTO)
LEFT JOIN ODS_V.MM_DESCODIGOPAISNACIONALIDAD G ON A.CODPAISNACIONALIDAD=G.CODPAISNACIONALIDAD
LEFT JOIN ODS_V.MM_DESCODIGOPROFESION H ON A.CODPROFESION=H.CODPROFESION
LEFT JOIN ODS_V.MM_DESCODACTIVIDADECONOMICA I ON A.CODACTECONOMICA=I.CODACTECONOMICA
LEFT JOIN ODS_V.mm_descodigosubsegmento J ON A.CODSUBSEGMENTO=J.CODSUBSEGMENTO
LEFT JOIN ODS_V.Mm_Descodsubseggen K ON J.CODSUBSEGGENERAL=K.CODSUBSEGGENERAL
LEFT JOIN ODS_V.mm_descodigosegmento L ON TRIM(K.CODSEGMENTO)=TRIM(L.CODSEGMENTO)
left join T23377.efe_dimdepartamento z on trim(A.coddepartamento)=trim(z.coddepartamento);

COMMIT;
SPOOL OFF
QUIT;