--PARAMETRO DE CREDENCIALES
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

--EXTRACCION DE LOS SEGMENTOS DE BANCA
--DROP TABLE TMP_ESCPEP_SEGMENTOBANCA;
--CREATE TABLE TMP_ESCPEP_SEGMENTOBANCA TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_SEGMENTOBANCA;
INSERT INTO TMP_ESCPEP_SEGMENTOBANCA
SELECT DISTINCT SUBSEG.CODSUBSEGMENTO, SUBSEG.DESSUBSEGMENTO, SEG.CODSEGMENTO, SEG.DESSEGMENTO
FROM ODS_V.MM_DESCODIGOSUBSEGMENTO SUBSEG
LEFT JOIN ODS_V.MM_DESCODSUBSEGGEN SUBSEGGEN ON TRIM(SUBSEG.CODSUBSEGGENERAL)=TRIM(SUBSEGGEN.CODSUBSEGGENERAL)
LEFT JOIN ODS_V.MM_DESCODIGOSEGMENTO SEG ON TRIM(SUBSEGGEN.CODSEGMENTO)=TRIM(SEG.CODSEGMENTO);

--EXTRACCION DEL UNIVERSO DE PEPS
--DROP TABLE TMP_ESCPEP_UNIVERSO;
--CREATE TABLE TMP_ESCPEP_UNIVERSO TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_UNIVERSO;
INSERT INTO TMP_ESCPEP_UNIVERSO
SELECT DISTINCT A.CODCLAVECIC, A.TIPPER, E.DESTIPPER, A.TIPCLI, D.DESTIPCLI, A.CODSECTORISTA, A.TIPBANCA, C.DESTIPBANCA,
A.CODACTECONOMICA, F.DESACTECONOMICA, A.CODSUBSEGMENTO, G.DESSUBSEGMENTO, G.CODSEGMENTO, G.DESSEGMENTO, A.TIPMARCACLI, B.DESTIPMARCACLI, A.FLGREGELIMINADO
FROM ODS_V.MD_CLIENTEG94 A
LEFT JOIN ODS_V.MM_DESTIPMARCACLIENTE B ON A.TIPMARCACLI = B.TIPMARCACLI
LEFT JOIN ODS_V.MM_DESTIPOBANCA C ON A.TIPBANCA = C.TIPBANCA
LEFT JOIN ODS_V.MM_DESTIPOCLIENTE D ON A.TIPCLI = D.TIPCLI
LEFT JOIN ODS_V.MM_DESTIPOPERSONA E ON A.TIPPER = E.TIPPER
LEFT JOIN ODS_V.MM_DESCODACTIVIDADECONOMICA F ON A.CODACTECONOMICA = F.CODACTECONOMICA
LEFT JOIN TMP_ESCPEP_SEGMENTOBANCA G ON A.CODSUBSEGMENTO = G.CODSUBSEGMENTO
WHERE A.TIPMARCACLI IN ('P') AND A.FLGREGELIMINADO = 'N'
--SE EXCLUYEN LOS TIPOS DE CLIENTES NO CLIENTE, CLIENTE DUPLICADO, CLIENTE EXTERNO Y CLIENTE FALLECIDO
AND A.TIPCLI NOT IN ('NC','CD','CE','CF')
--SE EXCLUYE EL SEGMENTO NO BANCO
AND TRIM(G.CODSEGMENTO) NOT IN ('SN');

SPOOL OFF
QUIT;