--PARAMETRO DE CREDENCIALES
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);


SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--DROP TABLE TMP_ESCPEP_CUENTAS_PEP;
--CREATE TABLE TMP_ESCPEP_CUENTAS_PEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_CUENTAS_PEP;
INSERT INTO TMP_ESCPEP_CUENTAS_PEP
SELECT A.CODCLAVECIC, B.CODCLAVEOPECTA, TRIM(B.CODOPECTA) AS CODOPECTA
FROM TMP_ESCPEP_UNIVERSO A
INNER JOIN ODS_V.MD_CUENTAG94 B ON A.CODCLAVECIC = B.CODCLAVECIC
WHERE B.FLGREGELIMINADO = 'N' AND TRIM(CODSISTEMAORIGEN) IN ('BAN','IMP','SAV','RT','GT');

--EXTRAER CODCLAVECICS DEL UNIVERSO DE PEPS

--DROP TABLE TMP_ESCPEP_CODCLAVECICS_PEP;
--CREATE TABLE TMP_ESCPEP_CODCLAVECICS_PEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_CODCLAVECICS_PEP;
INSERT INTO TMP_ESCPEP_CODCLAVECICS_PEP
SELECT DISTINCT CODCLAVECIC
FROM TMP_ESCPEP_UNIVERSO;

--EXTRACCION DE TRXS EN CANAL AGENTE
---EXTRACCION DE PEP-INT
--EXTRACCION EN AGENTE - TRAN

--DROP TABLE TMP_ESCPEP_TRX_AGE_PEP_INT_TRAN;
--CREATE TABLE TMP_ESCPEP_TRX_AGE_PEP_INT_TRAN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_AGE_PEP_INT_TRAN;
INSERT INTO TMP_ESCPEP_TRX_AGE_PEP_INT_TRAN
SELECT DISTINCT A.NUMREGISTRO, A.FECDIA, A.HORTRANSACCION,A.TIPTRANSACCIONAGENTEVIABCP, A.TIPESTTRANSACCIONAGENTEVIABCP, A.CODMONEDA, A.MTOTRANSACCION, A.CODCLAVECIC, A.CODCLAVEOPECTACARGO, A.CODCLAVEOPECTAABONO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM T23377.TMP_MOVAGENTE_i A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTACARGO = B.CODCLAVEOPECTA
WHERE  A.TIPTRANSACCIONAGENTEVIABCP IN ('03') AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
union all
SELECT DISTINCT A.NUMREGISTRO, A.FECDIA, A.HORTRANSACCION,A.TIPTRANSACCIONAGENTEVIABCP, A.TIPESTTRANSACCIONAGENTEVIABCP, A.CODMONEDA, A.MTOTRANSACCION, A.CODCLAVECIC, A.CODCLAVEOPECTACARGO, A.CODCLAVEOPECTAABONO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM T23377.TMP_MOVAGENTE_p A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTACARGO = B.CODCLAVEOPECTA
WHERE  A.TIPTRANSACCIONAGENTEVIABCP IN ('03') AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

--EXTRACCION EN AGENTE - DEP;

--DROP TABLE TMP_ESCPEP_TRX_AGE_PEP_INT_DEP;
--CREATE TABLE TMP_ESCPEP_TRX_AGE_PEP_INT_DEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_AGE_PEP_INT_DEP;
INSERT INTO TMP_ESCPEP_TRX_AGE_PEP_INT_DEP
SELECT DISTINCT A.NUMREGISTRO, A.FECDIA, A.HORTRANSACCION,A.TIPTRANSACCIONAGENTEVIABCP, A.TIPESTTRANSACCIONAGENTEVIABCP, A.CODMONEDA, A.MTOTRANSACCION, A.CODCLAVECIC, A.CODCLAVEOPECTACARGO, A.CODCLAVEOPECTAABONO ,
C.CODCLAVECIC AS CODCLAVECICPEP
FROM T23377.TMP_MOVAGENTE_i A
INNER JOIN ODS_V.MD_CLIENTEG94 B ON TRIM(A.CODUNICOCLI) = TRIM(B.CODUNICOCLI)
INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP C ON B.CODCLAVECIC = C.CODCLAVECIC
WHERE  A.TIPTRANSACCIONAGENTEVIABCP IN ('05') AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
union all
SELECT DISTINCT A.NUMREGISTRO, A.FECDIA, A.HORTRANSACCION,A.TIPTRANSACCIONAGENTEVIABCP, A.TIPESTTRANSACCIONAGENTEVIABCP, A.CODMONEDA, A.MTOTRANSACCION, A.CODCLAVECIC, A.CODCLAVEOPECTACARGO, A.CODCLAVEOPECTAABONO ,
C.CODCLAVECIC AS CODCLAVECICPEP
FROM T23377.TMP_MOVAGENTE_p A
INNER JOIN ODS_V.MD_CLIENTEG94 B ON TRIM(A.CODUNICOCLI) = TRIM(B.CODUNICOCLI)
INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP C ON B.CODCLAVECIC = C.CODCLAVECIC
WHERE  A.TIPTRANSACCIONAGENTEVIABCP IN ('05') AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

---EXTRACCION DE INT-PEP

--EXTRACCION EN AGENTE - TRANYDEP;

--DROP TABLE TMP_ESCPEP_TRX_AGE_INT_PEP_TRANDEP;
--CREATE TABLE TMP_ESCPEP_TRX_AGE_INT_PEP_TRANDEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_AGE_INT_PEP_TRANDEP;
INSERT INTO TMP_ESCPEP_TRX_AGE_INT_PEP_TRANDEP
SELECT DISTINCT A.NUMREGISTRO, A.FECDIA, A.HORTRANSACCION,A.TIPTRANSACCIONAGENTEVIABCP, A.TIPESTTRANSACCIONAGENTEVIABCP, A.CODMONEDA, A.MTOTRANSACCION, A.CODCLAVECIC, C.CODCLAVECIC AS CODCLAVECICG94, A.CODCLAVEOPECTACARGO, A.CODCLAVEOPECTAABONO ,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM T23377.TMP_MOVAGENTE_i A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTAABONO = B.CODCLAVEOPECTA
LEFT JOIN ODS_V.MD_CLIENTEG94 C ON TRIM(A.CODUNICOCLI) = TRIM(C.CODUNICOCLI)
WHERE  A.TIPTRANSACCIONAGENTEVIABCP IN ('03','05') AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
union all
SELECT DISTINCT A.NUMREGISTRO, A.FECDIA, A.HORTRANSACCION,A.TIPTRANSACCIONAGENTEVIABCP, A.TIPESTTRANSACCIONAGENTEVIABCP, A.CODMONEDA, A.MTOTRANSACCION, A.CODCLAVECIC, C.CODCLAVECIC AS CODCLAVECICG94, A.CODCLAVEOPECTACARGO, A.CODCLAVEOPECTAABONO ,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM T23377.TMP_MOVAGENTE_p A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTAABONO = B.CODCLAVEOPECTA
LEFT JOIN ODS_V.MD_CLIENTEG94 C ON TRIM(A.CODUNICOCLI) = TRIM(C.CODUNICOCLI)
WHERE  A.TIPTRANSACCIONAGENTEVIABCP IN ('03','05') AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

--poblando auxiliares:
CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_01 AS
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
		A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, TRIM(A.CODOPECTAHACIA) AS CODOPECTAHACIA, TRIM(A.CODOPECTADESDE) AS CODOPECTADESDE
	FROM  ODS_V.HD_MOVIMIENTOCAJERO A
	WHERE
		A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -2 ),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -1))) AND
		CODTRANCAJERO = '40' AND FLGVALIDA = 'S';	
		
CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_02 AS
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
		A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, TRIM(A.CODOPECTAHACIA) AS CODOPECTAHACIA, TRIM(A.CODOPECTADESDE) AS CODOPECTADESDE
	FROM  ODS_V.HD_MOVIMIENTOCAJERO A
	WHERE
		A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -4),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -3))) AND
		CODTRANCAJERO = '40' AND FLGVALIDA = 'S';

CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_03 AS
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
		A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, TRIM(A.CODOPECTAHACIA) AS CODOPECTAHACIA, TRIM(A.CODOPECTADESDE) AS CODOPECTADESDE
	FROM  ODS_V.HD_MOVIMIENTOCAJERO A
	WHERE
		A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -7),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -5))) AND
		CODTRANCAJERO = '40' AND FLGVALIDA = 'S';


--DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1;
--CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1;
INSERT INTO TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1
SELECT * FROM TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_01
UNION ALL 		
SELECT * FROM TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_02
UNION ALL
SELECT * FROM TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_03;

DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_01;
DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_02;
DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1_AUX_03;

--CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_2 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_2;
INSERT INTO TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_2
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
		A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, C.CODCLAVEOPECTA AS CODCLAVEOPECTADESDE,
		C.CODCLAVECIC AS CODCLAVECICPEP, C.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP, CODOPECTAHACIA
	FROM  TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_1 A
		INNER JOIN TMP_ESCPEP_CUENTAS_PEP C ON TRIM(A.CODOPECTADESDE) = C.CODOPECTA	;

--CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN AS
TRUNCATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN;
INSERT INTO TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN
SELECT DISTINCT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
	A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, A.CODCLAVEOPECTADESDE, D.CODCLAVEOPECTA AS CODCLAVEOPECTAHACIA,
	A.CODCLAVECICPEP, A.CODCLAVEOPECTAPEP
FROM TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN_2 A
	LEFT JOIN ODS_V.MD_CUENTAG94 D ON TRIM(A.CODOPECTAHACIA) = TRIM(D.CODOPECTA);

--EXTRACCION EN CAJERO - DEP;
CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_01 AS
SELECT DISTINCT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN, A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME,-1 AS CODCLAVEOPECTADESDE, D.CODCLAVEOPECTA AS CODCLAVEOPECTAHACIA,
B.CODCLAVECIC AS CODCLAVECICPEP
FROM  ODS_V.HD_MOVIMIENTOCAJERO A
INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP B ON A.CODCLAVECIC = B.CODCLAVECIC
INNER JOIN ODS_V.MD_CUENTAG94 D ON TRIM(A.CODOPECTAHACIA) = TRIM(D.CODOPECTA)
WHERE CODTRANCAJERO IN ('20') AND FLGVALIDA = 'S' AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -2),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-1)));

CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_02 AS
SELECT DISTINCT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN, A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME,-1 AS CODCLAVEOPECTADESDE, D.CODCLAVEOPECTA AS CODCLAVEOPECTAHACIA,
B.CODCLAVECIC AS CODCLAVECICPEP
FROM  ODS_V.HD_MOVIMIENTOCAJERO A
INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP B ON A.CODCLAVECIC = B.CODCLAVECIC
INNER JOIN ODS_V.MD_CUENTAG94 D ON TRIM(A.CODOPECTAHACIA) = TRIM(D.CODOPECTA)
WHERE CODTRANCAJERO IN ('20') AND FLGVALIDA = 'S' AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -4),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-3)));

CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_03 AS
SELECT DISTINCT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN, A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME,-1 AS CODCLAVEOPECTADESDE, D.CODCLAVEOPECTA AS CODCLAVEOPECTAHACIA,
B.CODCLAVECIC AS CODCLAVECICPEP
FROM  ODS_V.HD_MOVIMIENTOCAJERO A
INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP B ON A.CODCLAVECIC = B.CODCLAVECIC
INNER JOIN ODS_V.MD_CUENTAG94 D ON TRIM(A.CODOPECTAHACIA) = TRIM(D.CODOPECTA)
WHERE CODTRANCAJERO IN ('20') AND FLGVALIDA = 'S' AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -7),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-5)));

--DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP;
--CREATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP AS
TRUNCATE TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP;
INSERT INTO TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP
SELECT * FROM TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_01
UNION ALL
SELECT * FROM TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_02
UNION ALL
SELECT * FROM TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_03;

DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_01;
DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_02;
DROP TABLE TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP_AUX_03;
	
CREATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_01 AS
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, TRIM(A.CODOPECTADESDE) AS CODOPECTADESDE, TRIM(A.CODOPECTAHACIA) AS CODOPECTAHACIA
FROM  ODS_V.HD_MOVIMIENTOCAJERO A
WHERE A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -2),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-1))) AND 
CODTRANCAJERO IN ('40','20') AND FLGVALIDA = 'S';

CREATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_02 AS
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, TRIM(A.CODOPECTADESDE) AS CODOPECTADESDE, TRIM(A.CODOPECTAHACIA) AS CODOPECTAHACIA
FROM  ODS_V.HD_MOVIMIENTOCAJERO A
WHERE A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -4),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-3))) AND 
CODTRANCAJERO IN ('40','20') AND FLGVALIDA = 'S';

CREATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_03 AS
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, TRIM(A.CODOPECTADESDE) AS CODOPECTADESDE, TRIM(A.CODOPECTAHACIA) AS CODOPECTAHACIA
FROM  ODS_V.HD_MOVIMIENTOCAJERO A
WHERE A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -7),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-5))) AND 
CODTRANCAJERO IN ('40','20') AND FLGVALIDA = 'S';			

--DROP TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1;
--CREATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1 AS 		
TRUNCATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1;
INSERT INTO TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1
SELECT * FROM TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_01
UNION ALL
SELECT * FROM TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_02
UNION ALL
SELECT * FROM TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_03;

DROP TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_01;
DROP TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_02;
DROP TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1_AUX_03;	
				
--CREATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_2 TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_2;
INSERT INTO TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_2
SELECT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
		A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, C.CODCLAVEOPECTA AS CODCLAVEOPECTAHACIA,
		C.CODCLAVECIC AS CODCLAVECICPEP, C.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP, CODOPECTADESDE
FROM TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1 A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP C ON TRIM(A.CODOPECTAHACIA) = C.CODOPECTA;

--CREATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP;
INSERT INTO TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP
SELECT DISTINCT A.NUMREGISTRO, A.CODCAJERO, A.FECDIA, A.HORTRANSACCION, A.CODTRANCAJERO, A.FLGVALIDA, A.CODCLAVECIC, A.CODMONEDATRAN,
	A.MTOTRANSACCIONSOL, A.MTOTRANSACCIONME, D.CODCLAVEOPECTA AS CODCLAVEOPECTADESDE, A.CODCLAVEOPECTAHACIA,
	A.CODCLAVECICPEP, A.CODCLAVEOPECTAPEP
FROM TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_2 A
	LEFT JOIN ODS_V.MD_CUENTAG94 D ON TRIM(A.CODOPECTADESDE) = TRIM(D.CODOPECTA);

DROP TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_1;
DROP TABLE TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP_2;

--EXTRACCION DE TRXS EN CANAL BANCA MOVIL

---EXTRACCION DE PEP-INT

--EXTRACCION EN BANCA MOVIL - TRAN ;

--DROP TABLE TMP_ESCPEP_TRX_BCAMOV_PEP_INT_TRAN;
--CREATE TABLE TMP_ESCPEP_TRX_BCAMOV_PEP_INT_TRAN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_BCAMOV_PEP_INT_TRAN;
INSERT INTO TMP_ESCPEP_TRX_BCAMOV_PEP_INT_TRAN
SELECT DISTINCT A.NUMTRANSACCIONBCAMOVIL,A.FECTRANSACCION, A.HORTRANSACCION,A.FLGTRANSACCIONVALIDA, A.TIPTRANSACCIONBCAMOVIL, A.CODMONEDATRANSACCION, A.MTOTRANSACCION, A.CODCLAVEOPECTAORIGEN, A.CODCLAVEOPECTADESTINO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM  T23377.TMP_MOVBCAMOVIL_i A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTAORIGEN = B.CODCLAVEOPECTA
WHERE TIPTRANSACCIONBCAMOVIL IN (2) and A.FECTRANSACCION BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)))
union all
SELECT DISTINCT A.NUMTRANSACCIONBCAMOVIL,A.FECTRANSACCION, A.HORTRANSACCION,A.FLGTRANSACCIONVALIDA, A.TIPTRANSACCIONBCAMOVIL, A.CODMONEDATRANSACCION, A.MTOTRANSACCION, A.CODCLAVEOPECTAORIGEN, A.CODCLAVEOPECTADESTINO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM  T23377.TMP_MOVBCAMOVIL_p A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTAORIGEN = B.CODCLAVEOPECTA
WHERE TIPTRANSACCIONBCAMOVIL IN (2) and A.FECTRANSACCION BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)));

---EXTRACCION DE INT-PEP

--EXTRACCION EN BANCA MOVIL - TRAN ;

--DROP TABLE TMP_ESCPEP_TRX_BCAMOV_INT_PEP_TRAN;
--CREATE TABLE TMP_ESCPEP_TRX_BCAMOV_INT_PEP_TRAN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_BCAMOV_INT_PEP_TRAN;
INSERT INTO TMP_ESCPEP_TRX_BCAMOV_INT_PEP_TRAN
SELECT DISTINCT A.NUMTRANSACCIONBCAMOVIL,A.FECTRANSACCION, A.HORTRANSACCION,A.FLGTRANSACCIONVALIDA, A.TIPTRANSACCIONBCAMOVIL, A.CODMONEDATRANSACCION, A.MTOTRANSACCION, A.CODCLAVEOPECTAORIGEN, A.CODCLAVEOPECTADESTINO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM  T23377.TMP_MOVBCAMOVIL_i A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTADESTINO = B.CODCLAVEOPECTA
WHERE TIPTRANSACCIONBCAMOVIL IN (2) and A.FECTRANSACCION BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)))
UNION ALL
SELECT DISTINCT A.NUMTRANSACCIONBCAMOVIL,A.FECTRANSACCION, A.HORTRANSACCION,A.FLGTRANSACCIONVALIDA, A.TIPTRANSACCIONBCAMOVIL, A.CODMONEDATRANSACCION, A.MTOTRANSACCION, A.CODCLAVEOPECTAORIGEN, A.CODCLAVEOPECTADESTINO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM  T23377.TMP_MOVBCAMOVIL_p A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTADESTINO = B.CODCLAVEOPECTA
WHERE TIPTRANSACCIONBCAMOVIL IN (2) and A.FECTRANSACCION BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)));

--EXTRACCION DE TRXS EN CANAL HOMEBANKING
---EXTRACCION DE PEP-INT

--DROP TABLE TMP_ESCPEP_TRX_HBK_PEP_INT_TRAN;
--CREATE TABLE TMP_ESCPEP_TRX_HBK_PEP_INT_TRAN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_HBK_PEP_INT_TRAN;
INSERT INTO TMP_ESCPEP_TRX_HBK_PEP_INT_TRAN
SELECT DISTINCT A.CODINTERNOTRANSACCIONHB, A.FECDIA, A.HORTRANSACCION, A.CODOPEHBCTR, A.TIPRESULTADOTRANSACCION, A.MTOTRANSACCION, A.CODMONEDA, C.CODCLAVEOPECTA AS CODCLAVEOPECTAORIGEN, D.CODCLAVEOPECTA AS CODCLAVEOPECTADESTINO,
C.CODCLAVECIC AS CODCLAVECICPEP, C.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM
    ODS_V.HD_MOVHOMEBANKINGTRANSACCION A
    INNER JOIN TMP_ESCPEP_CUENTAS_PEP C ON TRIM(A.CODOPECTAORIGEN) = C.CODOPECTA
    INNER JOIN ODS_V.MD_CUENTAG94 D ON TRIM(A.CODOPECTADESTINO) = TRIM(D.CODOPECTA)
WHERE A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) AND
      A.CODOPEHBCTR IN ('D_TRAN','TRAN_N','TRAN') AND A.TIPRESULTADOTRANSACCION = 'OK';

---EXTRACCION DE INT-PEP

--DROP TABLE TMP_ESCPEP_TRX_HBK_INT_PEP_TRAN;
--CREATE TABLE TMP_ESCPEP_TRX_HBK_INT_PEP_TRAN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_HBK_INT_PEP_TRAN;
INSERT INTO TMP_ESCPEP_TRX_HBK_INT_PEP_TRAN
SELECT DISTINCT A.CODINTERNOTRANSACCIONHB, A.FECDIA, A.HORTRANSACCION, A.CODOPEHBCTR, A.TIPRESULTADOTRANSACCION, A.MTOTRANSACCION, A.CODMONEDA, D.CODCLAVEOPECTA AS CODCLAVEOPECTAORIGEN, C.CODCLAVEOPECTA AS CODCLAVEOPECTADESTINO,
C.CODCLAVECIC AS CODCLAVECICPEP, C.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM
    ODS_V.HD_MOVHOMEBANKINGTRANSACCION A
    INNER JOIN TMP_ESCPEP_CUENTAS_PEP C ON TRIM(A.CODOPECTADESTINO) = C.CODOPECTA
    INNER JOIN ODS_V.MD_CUENTAG94 D ON TRIM(A.CODOPECTAORIGEN) = TRIM(D.CODOPECTA)
WHERE A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) AND
      A.CODOPEHBCTR IN ('D_TRAN','TRAN_N','TRAN') AND A.TIPRESULTADOTRANSACCION = 'OK';

--EXTRACCION DE TRXS EN CANAL VENTANILLA
CREATE TABLE TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_01 AS
SELECT
  A.CODINTERNOTRANSACCION AS NUMREGISTRO,
  A.FECDIA,
  A.HORINITRANSACCION,
  A.HORFINTRANSACCION,
  A.CODSUCAGE,
  A.CODSESION,
  A.CODTRANSACCIONVENTANILLA,
  A.FLGTRANSACCIONAPROBADA,
  A.CODMONEDATRANSACCION AS CODMONEDA,
  CASE WHEN A.MTOTRANSACCIONCTA <> 0 THEN A.MTOTRANSACCIONCTA ELSE A.MTOTRANSACCION END AS MTOTRANSACCION,
  A.CODCLAVEOPECTA,
  A.CODCLAVEOPECTADESTINO
FROM ODS_V.HD_TRANSACCIONVENTANILLA A
WHERE FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -2),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -1))) AND
CODTRANSACCIONVENTANILLA IN (60,62,63,159,186,187,188) AND FLGTRANSACCIONAPROBADA = 'S';


CREATE TABLE TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_02 AS
SELECT
  A.CODINTERNOTRANSACCION AS NUMREGISTRO,
  A.FECDIA,
  A.HORINITRANSACCION,
  A.HORFINTRANSACCION,
  A.CODSUCAGE,
  A.CODSESION,
  A.CODTRANSACCIONVENTANILLA,
  A.FLGTRANSACCIONAPROBADA,
  A.CODMONEDATRANSACCION AS CODMONEDA,
  CASE WHEN A.MTOTRANSACCIONCTA <> 0 THEN A.MTOTRANSACCIONCTA ELSE A.MTOTRANSACCION END AS MTOTRANSACCION,
  A.CODCLAVEOPECTA,
  A.CODCLAVEOPECTADESTINO
FROM ODS_V.HD_TRANSACCIONVENTANILLA A
WHERE FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -4),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -3))) AND
CODTRANSACCIONVENTANILLA IN (60,62,63,159,186,187,188) AND FLGTRANSACCIONAPROBADA = 'S';  
  

CREATE TABLE TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_03 AS
SELECT
  A.CODINTERNOTRANSACCION AS NUMREGISTRO,
  A.FECDIA,
  A.HORINITRANSACCION,
  A.HORFINTRANSACCION,
  A.CODSUCAGE,
  A.CODSESION,
  A.CODTRANSACCIONVENTANILLA,
  A.FLGTRANSACCIONAPROBADA,
  A.CODMONEDATRANSACCION AS CODMONEDA,
  CASE WHEN A.MTOTRANSACCIONCTA <> 0 THEN A.MTOTRANSACCIONCTA ELSE A.MTOTRANSACCION END AS MTOTRANSACCION,
  A.CODCLAVEOPECTA,
  A.CODCLAVEOPECTADESTINO
FROM ODS_V.HD_TRANSACCIONVENTANILLA A
WHERE FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, -7),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -5))) AND
CODTRANSACCIONVENTANILLA IN (60,62,63,159,186,187,188) AND FLGTRANSACCIONAPROBADA = 'S';
 
--DROP TABLE TMP_ESCPEP_TRX_VENTANILLA_INI AS
--CREATE TABLE TMP_ESCPEP_TRX_VENTANILLA_INI AS
TRUNCATE TABLE TMP_ESCPEP_TRX_VENTANILLA_INI;
INSERT INTO TMP_ESCPEP_TRX_VENTANILLA_INI
SELECT * FROM TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_01
UNION ALL
SELECT * FROM TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_02
UNION ALL
SELECT * FROM TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_03;

DROP TABLE TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_01;
DROP TABLE TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_02;
DROP TABLE TMP_ESCPEP_TRX_VENTANILLA_INI_AUX_03;

---EXTRACCION DE PEP-INT

--EXTRACCION DE DEPÓSITOS

--DROP TABLE TMP_ESCPEP_TRX_VENT_PEP_INT_DEP;
--CREATE TABLE TMP_ESCPEP_TRX_VENT_PEP_INT_DEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_VENT_PEP_INT_DEP;
INSERT INTO TMP_ESCPEP_TRX_VENT_PEP_INT_DEP
SELECT DISTINCT
    A.NUMREGISTRO, A.FECDIA, A.HORINITRANSACCION, A.HORFINTRANSACCION, A.CODTRANSACCIONVENTANILLA, A.FLGTRANSACCIONAPROBADA, A.CODMONEDA, A.MTOTRANSACCION, -1 AS CODCLAVEOPECTA, A.CODCLAVEOPECTADESTINO,
    D.CODCLAVECIC AS CODCLAVECICPEP
FROM TMP_ESCPEP_TRX_VENTANILLA_INI A
     INNER JOIN ODS_V.HD_MOVLAVADODINEROVENTANILLA B ON A.FECDIA = B.FECDIA AND A.CODSUCAGE = B.CODSUCAGE AND A.CODSESION = B.CODSESION
     INNER JOIN ODS_V.MD_CLIENTEG94 C ON TRIM(C.CODUNICOCLI) = COALESCE(TRIM(B.CODUNICOCLISOLICITANTE), TRIM(B.CODUNICOCLIORDENANTE))
     INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP D ON C.CODCLAVECIC = D.CODCLAVECIC
WHERE A.CODTRANSACCIONVENTANILLA IN (60,62,63) AND C.CODCLAVECIC <> 0;

--EXTRACCION DE TRANSFERENCIAS

--DROP TABLE TMP_ESCPEP_TRX_VENT_PEP_INT_TRAN;
--CREATE TABLE TMP_ESCPEP_TRX_VENT_PEP_INT_TRAN TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_VENT_PEP_INT_TRAN;
INSERT INTO TMP_ESCPEP_TRX_VENT_PEP_INT_TRAN
SELECT DISTINCT
    A.NUMREGISTRO, A.FECDIA, A.HORINITRANSACCION, A.HORFINTRANSACCION, A.CODTRANSACCIONVENTANILLA, A.FLGTRANSACCIONAPROBADA, A.CODMONEDA, A.MTOTRANSACCION, A.CODCLAVEOPECTA, A.CODCLAVEOPECTADESTINO,
    B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM TMP_ESCPEP_TRX_VENTANILLA_INI A
     INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA
WHERE A.CODTRANSACCIONVENTANILLA IN (159,186,187,188);

---EXTRACCION DE INT-PEP

--DROP TABLE TMP_ESCPEP_TRX_VENT_INT_PEP_TRANDEP;
--CREATE TABLE TMP_ESCPEP_TRX_VENT_INT_PEP_TRANDEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_VENT_INT_PEP_TRANDEP;
INSERT INTO TMP_ESCPEP_TRX_VENT_INT_PEP_TRANDEP
SELECT DISTINCT
    A.NUMREGISTRO, A.FECDIA, A.HORINITRANSACCION, A.HORFINTRANSACCION, A.CODTRANSACCIONVENTANILLA, A.FLGTRANSACCIONAPROBADA, A.CODMONEDA, A.MTOTRANSACCION, C.CODCLAVECIC AS CODCLAVECICG94, A.CODCLAVEOPECTA, A.CODCLAVEOPECTADESTINO,
    D.CODCLAVECIC AS CODCLAVECICPEP, D.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM TMP_ESCPEP_TRX_VENTANILLA_INI A
    LEFT JOIN ODS_V.HD_MOVLAVADODINEROVENTANILLA B ON A.FECDIA = B.FECDIA AND A.CODSUCAGE = B.CODSUCAGE AND A.CODSESION = B.CODSESION
    LEFT JOIN ODS_V.MD_CLIENTEG94 C ON COALESCE(B.CODUNICOCLISOLICITANTE, B.CODUNICOCLIORDENANTE) = TRIM(C.CODUNICOCLI)
    INNER JOIN TMP_ESCPEP_CUENTAS_PEP D ON A.CODCLAVEOPECTADESTINO = D.CODCLAVEOPECTA
WHERE A.CODTRANSACCIONVENTANILLA IN (60,62,63,159,186,187,188);

--EXTRACCION DE TRXS EN GGTT

--DROP TABLE TMP_ESCPEP_DOCGGTT;
--CREATE TABLE TMP_ESCPEP_DOCGGTT TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_DOCGGTT;
INSERT INTO TMP_ESCPEP_DOCGGTT
SELECT DISTINCT A.CODDOCGGTT,A.NUMOPERACIONGGTT, A.FECDIA, A.FECEMISION, A.HOREMISION, A.CODTIPESTADOTRANSACCION, A.CODPRODUCTO, A.CODMONEDA, A.MTOIMPORTEOPERACION, A.CODCLAVECICSOLICITANTE, A.CODCLAVECICORDENANTE, A.CODCLAVECICBENEFICIARIO, A.CODSWIFTBCOEMISOR, A.CODSWIFTBCODESTINO, A.CODPAISBCODESTINO
FROM ODS_V.HD_DOCUMENTOEMITIDOGGTT A
WHERE FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2))) AND CODTIPESTADOTRANSACCION = '00';

--EXTRACCION DE PEP-INT

--DROP TABLE TMP_ESCPEP_TRX_GGTT_PEP_INT;
--CREATE TABLE TMP_ESCPEP_TRX_GGTT_PEP_INT TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_GGTT_PEP_INT;
INSERT INTO TMP_ESCPEP_TRX_GGTT_PEP_INT
SELECT DISTINCT A.CODDOCGGTT,A.NUMOPERACIONGGTT, A.FECDIA, A.FECEMISION, A.HOREMISION, A.CODTIPESTADOTRANSACCION, A.CODPRODUCTO, A.CODMONEDA, A.MTOIMPORTEOPERACION, A.CODCLAVECICSOLICITANTE, A.CODCLAVECICORDENANTE, A.CODCLAVECICBENEFICIARIO, A.CODSWIFTBCOEMISOR, A.CODSWIFTBCODESTINO, A.CODPAISBCODESTINO,
B.CODCLAVECIC AS CODCLAVECICPEP
FROM
    TMP_ESCPEP_DOCGGTT A
    INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP B ON A.CODCLAVECICORDENANTE = B.CODCLAVECIC;

--EXTRACCION DE INT-PEP

--DROP TABLE TMP_ESCPEP_TRX_GGTT_INT_PEP;
--CREATE TABLE TMP_ESCPEP_TRX_GGTT_INT_PEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_GGTT_INT_PEP;
INSERT INTO TMP_ESCPEP_TRX_GGTT_INT_PEP
SELECT DISTINCT A.CODDOCGGTT,A.NUMOPERACIONGGTT, A.FECDIA, A.FECEMISION, A.HOREMISION, A.CODTIPESTADOTRANSACCION, A.CODPRODUCTO, A.CODMONEDA, A.MTOIMPORTEOPERACION, A.CODCLAVECICSOLICITANTE, A.CODCLAVECICORDENANTE, A.CODCLAVECICBENEFICIARIO, A.CODSWIFTBCOEMISOR, A.CODSWIFTBCODESTINO, A.CODPAISBCODESTINO,
B.CODCLAVECIC AS CODCLAVECICPEP
FROM
    TMP_ESCPEP_DOCGGTT A
    INNER JOIN TMP_ESCPEP_CODCLAVECICS_PEP B ON A.CODCLAVECICBENEFICIARIO = B.CODCLAVECIC;

--EXTRACCION DE TRXS EN TABLA TRANSFERENCIAS DEL EXTERIOR

--DROP TABLE TMP_ESCPEP_TRX_REMITT_INT_PEP_DELEXT;
--CREATE TABLE TMP_ESCPEP_TRX_REMITT_INT_PEP_DELEXT TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_REMITT_INT_PEP_DELEXT;
INSERT INTO TMP_ESCPEP_TRX_REMITT_INT_PEP_DELEXT
SELECT 
A.NUMOPERACIONREMITTANCE, A.FECDIA, A.HORTRANSACCION, A.CODPRODUCTO, A.CODESTADOOPEREMITTANCE, A.CODMONEDA, A.MTOTRANSACCION, A.MTOTRANSACCIONDOL,-1 AS CODCLAVEOPECTAORIGEN, A.CODCLAVEOPECTAAFECTADA, A.CODPAISORIGEN, A.CODSWIFTINSTORDENANTE, A.CODSWIFTBCOORDENANTE,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM ODS_V.HD_MOVOPERATIVOREMITTANCE  A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTAAFECTADA = B.CODCLAVEOPECTA
WHERE CODPRODUCTO IN ('TRAXAB','TRAXRE','TRAXVE') AND CODESTADOOPEREMITTANCE = '7' AND FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

--EXTRACCION DE TRXS EN TABLA TRANSFERENCIAS AL EXTERIOR

--DROP TABLE TMP_ESCPEP_TRX_BANNI_PEP_INT_ALEXT;
--CREATE TABLE TMP_ESCPEP_TRX_BANNI_PEP_INT_ALEXT TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_BANNI_PEP_INT_ALEXT;
INSERT INTO TMP_ESCPEP_TRX_BANNI_PEP_INT_ALEXT
SELECT
A.CODCLAVEOPECTA, A.NUMREGISTRO, A.FECDIA, A.HORTRANSACCION, B.CODPRODUCTO, B.FLGREGELIMINADO, B.CODMONEDA, B.MTOOPERACION, B.MTOOPERACIONDOL, B.CODCLAVEOPECTAAFECTADA , -1 AS CODCLAVEOPECTADESTINO, B.CODPAISBENEFICIARIO,
C.CODCLAVECIC AS CODCLAVECICPEP, C.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM ODS_V.HD_MOVIMIENTOBANNI  A
LEFT JOIN ODS_V.MD_OPERACIONBAN B ON A.CODCLAVEOPECTA = B.CODCLAVEOPECTA
INNER JOIN TMP_ESCPEP_CUENTAS_PEP C ON B.CODCLAVEOPECTAAFECTADA = C.CODCLAVEOPECTA
WHERE B.CODPRODUCTO = 'TRAEXT' AND B.FLGREGELIMINADO = 'N'  AND A.FECDIA BETWEEN  TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)));

--EXTRACCION DE TRANSERENCIAS INTERBANCARIAS

--EXTRACCION DE GRE-INT
--DROP TABLE TMP_ESCPEP_TRX_TTIB_PEP_INT_TTIB;
--CREATE TABLE TMP_ESCPEP_TRX_TTIB_PEP_INT_TTIB TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_TTIB_PEP_INT_TTIB;
INSERT INTO TMP_ESCPEP_TRX_TTIB_PEP_INT_TTIB
SELECT DISTINCT
A.NUMSECUENCIAL, A.FECTRANSACCION, A.HORTRANSACCION, A.CODOPETRANSACCIONTTIB, A.TIPESTTTIB, A.CODMONEDA, A.MTOTRANSACCION, A.CODCTAINTERBANORDENANTE, A.CODCLAVEOPECTAORDENANTE, A.CODCTAINTERBANBENEFICIARIO, A.CODCLAVEOPECTABENEFICIARIO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM ODS_V.HD_MOVIMIENTOTTIB A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTAORDENANTE = B.CODCLAVEOPECTA
WHERE A.TIPESTTTIB = '00' AND A.CODOPETRANSACCIONTTIB NOT IN (223,221) AND A.FECTRANSACCION BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)));

--EXTRACCION DE INT-GRE
--DROP TABLE TMP_ESCPEP_TRX_TTIB_INT_PEP_TTIB;
--CREATE TABLE TMP_ESCPEP_TRX_TTIB_INT_PEP_TTIB TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRX_TTIB_INT_PEP_TTIB;
INSERT INTO TMP_ESCPEP_TRX_TTIB_INT_PEP_TTIB
SELECT DISTINCT
A.NUMSECUENCIAL, A.FECTRANSACCION, A.HORTRANSACCION, A.CODOPETRANSACCIONTTIB, A.TIPESTTTIB, A.CODMONEDA, A.MTOTRANSACCION, A.CODCTAINTERBANORDENANTE, A.CODCLAVEOPECTAORDENANTE, A.CODCTAINTERBANBENEFICIARIO, A.CODCLAVEOPECTABENEFICIARIO,
B.CODCLAVECIC AS CODCLAVECICPEP, B.CODCLAVEOPECTA AS CODCLAVEOPECTAPEP
FROM ODS_V.HD_MOVIMIENTOTTIB A
INNER JOIN TMP_ESCPEP_CUENTAS_PEP B ON A.CODCLAVEOPECTABENEFICIARIO = B.CODCLAVEOPECTA
WHERE A.TIPESTTTIB = '00' AND A.CODOPETRANSACCIONTTIB NOT IN (223,221) AND A.FECTRANSACCION BETWEEN TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') AND TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, :INTERVALO_2)));

--CONSOLIDACION DE TRXS

--DROP TABLE TMP_ESCPEP_PEP_INT;
--CREATE TABLE TMP_ESCPEP_PEP_INT TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_PEP_INT;
INSERT INTO TMP_ESCPEP_PEP_INT
    --AGENTE
      SELECT
          T.NUMREGISTRO, T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.TIPTRANSACCIONAGENTEVIABCP) AS CODTRANSACCION, D.DESTIPTRANSACCIONAGENTEVIABCP AS TIPOTRANSACCION, 'AGENTE' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO, L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_AGE_PEP_INT_TRAN T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTAABONO = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTIPOTRANAGENTEVIABCP D ON T.TIPTRANSACCIONAGENTEVIABCP = D.TIPTRANSACCIONAGENTEVIABCP
      WHERE T.TIPTRANSACCIONAGENTEVIABCP = '03'
      UNION
      SELECT
          T.NUMREGISTRO, T.CODCLAVECICPEP,-1 AS CODCLAVEOPECTAPEP,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.TIPTRANSACCIONAGENTEVIABCP) AS CODTRANSACCION, D.DESTIPTRANSACCIONAGENTEVIABCP AS TIPOTRANSACCION, 'AGENTE' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO,L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_AGE_PEP_INT_DEP T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTAABONO = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTIPOTRANAGENTEVIABCP D ON T.TIPTRANSACCIONAGENTEVIABCP = D.TIPTRANSACCIONAGENTEVIABCP
          WHERE T.TIPTRANSACCIONAGENTEVIABCP = '05'
      UNION
    --CAJERO
      SELECT
          T.NUMREGISTRO, T.CODCLAVECICPEP, T.CODCLAVEOPECTAPEP,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDATRAN, CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END AS MTOTRANSACCION, (CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END) * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANCAJERO) AS CODTRANSACCION, D.DESCODTRANCAJERO AS TIPOTRANSACCION, 'CAJERO' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO, L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_CAJ_PEP_INT_TRAN T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTAHACIA = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDATRAN = TC.CODMONEDA
          LEFT JOIN ODS_V.MM_DESCODIGOTRANSACCIONCAJERO D ON T.CODTRANCAJERO = D.CODTRANCAJERO
      UNION
      SELECT
          T.NUMREGISTRO, T.CODCLAVECICPEP, -1 AS CODCLAVEOPECTAPEP,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDATRAN, CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END AS MTOTRANSACCION, (CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END) * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANCAJERO) AS CODTRANSACCION, D.DESCODTRANCAJERO AS TIPOTRANSACCION, 'CAJERO' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO, L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_CAJ_PEP_INT_DEP T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTAHACIA = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDATRAN = TC.CODMONEDA
          LEFT JOIN ODS_V.MM_DESCODIGOTRANSACCIONCAJERO D ON T.CODTRANCAJERO = D.CODTRANCAJERO
      UNION
    --BANCA MOVIL
      SELECT
          TO_CHAR(T.NUMTRANSACCIONBCAMOVIL) AS NUMTRANSACCIONBCAMOVIL, T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP,
          T.FECTRANSACCION, T.HORTRANSACCION, T.CODMONEDATRANSACCION AS CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.TIPTRANSACCIONBCAMOVIL) AS CODTRANSACCION, D.DESTIPTRANSACCIONBCAMOVIL AS TIPOTRANSACCION, 'BANCA MOVIL' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTIN, L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_BCAMOV_PEP_INT_TRAN T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTADESTINO = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECTRANSACCION = TC.FECTIPCAMBIO AND T.CODMONEDATRANSACCION = TC.CODMONEDA
          LEFT JOIN ODS_V.MM_DESTIPTRANSACCIONBCAMOVIL D ON T.TIPTRANSACCIONBCAMOVIL = D.TIPTRANSACCIONBCAMOVIL
      UNION
    --HOMEBANKING
      SELECT
          T.CODINTERNOTRANSACCIONHB, T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODOPEHBCTR) AS CODTRANSACCION, D.DESCODOPEHBCTR AS TIPOTRANSACCION, 'HOMEBANKING' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO, L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_HBK_PEP_INT_TRAN T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTADESTINO = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESCODIGOOPEHBCTR D ON T.CODOPEHBCTR = D.CODOPEHBCTR
      UNION
    --VENTANILLA
      SELECT
          TO_CHAR(T.NUMREGISTRO) AS NUMREGISTRO, T.CODCLAVECICPEP,-1 AS CODCLAVEOPECTAPEP,
          T.FECDIA, T.HORINITRANSACCION , T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANSACCIONVENTANILLA) AS CODTRANSACCION, D.DESTRANSACCIONVENTANILLA AS TIPOTRANSACCION, 'VENTANILLA' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO, L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_VENT_PEP_INT_DEP T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTADESTINO = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA D ON T.CODTRANSACCIONVENTANILLA = D.CODTRANSACCIONVENTANILLA
      UNION
      SELECT
          TO_CHAR(T.NUMREGISTRO) AS NUMREGISTRO, T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP,
          T.FECDIA, T.HORINITRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANSACCIONVENTANILLA) AS CODTRANSACCION, D.DESTRANSACCIONVENTANILLA AS TIPOTRANSACCION, 'VENTANILLA' AS CANAL,
          L.CODCLAVECIC AS CODCLAVECICINT,' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO, L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT
      FROM
          TMP_ESCPEP_TRX_VENT_PEP_INT_TRAN T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTADESTINO = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA D ON T.CODTRANSACCIONVENTANILLA = D.CODTRANSACCIONVENTANILLA
      UNION
    --GGTT
    	SELECT
    		T.CODDOCGGTT, T.CODCLAVECICPEP,-1 AS CODCLAVEOPECTAPEP,
    		T.FECDIA, T.HOREMISION, T.CODMONEDA, T.MTOIMPORTEOPERACION, T.MTOIMPORTEOPERACION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODPRODUCTO) AS CODTRANSACCION, D.DESCODPRODUCTO AS TIPOTRANSACCION, 'DOCUMENTOGGTT' AS CANAL,
    		CASE WHEN T.CODCLAVECICBENEFICIARIO = 3288453 THEN -1 ELSE T.CODCLAVECICBENEFICIARIO END AS CODCLAVECICINT,' ' AS DATOADICIONALINT, UPPER(P.NOMBREPAIS) AS CODPAISDESTINO, -1 AS CODCLAVEOPECTAINT
    	FROM
    		TMP_ESCPEP_TRX_GGTT_PEP_INT T
    		LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
    		LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D ON T.CODPRODUCTO = D.CODPRODUCTO
    		LEFT JOIN S55632.MD_CODIGOPAIS P ON SUBSTR(T.CODSWIFTBCODESTINO, 5, 2) = P.CODPAIS2 OR CODPAISBCODESTINO = P.CODPAIS3
      UNION
      --BANNI AL EXTERIOR
    	SELECT
    		TO_CHAR(T.CODCLAVEOPECTA) AS CODCLAVEOPECTA, T.CODCLAVECICPEP, T.CODCLAVEOPECTAPEP,
    		T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOOPERACION, T.MTOOPERACIONDOL AS MTODOLARIZADO, TO_CHAR(T.CODPRODUCTO) AS CODTRANSACCION, D.DESCODPRODUCTO AS TIPOTRANSACCION, 'BANNI' AS CANAL,
    		-1 AS CODCLAVECICINT, '' AS DATOADICIONALINT, UPPER(P.NOMBREPAIS) AS CODPAISDESTINO, -1 AS CODCLAVEOPECTAINT
    	FROM
    		TMP_ESCPEP_TRX_BANNI_PEP_INT_ALEXT T
    		LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D ON T.CODPRODUCTO = D.CODPRODUCTO
    		LEFT JOIN S55632.MD_CODIGOPAIS P ON TRIM(T.CODPAISBENEFICIARIO) = P.CODPAIS3
      UNION
      --TTIB
    	SELECT
    		T.NUMSECUENCIAL,T.CODCLAVECICPEP, T.CODCLAVEOPECTAPEP,
    		T.FECTRANSACCION, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODOPETRANSACCIONTTIB) AS CODTRANSACCION, D.DESTIPOPERACIONTTIB AS TIPOTRANSACCION, 'TTIB' AS CANAL,
    		-1 AS CODCLAVECICINT, ' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO, -1 AS CODCLAVEOPECTAINT
    	FROM
    		TMP_ESCPEP_TRX_TTIB_PEP_INT_TTIB T
        LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECTRANSACCION = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
        LEFT JOIN ODS_V.MD_DESTIPOPERACIONTTIB D ON T.CODOPETRANSACCIONTTIB = D.TIPOPERACIONTTIB;

--DROP TABLE TMP_ESCPEP_INT_PEP;
--CREATE TABLE TMP_ESCPEP_INT_PEP TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_INT_PEP;
INSERT INTO TMP_ESCPEP_INT_PEP
    --AGENTE
      SELECT
          T.NUMREGISTRO, L.CODCLAVECIC AS CODCLAVECICINT,L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.TIPTRANSACCIONAGENTEVIABCP) AS CODTRANSACCION, D.DESTIPTRANSACCIONAGENTEVIABCP AS TIPOTRANSACCION, 'AGENTE' AS CANAL,
          T.CODCLAVECICPEP, T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_AGE_INT_PEP_TRANDEP T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTACARGO = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTIPOTRANAGENTEVIABCP D ON T.TIPTRANSACCIONAGENTEVIABCP = D.TIPTRANSACCIONAGENTEVIABCP
          WHERE  T.TIPTRANSACCIONAGENTEVIABCP = '03'
      UNION
      SELECT
          T.NUMREGISTRO, T.CODCLAVECICG94 AS CODCLAVECICINT, -1 AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.TIPTRANSACCIONAGENTEVIABCP) AS CODTRANSACCION, D.DESTIPTRANSACCIONAGENTEVIABCP AS TIPOTRANSACCION, 'AGENTE' AS CANAL,
          T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_AGE_INT_PEP_TRANDEP T
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTIPOTRANAGENTEVIABCP D ON T.TIPTRANSACCIONAGENTEVIABCP = D.TIPTRANSACCIONAGENTEVIABCP
      WHERE T.TIPTRANSACCIONAGENTEVIABCP = '05' AND T.CODCLAVECICG94 IS NOT NULL
      UNION
    --CAJERO
      SELECT
          T.NUMREGISTRO, L.CODCLAVECIC AS CODCLAVECICINT,T.CODCLAVEOPECTADESDE AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDATRAN, CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END AS MTOTRANSACCION, (CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END) * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANCAJERO) AS CODTRANSACCION, D.DESCODTRANCAJERO AS TIPOTRANSACCION, 'CAJERO' AS CANAL,
          T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTADESDE = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDATRAN = TC.CODMONEDA
          LEFT JOIN ODS_V.MM_DESCODIGOTRANSACCIONCAJERO D ON T.CODTRANCAJERO = D.CODTRANCAJERO
      WHERE T.CODTRANCAJERO IN ('40')
      UNION
      SELECT
          T.NUMREGISTRO, T.CODCLAVECIC AS CODCLAVECICINT,-1 AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDATRAN, CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END AS MTOTRANSACCION, (CASE WHEN T.CODMONEDATRAN = '0001' THEN T.MTOTRANSACCIONSOL ELSE T.MTOTRANSACCIONME END) * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANCAJERO) AS CODTRANSACCION, D.DESCODTRANCAJERO AS TIPOTRANSACCION, 'CAJERO' AS CANAL,
          T.CODCLAVECICPEP, T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_CAJ_INT_PEP_TRANDEP T
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDATRAN = TC.CODMONEDA
          LEFT JOIN ODS_V.MM_DESCODIGOTRANSACCIONCAJERO D ON T.CODTRANCAJERO = D.CODTRANCAJERO
      WHERE T.CODTRANCAJERO IN ('20') AND T.CODCLAVECIC <> 0
      UNION
    --BANCA MOVIL
      SELECT
          TO_CHAR(T.NUMTRANSACCIONBCAMOVIL) AS NUMTRANSACCIONBCAMOVIL, L.CODCLAVECIC AS CODCLAVECICINT,L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECTRANSACCION, T.HORTRANSACCION, T.CODMONEDATRANSACCION AS CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.TIPTRANSACCIONBCAMOVIL) AS CODTRANSACCION, D.DESTIPTRANSACCIONBCAMOVIL AS TIPOTRANSACCION, 'BANCA MOVIL' AS CANAL,
          T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_BCAMOV_INT_PEP_TRAN T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTAORIGEN = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECTRANSACCION = TC.FECTIPCAMBIO AND T.CODMONEDATRANSACCION = TC.CODMONEDA
          LEFT JOIN ODS_V.MM_DESTIPTRANSACCIONBCAMOVIL D ON T.TIPTRANSACCIONBCAMOVIL = D.TIPTRANSACCIONBCAMOVIL
      UNION
    --HOMEBANKING
      SELECT
          T.CODINTERNOTRANSACCIONHB, L.CODCLAVECIC AS CODCLAVECICINT,T.CODCLAVEOPECTAORIGEN AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODOPEHBCTR) AS CODTRANSACCION, D.DESCODOPEHBCTR AS TIPOTRANSACCION, 'HOMEBANKING' AS CANAL,
          T.CODCLAVECICPEP, T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_HBK_INT_PEP_TRAN T
          INNER JOIN ODS_V.MD_CUENTA  L ON T.CODCLAVEOPECTAORIGEN = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESCODIGOOPEHBCTR D ON T.CODOPEHBCTR = D.CODOPEHBCTR
      UNION
    --VENTANILLA
      SELECT
          TO_CHAR(T.NUMREGISTRO) AS NUMREGISTRO, T.CODCLAVECICG94 AS CODCLAVECICINT, -1 AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECDIA, T.HORINITRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANSACCIONVENTANILLA) AS CODTRANSACCION, D.DESTRANSACCIONVENTANILLA AS TIPOTRANSACCION, 'VENTANILLA' AS CANAL,
          T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_VENT_INT_PEP_TRANDEP T
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA D ON T.CODTRANSACCIONVENTANILLA = D.CODTRANSACCIONVENTANILLA
      WHERE T.CODTRANSACCIONVENTANILLA IN (60,62,63) AND T.CODCLAVECICG94 IS NOT NULL
      UNION
      SELECT
          TO_CHAR(T.NUMREGISTRO) AS NUMREGISTRO, L.CODCLAVECIC AS CODCLAVECICINT,L.CODCLAVEOPECTA AS CODCLAVEOPECTAINT,
          ' ' AS DATOADICIONALINT,' ' AS CODPAISORIGEN,
          T.FECDIA, T.HORINITRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODTRANSACCIONVENTANILLA) AS CODTRANSACCION, D.DESTRANSACCIONVENTANILLA AS TIPOTRANSACCION, 'VENTANILLA' AS CANAL,
          T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP
      FROM
          TMP_ESCPEP_TRX_VENT_INT_PEP_TRANDEP T
          INNER JOIN ODS_V.MD_CUENTA L ON T.CODCLAVEOPECTA = L.CODCLAVEOPECTA
          LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
          LEFT JOIN ODS_V.MD_DESTRANSACCIONVENTANILLA D ON T.CODTRANSACCIONVENTANILLA = D.CODTRANSACCIONVENTANILLA
      WHERE T.CODTRANSACCIONVENTANILLA IN (159,186,187,188)
      UNION
    --GGTT
    	SELECT
    		T.CODDOCGGTT, CASE WHEN T.CODCLAVECICORDENANTE = 3288453 THEN -1 ELSE T.CODCLAVECICORDENANTE END AS CODCLAVECICINT, -1 AS CODCLAVEOPECTAINT,
    		' ' AS DATOADICIONALINT, UPPER(P.NOMBREPAIS) AS CODPAISORIGEN,
    		T.FECDIA, T.HOREMISION, T.CODMONEDA, T.MTOIMPORTEOPERACION, T.MTOIMPORTEOPERACION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODPRODUCTO) AS CODTRANSACCION, D.DESCODPRODUCTO AS TIPOTRANSACCION, 'DOCUMENTOGGTT' AS CANAL,
    		T.CODCLAVECICPEP, -1 AS CODCLAVEOPECTAPEP
    	FROM
    		TMP_ESCPEP_TRX_GGTT_INT_PEP T
    		LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECDIA = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
    		LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D ON T.CODPRODUCTO = D.CODPRODUCTO
    		LEFT JOIN S55632.MD_CODIGOPAIS P ON SUBSTR(T.CODSWIFTBCOEMISOR, 5, 2) = P.CODPAIS2
      UNION
    --REMITTANCE DEL EXTERIOR
    	SELECT
    		T.NUMOPERACIONREMITTANCE, -1 AS CODCLAVECICINT,-1 AS CODCLAVEOPECTAINT,
    		' ' AS DATOADICIONALINT, UPPER(P.NOMBREPAIS) AS CODPAISORIGEN,
    		T.FECDIA, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCIONDOL AS MTODOLARIZADO, TO_CHAR(T.CODPRODUCTO) AS CODTRANSACCION, D.DESCODPRODUCTO AS TIPOTRANSACCION, 'REMITTANCE' AS CANAL,
    		T.CODCLAVECICPEP,T.CODCLAVEOPECTAPEP
    	FROM
    		TMP_ESCPEP_TRX_REMITT_INT_PEP_DELEXT T
    		LEFT JOIN ODS_V.MD_DESCODIGOPRODUCTO D ON T.CODPRODUCTO = D.CODPRODUCTO
    		LEFT JOIN S55632.MD_CODIGOPAIS P ON SUBSTR(COALESCE(T.CODSWIFTINSTORDENANTE, T.CODSWIFTBCOORDENANTE), 5, 2) = P.CODPAIS2
      UNION
      --TTIB
    	SELECT
    		T.NUMSECUENCIAL,-1 AS CODCLAVECICINT, -1 AS CODCLAVEOPECTAINT,
        ' ' AS DATOADICIONALINT, ' ' AS CODPAISDESTINO,
    		T.FECTRANSACCION, T.HORTRANSACCION, T.CODMONEDA, T.MTOTRANSACCION, T.MTOTRANSACCION * TC.MTOCAMBIOALDOLAR AS MTODOLARIZADO, TO_CHAR(T.CODOPETRANSACCIONTTIB) AS CODTRANSACCION, D.DESTIPOPERACIONTTIB AS TIPOTRANSACCION, 'TTIB' AS CANAL,
    		T.CODCLAVECICPEP, T.CODCLAVEOPECTAPEP
    	FROM
    		TMP_ESCPEP_TRX_TTIB_INT_PEP_TTIB T
        LEFT JOIN ODS_V.HD_TIPOCAMBIOSALDODIARIO TC ON T.FECTRANSACCION = TC.FECTIPCAMBIO AND T.CODMONEDA = TC.CODMONEDA
        LEFT JOIN ODS_V.MD_DESTIPOPERACIONTTIB D ON T.CODOPETRANSACCIONTTIB = D.TIPOPERACIONTTIB;

--CONSOLIDACION

--DROP TABLE TMP_ESCPEP_TRXS_AUX;
--CREATE TABLE TMP_ESCPEP_TRXS_AUX TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRXS_AUX;
INSERT INTO TMP_ESCPEP_TRXS_AUX
SELECT
      CAST(TO_CHAR(FECDIA, 'YYYYMM') AS INT) AS PERIODO, NUMREGISTRO, CODCLAVECICINT AS CODCLAVECICSOURCE, CODCLAVEOPECTAINT AS CODCLAVEOPECTASOURCE, UPPER(REPLACE(DATOADICIONALINT,'''','')) AS DATOSOURCE, CODPAISORIGEN AS PAISSOURCE,
      FECDIA, HORTRANSACCION, CODMONEDA, MTOTRANSACCION, MTODOLARIZADO, CODTRANSACCION, TIPOTRANSACCION, CANAL,
      CODCLAVECICPEP AS CODCLAVECICTARGET,CODCLAVEOPECTAPEP  AS CODCLAVEOPECTATARGET, '' AS DATOTARGET, '' AS PAISTARGET,
      'ING' AS TIPOINGRESOEGRESO
FROM TMP_ESCPEP_INT_PEP
WHERE (CODCLAVECICINT <> 0 AND CODCLAVECICPEP <> 0) OR CANAL IN ('DOCUMENTOGGTT', 'BANNI','REMITTANCE')
UNION ALL
SELECT
      CAST(TO_CHAR(FECDIA, 'YYYYMM') AS INT) AS PERIODO, NUMREGISTRO, CODCLAVECICPEP AS CODCLAVECICSOURCE,CODCLAVEOPECTAPEP AS CODCLAVEOPECTASOURCE, '' AS DATOSOURCE, '' AS PAISSOURCE,
      FECDIA, HORTRANSACCION, CODMONEDA, MTOTRANSACCION, MTODOLARIZADO, CODTRANSACCION, TIPOTRANSACCION, CANAL,
      CODCLAVECICINT AS CODCLAVECICTARGET,CODCLAVEOPECTAINT  AS CODCLAVEOPECTATARGET, UPPER(REPLACE(DATOADICIONALINT,'''','')) AS DATOTARGET, CODPAISDESTINO AS PAISTARGET,
      'EGR' AS TIPOINGRESOEGRESO
FROM TMP_ESCPEP_PEP_INT A
LEFT JOIN TMP_ESCPEP_CODCLAVECICS_PEP B ON A.CODCLAVECICINT = B.CODCLAVECIC
WHERE B.CODCLAVECIC IS NULL AND ((CODCLAVECICINT <> 0 AND CODCLAVECICPEP <> 0) OR CANAL IN ('DOCUMENTOGGTT', 'BANNI','REMITTANCE'));

--TABLA FINAL DE TRANSACCIONES

--DROP TABLE TMP_ESCPEP_TRXS;
--CREATE TABLE TMP_ESCPEP_TRXS TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_ESCPEP_TRXS;
INSERT INTO TMP_ESCPEP_TRXS
SELECT
      ROWNUM AS IDTRX,A.*, CASE WHEN CANAL = 'VENTANILLA' AND TRIM(CODTRANSACCION) IN ('60','62','63') THEN 1
				        WHEN CANAL = 'AGENTE' AND TRIM(CODTRANSACCION) IN ('05') THEN 1
				        WHEN CANAL = 'CAJERO' AND TRIM(CODTRANSACCION) IN ('20') THEN 1 ELSE 0 END FLGCASH
FROM TMP_ESCPEP_TRXS_AUX A
WHERE CODCLAVECICSOURCE <> CODCLAVECICTARGET AND MTODOLARIZADO > 100;

--REVISAR QUE SE PRESERVEN LAS TRXS DE GGTT QUE TENGAN VACIOS EN CODCLAVECICS S Y T

UPDATE TMP_ESCPEP_TRXS SET CODCLAVECICSOURCE = -1 WHERE CODCLAVECICSOURCE IS NULL;
UPDATE TMP_ESCPEP_TRXS SET CODCLAVECICTARGET = -1 WHERE CODCLAVECICTARGET IS NULL;

COMMIT;
SPOOL OFF
QUIT;