
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

ALTER SESSION SET NLS_NUMERIC_CHARACTERS='.,';

--TABLON DE ESCENARIO DE GREMIOS FUERA DE PERFIL

SET ECHO OFF;
SET FEEDBACK OFF;
SET HEAD OFF;
SET LIN 9999;
SET TRIMSPOOL ON;
SET WRAP OFF;
SET PAGES 0;
SET TERM OFF;

SPOOL ./data/production/01_raw.csv

PROMPT PERIODO|CODCLAVECIC|TIPPER|DESTIPPER|TIPCLI|DESTIPCLI|CODSECTORISTA|TIPBANCA|DESTIPBANCA|CODACTECONOMICA|DESACTECONOMICA|CODSUBSEGMENTO|DESSUBSEGMENTO|CODSEGMENTO|DESSEGMENTO|TIPMARCACLI|DESTIPMARCACLI|FLGREGELIMINADO|EDAD|ANTIGUEDADCLIENTE|FLGNP|CTDNP|FLGLSB|CTDLSB|CTDEVALS|CTDEVALS_FP|CTDINVS|CTDROS|FLGARCHIVONEGATIVO|DESTIPMOTIVONEGATIVO|NUMDIR|TIPDIR|CODUBIGEO|CODDISTRITO|DESCODDISTRITO|CODPROVINCIA|DESCODPROVINCIA|CODDEPARTAMENTO|DESCODDEPARTAMENTO|CTD_CTAS_NUEVAS|FLG_ROS|MTO_TOTAL|MTO_CASH|MTO_TIB|MTO_DEL_TTEE|MTO_TERCEROS_NOREL|MTO_EMP_REL_NOPDH|FLG_INGR_TER_NP_LSB|FLG_INGR_TER_AN|CTD_DEPO_10K|CTD_INGR_REL_NPLSP|MTO_EGRESO|MTO_AL_TTEE|FLG_PERFIL_INGTOTAL_3DS|FLG_PERFIL_INGCASH_3DS|FLG_PERFIL_EGR_3DS|FLG_PERFIL_ING_EGR_3DS|FLG_PERFIL_AL_DEL_TTEE_3DS|FLG_PERFIL_INGR_VS_ESTIM;

SELECT
PERIODO||'|'||
CODCLAVECIC||'|'||
TIPPER||'|'||
DESTIPPER||'|'||
TIPCLI||'|'||
DESTIPCLI||'|'||
CODSECTORISTA||'|'||
TIPBANCA||'|'||
DESTIPBANCA||'|'||
CODACTECONOMICA||'|'||
DESACTECONOMICA||'|'||
CODSUBSEGMENTO||'|'||
DESSUBSEGMENTO||'|'||
CODSEGMENTO||'|'||
DESSEGMENTO||'|'||
TIPMARCACLI||'|'||
DESTIPMARCACLI||'|'||
FLGREGELIMINADO||'|'||
EDAD||'|'||
ANTIGUEDADCLIENTE||'|'||
FLGNP||'|'||
CTDNP||'|'||
FLGLSB||'|'||
CTDLSB||'|'||
CTDEVALS||'|'||
CTDEVALS_FP||'|'||
CTDINVS||'|'||
CTDROS||'|'||
FLGARCHIVONEGATIVO||'|'||
DESTIPMOTIVONEGATIVO||'|'||
NUMDIR||'|'||
TIPDIR||'|'||
CODUBIGEO||'|'||
CODDISTRITO||'|'||
DESCODDISTRITO||'|'||
CODPROVINCIA||'|'||
DESCODPROVINCIA||'|'||
CODDEPARTAMENTO||'|'||
DESCODDEPARTAMENTO||'|'||
CTD_CTAS_NUEVAS||'|'||
FLG_ROS||'|'||
MTO_TOTAL||'|'||
MTO_CASH||'|'||
MTO_TIB||'|'||
MTO_DEL_TTEE||'|'||
MTO_TERCEROS_NOREL||'|'||
MTO_EMP_REL_NOPDH||'|'||
FLG_INGR_TER_NP_LSB||'|'||
FLG_INGR_TER_AN||'|'||
CTD_DEPO_10K||'|'||
CTD_INGR_REL_NPLSP||'|'||
MTO_EGRESO||'|'||
MTO_AL_TTEE||'|'||
FLG_PERFIL_INGTOTAL_3DS||'|'||
FLG_PERFIL_INGCASH_3DS||'|'||
FLG_PERFIL_EGR_3DS||'|'||
FLG_PERFIL_ING_EGR_3DS||'|'||
FLG_PERFIL_AL_DEL_TTEE_3DS||'|'||
FLG_PERFIL_INGR_VS_ESTIM
FROM TMP_ESCPEP_PEPS_MES
;

SPOOL OFF;
QUIT;