@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

CREATE TABLE TMP_BASETOP_DOLAR_OUTPUT
(	PERIODO			NUMBER,
	NBRCLIENTE		VARCHAR2(77),
	CODIGO_CLIENTE	VARCHAR2(13),
	CODDEPARTAMENTO	VARCHAR2(5),
	NBRUBICACION	VARCHAR2(25),
	FLGZAED			NUMBER,
	BENEFICIARIO	NUMBER,
	SOLICITANTE		NUMBER,
	TOTAL			NUMBER,
	NACIONALIDAD	VARCHAR2(40),
	CATFLGZAED		NUMBER,
	CATNACIONAL		NUMBER,
	CATSEGMENTO		NUMBER,
	CATPROFESION	NUMBER,
	FECNACIMIENTO	DATE,
	EDAD			NUMBER,
	PROFESION		VARCHAR2(100),
	CIIU			VARCHAR2(50),
	SEGMENTO		VARCHAR2(35),
	FFNN			VARCHAR2(7),
	FLGFFNN			NUMBER,
	NBRCLIENTE_REL	VARCHAR2(4000),
	CARGO_REL		VARCHAR2(4000),
	AN_CUMPLIMIENTO	CHAR(2),
	CUENTA_PASIVA	CHAR(2),
	CUENTA_ACTIVA	CHAR(2),
	FEC_INV			VARCHAR2(112),
	ORIGEN_INV		VARCHAR2(255),
	FEC_EVA			VARCHAR2(112),
	ORIGEN_EVA		VARCHAR2(255),
	EDAD_C			NUMBER,
	BENEF_99		NUMBER,
	SOLIC_99		NUMBER,
	ZONA_LIMA		NUMBER,
	ZONA_ZAED		NUMBER,
	ZONA_NOZAED		NUMBER,
	PROF_RIESGO		NUMBER,
	PROF_SININFO	NUMBER,
	PROF_OTRAS		NUMBER,
	SEGM_PEQCON		NUMBER,
	SEGM_EXCNEG		NUMBER,
	SEGM_ENAPRIV	NUMBER,
	OTROSNAC		NUMBER,
	PERU			NUMBER,
	SIN_NAC			NUMBER,
	NAC_RIESGO		NUMBER,
	ClienteSegment	NUMBER
) TABLESPACE D_AML_99 ;
COMMIT;
quit;