ALTER SESSION DISABLE PARALLEL QUERY;

SET ECHO OFF
SET FEEDBACK OFF
SET HEAD OFF
SET LIN 256
SET TRIMSPOOL ON
SET WRAP OFF
SET PAGES 0
SET TERM OFF
set colsep ','
--set colsep '|'


SPOOL \\Pfilep11\lavadoactivos\99_Procesos_BI\0_SapycWeb\PAQUETES_ADHOC\99999999_MODEM_EPIC003_TRX_&&codunicocli..csv;
--SPOOL \\pfile2kp02\_Practicantes_AC\Francesca_Melgar\CSV\99999999_MODEM_EPIC003_TRX_&&codunicocli..csv;

PROMPT CODIGO_OPERACION,CODCLAVECIC,NBRCLIORDENANTE,CODUNICOCLI,CODUNICOCLIBENEFICIARIO,MONEDA,MONTO_DOLAR,MTOTRX,NACIONALIDAD,FECHA_OPERACION,TIPO_PERSONA,PAIS_DESTINO,TIPMARCACLI,FLGPEP,CANAL,DESSEGMENTO,NBRCLIBENEFICIARIO,CODSECTORISTA;

SELECT
    CODIGO_OPERACION||','||
    CODCLAVECIC||','||
    REPLACE(TRIM(NBRCLIORDENANTE),',','')||','||
    CODUNICOCLI||','||
    CODUNICOCLIBENEFICIARIO||','||
    MONEDA||','||
	REPLACE(TRIM(TO_CHAR(MONTO_DOLAR,'99999999999999999990D00')),',','.')||','||
    REPLACE(TRIM(TO_CHAR(MTOTRX,'99999999999999999990D00')),',','.')||','||   
    NACIONALIDAD||','||
    FECHA_OPERACION||','||
    TIPO_PERSONA||','||
    PAIS_DESTINO||','||
    TIPMARCACLI||','||
    FLGPEP||','||
    CANAL||','||
    DESSEGMENTO||','||
    REPLACE(TRIM(NBRCLIBENEFICIARIO),',','')||','||
    CODSECTORISTA
FROM	
	TMP_TRX_EPIC003
	where CODCLAVECIC = :codclavecic;
	
SPOOL OFF;
