ALTER SESSION DISABLE PARALLEL QUERY;

SPOOL \\Pfilep11\lavadoactivos\99_Procesos_BI\0_SapycWeb\PAQUETES_ADHOC\99999999_MODEM_EPIC017_TRXS_&&CODUNICOCLI..CSV;

PROMPT IDTRX,PERIODO,NUMREGISTRO,CODCLAVECICSOURCE,CODUNICOCLISOURCE,NOMBRESOURCE,CODOPECTASOURCE,DATOSOURCE,PAISSOURCE,FECDIA,HORTRANSACCION,CODMONEDA,MTOTRANSACCION,MTODOLARIZADO,CODTRANSACCION,TIPOTRANSACCION,CANAL,CODCLAVECICTARGET,CODUNICOCLITARGET,NOMBRETARGET,CODOPECTATARGET,DATOTARGET,PAISTARGET,TIPOINGRESOEGRESO;

SELECT
	IDTRX||','||
	PERIODO||','||
	NUMREGISTRO||','||
	CODCLAVECICSOURCE||','||
	CODUNICOCLISOURCE||','||
	NOMBRESOURCE||','||
	CODOPECTASOURCE||','||
	DATOSOURCE||','||
	PAISSOURCE||','||
	FECDIA||','||
	HORTRANSACCION||','||
	CODMONEDA||','||
	REPLACE(TRIM(TO_CHAR(MTOTRANSACCION,'99999999999999999990D00')),',','.')||','||
	REPLACE(TRIM(TO_CHAR(MTODOLARIZADO,'99999999999999999990D00')),',','.')||','||
	CODTRANSACCION||','||
	TIPOTRANSACCION||','||
	CANAL||','||
	CODCLAVECICTARGET||','||
	CODUNICOCLITARGET||','||
	NOMBRETARGET||','||
	CODOPECTATARGET||','||
	DATOTARGET||','||
	PAISTARGET||','||
	TIPOINGRESOEGRESO
FROM TMP_TRX_EPIC017_2
WHERE CODCLAVECICSOURCE = :CODCLAVECIC
UNION
SELECT
	IDTRX||','||
	PERIODO||','||
	NUMREGISTRO||','||
	CODCLAVECICSOURCE||','||
	CODUNICOCLISOURCE||','||
	NOMBRESOURCE||','||
	CODOPECTASOURCE||','||
	DATOSOURCE||','||
	PAISSOURCE||','||
	FECDIA||','||
	HORTRANSACCION||','||
	CODMONEDA||','||
	REPLACE(TRIM(TO_CHAR(MTOTRANSACCION,'99999999999999999990D00')),',','.')||','||
	REPLACE(TRIM(TO_CHAR(MTODOLARIZADO,'99999999999999999990D00')),',','.')||','||
	CODTRANSACCION||','||
	TIPOTRANSACCION||','||
	CANAL||','||
	CODCLAVECICTARGET||','||
	CODUNICOCLITARGET||','||
	NOMBRETARGET||','||
	CODOPECTATARGET||','||
	DATOTARGET||','||
	PAISTARGET||','||
	TIPOINGRESOEGRESO
FROM TMP_TRX_EPIC017_1
WHERE CODCLAVECICTARGET = :CODCLAVECIC ;

SPOOL OFF;