@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

VAR INTERVALO_1 NUMBER
EXEC :INTERVALO_1 := TO_NUMBER(&2);
VAR INTERVALO_2 NUMBER
EXEC :INTERVALO_2 := TO_NUMBER(&3);

SELECT :INTERVALO_1, :INTERVALO_2 FROM DUAL;

--create TABLE TMP_INGCLIEBCACEI_ALERTASMODEL as
truncate table TMP_INGCLIEBCACEI_ALERTASMODEL ;
insert into TMP_INGCLIEBCACEI_ALERTASMODEL
  WITH TMP AS
  (
    SELECT A.*,B.N_CLUSTER
    FROM TMP_INGCLIEBCACEI_CLIEMES_INGRETOT6  A
         INNER JOIN TMP_INGCLIEBCACEI_OUTPUTMODEL B ON A.CODCLAVECIC=B.CODCLAVECIC
    --WHERE A.CODCLAVECIC IN (SELECT CODCLAVECIC FROM TMP_INGCLIEBCACEI_OUTPUTMODEL)
  )
  SELECT *
  FROM TMP
  WHERE N_CLUSTER IN (3,5,7,8) AND
        MTO_RECIBIDO>500000 AND
        FLG_PERFIL_3DESVT_TRX=1 AND
        (FLG_ROS_REL=1 OR FLG_LSB_NP_REL=1);

--CREATE TABLE TMP_INGCLIEBCACEI_CIC_ALERTASMODEL TABLESPACE D_AML_99 AS
TRUNCATE TABLE TMP_INGCLIEBCACEI_CIC_ALERTASMODEL;
INSERT INTO TMP_INGCLIEBCACEI_CIC_ALERTASMODEL
	SELECT DISTINCT CODCLAVECIC
	FROM TMP_INGCLIEBCACEI_ALERTASMODEL;


truncate table TMP_INGCLIEBCACEI_ALERTAS;
insert into TMP_INGCLIEBCACEI_ALERTAS
--create TABLE TMP_INGCLIEBCACEI_ALERTAS as
  SELECT B.APEPATCLI||B.APEMATCLI||B.NBRCLI AS NBRCLI,A.*
  FROM TMP_INGCLIEBCACEI_ALERTASMODEL A
       LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODCLAVECIC=B.CODCLAVECIC
  WHERE A.CODCLAVECIC IN (SELECT * FROM TMP_INGCLIEBCACEI_CIC_ALERTASMODEL);	


TRUNCATE table TMP_INGCLIEBCACEI_CIC_ALERTASMODEL_INI;
INSERT into TMP_INGCLIEBCACEI_CIC_ALERTASMODEL_INI
--CREATE TABLE TMP_INGCLIEBCACEI_CIC_ALERTASMODEL_INI as
	select a.codclavecic, codunicocli, tipper,
		   case when tipper = 'E' then trim(apepatcli) || trim(apematcli) || trim(nbrcli)
				when tipper = 'P' then trim(apepatcli) || ' ' || trim(apematcli) || ' ' || trim(nbrcli)
		   end as nombre
	from ods_v.md_cliente a
		inner join TMP_INGCLIEBCACEI_CIC_ALERTASMODEL b on a.codclavecic = b.codclavecic and 
					a.codclavecic not in (select codclavecic from ods_v.md_empleadog94)
	union
	select a.codclavecic, codunicocli, 'P', trim(apepatempleado) || ' ' || trim(apematempleado) || ' ' || trim(nbrempleado)
	from ods_v.md_empleadog94 a
		inner join TMP_INGCLIEBCACEI_CIC_ALERTASMODEL b on a.codclavecic = b.codclavecic;

--CREATE TABLE TMP_INGCLIEBCACEI_CTAS_ALERT as
TRUNCATE table TMP_INGCLIEBCACEI_CTAS_ALERT ;
INSERT into TMP_INGCLIEBCACEI_CTAS_ALERT
	select cta.codclavecic, b.codunicocli, b.nombre, cta.codclaveopecta, codsistemaorigen, codopecta,
		   case when cta.codsistemaorigen = 'SAV' THEN
				SUBSTR(CODOPECTA,1,3) || '-' ||
				trim(to_char(MOD(to_number(SUBSTR(CODOPECTA,5,16)),100000000), '00000009')) || '-' ||
				SUBSTR(CODMONEDA,1,1) || '-' ||
				trim(to_char(
				CASE WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') THEN
					MOD(to_number(SUBSTR(CODOPECTA,13,2)) + to_number(SUBSTR(CODOPECTA,15,2)) +
					to_number(SUBSTR(CODOPECTA,17,2)) + to_number(SUBSTR(CODOPECTA,19,2)), 100)
				ELSE
					MOD(-20 + to_number(SUBSTR(CODOPECTA,1,1)) + to_number(SUBSTR(CODOPECTA,2,2)) + to_number(SUBSTR(CODOPECTA,13,2)) +
					to_number(SUBSTR(CODOPECTA,15,2)) + to_number(SUBSTR(CODOPECTA,17,2)) + to_number(SUBSTR(CODOPECTA,19,2)), 100)
				END, '09'))
		   when cta.codsistemaorigen = 'IMP' THEN
				SUBSTR(CODOPECTA,1,3) || '-' ||
				trim(to_char(MOD(to_number(SUBSTR(CODOPECTA,5,16)),10000000), '0000009')) || '-' ||
				SUBSTR(CODMONEDA,1,1) || '-' ||
				trim(to_char(
				CASE WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') AND CODMONEDA='0001' THEN
							MOD(to_number(SUBSTR(CODOPECTA,14,2)) + to_number(SUBSTR(CODOPECTA,16,2)) +
							to_number(SUBSTR(CODOPECTA,18,2)) + to_number(SUBSTR(CODOPECTA,20,1))*10, 100)
						WHEN SUBSTR(CODOPECTA,1,3) IN ('191','192','193','194') AND CODMONEDA='1001' THEN
							MOD(to_number(SUBSTR(CODOPECTA,14,2)) + to_number(SUBSTR(CODOPECTA,16,2)) +
							to_number(SUBSTR(CODOPECTA,18,2)) + to_number(SUBSTR(CODOPECTA,20,1))*10+10, 100)
						WHEN SUBSTR(CODOPECTA,1,3) NOT IN ('191','192','193','194') AND CODMONEDA='0001' THEN
							MOD(to_number(SUBSTR(CODOPECTA,1,1)) + to_number(SUBSTR(CODOPECTA,2,2)) + to_number(SUBSTR(CODOPECTA,14,2)) +
					  to_number(SUBSTR(CODOPECTA,16,2)) + to_number(SUBSTR(CODOPECTA,18,2)) + to_number(SUBSTR(CODOPECTA,20,1))*10, 100)
						WHEN SUBSTR(CODOPECTA,1,3) NOT IN ('191','192','193','194') AND CODMONEDA='1001' THEN
							MOD(10 + to_number(SUBSTR(CODOPECTA,1,1)) + to_number(SUBSTR(CODOPECTA,2,2)) + to_number(SUBSTR(CODOPECTA,14,2)) +
					  to_number(SUBSTR(CODOPECTA,16,2)) + to_number(SUBSTR(CODOPECTA,18,2)) + to_number(SUBSTR(CODOPECTA,20,1))*10, 100)
					   END, '09'))
			END as CuentaComercial
	from ods_v.md_cuentag94 cta
		 inner join TMP_INGCLIEBCACEI_CIC_ALERTASMODEL_INI b on cta.CODCLAVECIC = b.CODCLAVECIC
	where cta.CODSISTEMAORIGEN in ('SAV','IMP');

--CREATE TABLE TMP_INGCLIEBCACEI_SAV_ALERTAS as
TRUNCATE table TMP_INGCLIEBCACEI_SAV_ALERTAS;
INSERT into TMP_INGCLIEBCACEI_SAV_ALERTAS
	Select b.codclavecic, b.codunicocli, b.nombre, a.CODCLAVEOPECTA, b.CODOPECTA, b.CuentaComercial, a.FECDIA, a.HORTRANSACCION, a.DESOPETRANSACCIONSAVINGDETALLE, f.grupo,
		   c.DESCANAL, d.NBRSUCAGE, a.CODMONEDA, a.MTOTRANSACCION, a.TIPCARGOABONO, round(a.MTOTRANSACCION * e.MtoCambioAlDolar, 2) as MTODOLARIZADO
	from ods_v.hd_movimientosaving a
		 inner join TMP_INGCLIEBCACEI_CTAS_ALERT b on a.CODCLAVEOPECTA = b.codclaveopecta and b.codsistemaorigen = 'SAV'
		 left join ods_v.MD_DESCODIGOCANAL c on a.CODCANAL = c.CODCANAL
		 left join ods_v.MD_AGENCIA d on a.CODSUCAGE = d.CODSUCAGE
		 left join ods_v.hd_tipocambiosaldodiario e on a.FECDIA = e.FecTipCambio and a.CODMONEDA = e.CodMoneda
		 left join S55632.TMP_EQUIVAL_TIPOPE_EECC f on trim(a.DESOPETRANSACCIONSAVINGDETALLE) LIKE (trim(f.glosa) || '%')
	where a.fecdia between TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') and TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2)));

--CREATE TABLE TMP_INGCLIEBCACEI_IMP_ALERTAS as
TRUNCATE table TMP_INGCLIEBCACEI_IMP_ALERTAS;
INSERT into TMP_INGCLIEBCACEI_IMP_ALERTAS
WITH TMP AS (
    SELECT
        b.codclavecic, b.codunicocli, b.nombre, a.CODCLAVEOPECTA, b.CODOPECTA, b.CuentaComercial, a.FECDIA, a.HORTRANSACCION, a.DESOPETRANSACCIONIMPACDETALLE,
        a.CODMONEDA, a.MTOTRANSACCION, a.TIPCARGOABONO
        ,a.CODCANAL,a.CODSUCAGE
    FROM ods_v.hd_movimientoimpac a
        INNER JOIN TMP_INGCLIEBCACEI_CTAS_ALERT b on a.CODCLAVEOPECTA = b.codclaveopecta
    WHERE
        a.fecdia between TRUNC(ADD_MONTHS(SYSDATE, :INTERVALO_1),'MM') and TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,:INTERVALO_2))) AND
        b.codsistemaorigen = 'IMP'
)
	Select A.codclavecic, A.codunicocli, A.nombre, a.CODCLAVEOPECTA, A.CODOPECTA, A.CuentaComercial, a.FECDIA, a.HORTRANSACCION, a.DESOPETRANSACCIONIMPACDETALLE, f.grupo,
		   c.DESCANAL, d.NBRSUCAGE, a.CODMONEDA, a.MTOTRANSACCION, a.TIPCARGOABONO, round(a.MTOTRANSACCION * e.MtoCambioAlDolar, 2) as MTODOLARIZADO
	from TMP A
		 left join ods_v.MD_DESCODIGOCANAL c on a.CODCANAL = c.CODCANAL
		 left join ods_v.MD_AGENCIA d on a.CODSUCAGE = d.CODSUCAGE
		 left join ods_v.hd_tipocambiosaldodiario e on a.FECDIA = e.FecTipCambio and a.CODMONEDA = e.CodMoneda
		 left join S55632.TMP_EQUIVAL_TIPOPE_EECC f on trim(a.DESOPETRANSACCIONIMPACDETALLE) LIKE (trim(f.glosa) || '%');

--CREATE TABLE TMP_INGCLIEBCACEI_EECC_ALERTAS as
TRUNCATE table TMP_INGCLIEBCACEI_EECC_ALERTAS;
INSERT into TMP_INGCLIEBCACEI_EECC_ALERTAS
	select * from TMP_INGCLIEBCACEI_SAV_ALERTAS a
	union all
	select * from TMP_INGCLIEBCACEI_IMP_ALERTAS;

--TRANSACCIONES
TRUNCATE table TMP_INGCLIEBCACEI_TRX_INGRESOCLIE;
INSERT into TMP_INGCLIEBCACEI_TRX_INGRESOCLIE
--CREATE TABLE TMP_INGCLIEBCACEI_TRX_INGRESOCLIE as
WITH TMP AS
(
    SELECT B.CODUNICOCLI CODUNICOCLI_BEN,B.APEPATCLI||B.APEMATCLI||B.NBRCLI NBRCLI_BEN,A.*
    FROM TMP_INGCLIEBCACEI_TRX A
         LEFT JOIN ODS_v.MD_CLIENTE B ON A.CODCLAVECIC_BEN=B.CODCLAVECIC
    WHERE  A.CODCLAVECIC_BEN IN (SELECT * FROM TMP_INGCLIEBCACEI_CIC_ALERTASMODEL)
)
SELECT
       B.CODUNICOCLI CODUNICOCLI_SOL,B.APEPATCLI APEPATCLI_SOL,B.APEMATCLI APEMATCLI_SOL,B.NBRCLI NBRCLI_SOL,A.CODCLAVECIC_SOL,A.CODOPECTA_SOL,
       A.CODUNICOCLI_BEN,A.NBRCLI_BEN,A.CODCLAVECIC_BEN,A.CODOPECTA_BEN,A.TIPBANCA_BEN,
       A.FECDIA,A.HORTRANSACCION,A.CODMONEDA,A.MTOTRANSACCION,A.MTO_DOLARIZADO,A.TIPO_TRANSACCION,A.CANAL,A.CODPAISORIGEN
FROM TMP A
     LEFT JOIN ODS_V.MD_CLIENTE B ON A.CODCLAVECIC_SOL=B.CODCLAVECIC;

--Grant select on EPIC014_DOC to ROL_VISTASDWHGSTCUM;
quit;