--PARAMETRO DE CREDENCIALES
@&1 

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;

CREATE TABLE TMP_TTEE_CLIENTE_SEGEMENTO 
   (	CODSUBSEGMENTO CHAR(3) NOT NULL ENABLE, 
	DESSUBSEGMENTO VARCHAR2(40), 
	CODSEGMENTO CHAR(3), 
	DESSEGMENTO VARCHAR2(35)
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_GGTT_1 
   (	CODIGO_OPERACION CHAR(25) NOT NULL ENABLE, 
	CODCLAVECIC NUMBER, 
	NBRCLIORDENANTE VARCHAR2(77), 
	CODUNICOCLI CHAR(13), 
	CODUNICOCLIBENEFICIARIO CHAR(13), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER, 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE NOT NULL ENABLE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL VARCHAR2(50), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_GGTT_2 
   (	CODIGO_OPERACION CHAR(25) NOT NULL ENABLE, 
	CODCLAVECIC NUMBER, 
	NBRCLIORDENANTE VARCHAR2(77), 
	CODUNICOCLI CHAR(13), 
	CODUNICOCLIBENEFICIARIO CHAR(13), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER, 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE NOT NULL ENABLE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL VARCHAR2(50), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_GGTT 
   (	CODIGO_OPERACION CHAR(25), 
	CODCLAVECIC NUMBER, 
	NBRCLIORDENANTE VARCHAR2(77), 
	CODUNICOCLI CHAR(13), 
	CODUNICOCLIBENEFICIARIO CHAR(13), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER, 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL VARCHAR2(50), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_BANNI_1 
   (	CODIGO_OPERACION VARCHAR2(25), 
	CODCLAVECIC NUMBER, 
	NOMBRE_CLIENTE VARCHAR2(77), 
	CODUNICOCLI VARCHAR2(13), 
	CODUNICOCLIBENEFICIARIO CHAR(1), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER(16,2), 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE NOT NULL ENABLE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL CHAR(1), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_BANNI_2 
   (	CODIGO_OPERACION VARCHAR2(25), 
	CODCLAVECIC NUMBER, 
	NOMBRE_CLIENTE VARCHAR2(77), 
	CODUNICOCLI VARCHAR2(13), 
	CODUNICOCLIBENEFICIARIO CHAR(1), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER(16,2), 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE NOT NULL ENABLE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL CHAR(1), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_BANNI 
   (	CODIGO_OPERACION VARCHAR2(25), 
	CODCLAVECIC NUMBER, 
	NOMBRE_CLIENTE VARCHAR2(77), 
	CODUNICOCLI VARCHAR2(13), 
	CODUNICOCLIBENEFICIARIO CHAR(1), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER(16,2), 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL CHAR(1), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_FINAL 
   (	CODIGO_OPERACION VARCHAR2(25), 
	CODCLAVECIC NUMBER, 
	NBRCLIORDENANTE VARCHAR2(77), 
	CODUNICOCLI VARCHAR2(13), 
	CODUNICOCLIBENEFICIARIO VARCHAR2(13), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER, 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL VARCHAR2(50), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_UNIVERSO 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_GGTT_PERFIL 
   (	CODIGO_OPERACION CHAR(25) NOT NULL ENABLE, 
	CODCLAVECIC NUMBER, 
	MONTO_DOLAR NUMBER, 
	FECDIA DATE NOT NULL ENABLE
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_BANNI_PERFIL 
   (	CODIGO_OPERACION VARCHAR2(25), 
	CODCLAVECIC NUMBER, 
	MONTO_DOLAR NUMBER(16,2), 
	FECDIA DATE NOT NULL ENABLE
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PERFIL 
   (	CODIGO_OPERACION VARCHAR2(25), 
	CODCLAVECIC NUMBER, 
	MONTO_DOLAR NUMBER, 
	FECDIA DATE
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_SEGMENTO 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PEP CHAR(2), 
	SEGMENTO VARCHAR2(35)
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PROFESION 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PEP CHAR(2), 
	SEGMENTO VARCHAR2(35), 
	FLG_PROF NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_SAPYC 
   (	IDCASO NUMBER, 
	CODCLAVECIC NUMBER, 
	IDRESULTADOEVAL NUMBER, 
	FECFINEVAL TIMESTAMP (6), 
	IDRESULTADOSUPERVISOR NUMBER
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_EVALS 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PEP CHAR(2), 
	SEGMENTO VARCHAR2(35), 
	FLG_PROF NUMBER, 
	CTDEVAL NUMBER
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PRE_PAIS 
   (	CODCLAVECIC NUMBER, 
	FECHA_OPERACION DATE, 
	PAIS_DESTINO CHAR(3), 
	CODPAIS3 VARCHAR2(3)
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PAIS_AUX 
   (	CODCLAVECIC NUMBER, 
	FECHA_OPERACION DATE, 
	PAIS_DESTINO CHAR(3), 
	CODPAIS3 VARCHAR2(3), 
	CODPAIS3_FINAL VARCHAR2(3)
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PAR 
   (	CODCLAVECIC NUMBER, 
	FECHA_OPERACION DATE, 
	PAIS_DESTINO CHAR(3), 
	CODPAIS3 VARCHAR2(3), 
	CODPAIS3_FINAL VARCHAR2(3), 
	FLG_ACTIVO NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PAIS 
   (	CODCLAVECIC NUMBER, 
	FECHA_OPERACION DATE, 
	PAIS_DESTINO CHAR(3), 
	CODPAIS3 VARCHAR2(3), 
	CODPAIS3_FINAL VARCHAR2(3), 
	FLG_ACTIVO NUMBER, 
	FLG_PAR1 NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PAIS_PAR 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	FLG_PAR NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_FLG_PAR 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PEP CHAR(2), 
	SEGMENTO VARCHAR2(35), 
	FLG_PROF NUMBER, 
	CTDEVAL NUMBER, 
	FLG_PAR NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_GROUP_PERFIL 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANS NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_PERFIL1 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANS NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_FEC_PERFIL 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FECHA_MIN NUMBER, 
	FECHA_MAX NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TTEE_FEC_PERFIL2 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MEDIA_DEPO NUMBER, 
	DESV_DEPO NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TTEE_FEC_PERFIL3 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PEP CHAR(2), 
	SEGMENTO VARCHAR2(35), 
	FLG_PROF NUMBER, 
	CTDEVAL NUMBER, 
	FLG_PAR NUMBER, 
	FLG_PERFIL NUMBER
   )TABLESPACE D_AML_99;

CREATE TABLE TMP_TTEE_TABLON_FINAL 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	NBRCLIORDENANTE VARCHAR2(77), 
	SEGMENTO VARCHAR2(35), 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PEP NUMBER, 
	FLG_PROF NUMBER, 
	FLG_PAR NUMBER, 
	FLG_PERFIL NUMBER, 
	CTDEVAL NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_EPIC003_OUTPUTMODEL 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	NBRCLIORDENANTE VARCHAR2(77), 
	SEGMENTO VARCHAR2(35), 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PEP NUMBER, 
	FLG_PROF NUMBER, 
	FLG_PAR NUMBER, 
	FLG_PERFIL NUMBER, 
	CTDEVAL NUMBER, 
	FLG_PAIS NUMBER, 
	N_CLUSTER NUMBER, 
	OUTLIER NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE TMP_EPIC003_ALERTAS 
   (	PERIODO NUMBER, 
	CODCLAVECIC NUMBER, 
	CODUNICOCLI CHAR(13), 
	MTO_TRANSF NUMBER, 
	CTD_OPE NUMBER, 
	FLG_PAIS NUMBER, 
	FLG_PROF NUMBER, 
	FLG_PEP NUMBER, 
	FLG_PERFIL NUMBER, 
	CTDEVAL NUMBER
   ) TABLESPACE D_AML_99;

CREATE TABLE EPIC003_DOC 
   (	RUTA CHAR(62), 
	NBRDOCUMENTO CHAR(45), 
	CODUNICOCLI CHAR(13), 
	FECREGISTRO DATE, 
	NUMCASO CHAR(1), 
	IDANALISTA NUMBER
   ) TABLESPACE D_AML_99;

drop table EPIC003;
CREATE TABLE EPIC003 
   (	FECGENERACION DATE, 
	IDORIGEN NUMBER, 
	CODUNICOCLI CHAR(13), 
	ESCENARIO CHAR(7), 
	DESESCENARIO CHAR(42), 
	PERIODO CHAR(10), 
	TRIGGERING NUMBER, 
	COMENTARIO VARCHAR2(644)
   )TABLESPACE D_AML_99;

drop table TMP_TRX_EPIC003;
CREATE TABLE TMP_TRX_EPIC003 
   (	CODIGO_OPERACION VARCHAR2(25), 
	CODCLAVECIC NUMBER, 
	NBRCLIORDENANTE VARCHAR2(77), 
	CODUNICOCLI VARCHAR2(13), 
	CODUNICOCLIBENEFICIARIO VARCHAR2(13), 
	MONEDA VARCHAR2(7), 
	MONTO_DOLAR NUMBER, 
	MTOTRX NUMBER(16,2), 
	CODMONEDATRX CHAR(4), 
	NACIONALIDAD CHAR(3), 
	FECHA_OPERACION DATE, 
	TIPO_PERSONA VARCHAR2(15), 
	PAIS_DESTINO CHAR(3), 
	TIPMARCACLI CHAR(1), 
	FLGPEP CHAR(2), 
	CANAL VARCHAR2(50), 
	DESSEGMENTO VARCHAR2(35), 
	NBRCLIBENEFICIARIO VARCHAR2(75), 
	CODSECTORISTA VARCHAR2(50)
   ) TABLESPACE D_AML_99;

QUIT:


