--PARAMETRO DE CREDENCIALES
@&1

SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION DISABLE PARALLEL QUERY;


-------------- TABLA DE TRANSACCIONES ------------------
---OBTENEMOS TODAS LAS TRANSACCIONES DE LOS CLIENTES QUE GENERARON ALERTAS-----

--DROP TABLE TMP_TRX_EPIC003;
--CREATE TABLE TMP_TRX_EPIC003 TABLESPACE D_AML_99 AS 
TRUNCATE TABLE TMP_TRX_EPIC003;
INSERT INTO TMP_TRX_EPIC003
SELECT CODIGO_OPERACION, 
A.CODCLAVECIC, 
NBRCLIORDENANTE, 
A.CODUNICOCLI, 
CODUNICOCLIBENEFICIARIO, 
MONEDA, 
MONTO_DOLAR, 
MTOTRX, 
CODMONEDATRX, 
NACIONALIDAD, 
FECHA_OPERACION, 
TIPO_PERSONA, 
PAIS_DESTINO, 
TIPMARCACLI, 
FLGPEP, 
CANAL, 
DESSEGMENTO, 
NBRCLIBENEFICIARIO, 
CODSECTORISTA
FROM TMP_TTEE_FINAL A
INNER JOIN TMP_EPIC003_ALERTAS B ON A.CODCLAVECIC = B.CODCLAVECIC;


QUIT;