ALTER SESSION DISABLE PARALLEL QUERY;

SET ECHO OFF
SET FEEDBACK OFF
SET HEAD OFF
SET LIN 256
SET TRIMSPOOL ON
SET WRAP OFF
SET PAGES 0
SET TERM OFF
set colsep ','
--set colsep '|'

SPOOL \\Pfilep11\lavadoactivos\99_Procesos_BI\0_SapycWeb\PAQUETES_ADHOC\99999999_MODEM_EPIC014_TRX_&&codunicocli..csv;

PROMPT CODUNICOCLI_SOL,APEPATCLI_SOL,APEMATCLI_SOL,NBRCLI_SOL,CODCLAVECIC_SOL,CODOPECTA_SOL,CODUNICOCLI_BEN,NBRCLI_BEN,CODCLAVECIC_BEN,CODOPECTA_BEN,TIPBANCA_BEN,FECDIA,HORTRANSACCION,CODMONEDA,MTOTRANSACCION,MTO_DOLARIZADO,TIPO_TRANSACCION,CANAL,CODPAISORIGEN;

SELECT
    CODUNICOCLI_SOL||','||
	REPLACE(TRIM(APEPATCLI_SOL),',','')||','||
	REPLACE(TRIM(APEMATCLI_SOL),',','')||','||
	REPLACE(TRIM(NBRCLI_SOL),',','')||','||
    CODCLAVECIC_SOL||','||
    CODOPECTA_SOL||','||
    CODUNICOCLI_BEN||','||
    NBRCLI_BEN||','||
    CODCLAVECIC_BEN||','||
    CODOPECTA_BEN||','||
    TIPBANCA_BEN||','||
    FECDIA||','||
    HORTRANSACCION||','||
    CODMONEDA||','||
	REPLACE(TRIM(TO_CHAR(MTOTRANSACCION,'99999999999999999990D00')),',','.')||','||
	REPLACE(TRIM(TO_CHAR(MTO_DOLARIZADO,'99999999999999999990D00')),',','.')||','||	
	TIPO_TRANSACCION||','||
    CANAL||','||
    CODPAISORIGEN
FROM
	TMP_INGCLIEBCACEI_TRX_INGRESOCLIE
	where codclavecic_ben = :codclavecic and fecdia between TRUNC(ADD_MONTHS(SYSDATE, -1),'MM') and TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE,-1)));

SPOOL OFF;