--parametro de credenciales
@&1

alter session disable parallel query;

set echo off
set feedback off
set head off
set lin 9999
set trimspool on
set wrap off
set pages 0
set term off

SPOOL '.\data\production\01_raw.csv';

PROMPT CODMES_OPERACION|CODCLAVECIC|MONTO_INGRESO|CTD_INGRESO|MTO_EGR|CTD_EGRESO|FLG_PEP|FLG_PEP_REL|TIPPER|ACT_ECONOMICA_GRUPOSINTERES|CODPROFESION|CATPROFESION|ANTIGUEDAD|FLGNP|CTDNP|FLGLSB|CTDLSB|FLGARCHIVONEGATIVO|FLGNPLSBAN|CTD_AN_NP_LSB|FLG_PERFIL_3DS|FLG_POLICIA|ANT_YAPE|FLG_CUENTA_YAPECARD|CTD_OPE_DIST_ING|CTD_OPE_DIST_EGR|CTD_ALERTAS_PREV;

SELECT 	
CODMES_OPERACION||'|'||
CODCLAVECIC||'|'||
REPLACE(TRIM(TO_CHAR(MONTO_INGRESO,'99999999999999999990D00')),',','.')||'|'||
CTD_INGRESO||'|'||
REPLACE(TRIM(TO_CHAR(MTO_EGR,'99999999999999999990D00')),',','.')||'|'||
CTD_EGRESO||'|'||
FLG_PEP||'|'||
FLG_PEP_REL||'|'||
TIPPER||'|'||
ACT_ECONOMICA_GRUPOSINTERES||'|'||
CODPROFESION||'|'||
CATPROFESION||'|'||
ANTIGUEDAD||'|'||
FLGNP||'|'||
CTDNP||'|'||
FLGLSB||'|'||
CTDLSB||'|'||
FLGARCHIVONEGATIVO||'|'||
FLGNPLSBAN||'|'||
CTD_AN_NP_LSB||'|'||
FLG_PERFIL_3DS||'|'||
FLG_POLICIA||'|'||
ANT_YAPE||'|'||
FLG_CUENTA_YAPECARD||'|'||
CTD_OPE_DIST_ING||'|'||
CTD_OPE_DIST_EGR||'|'||
CTD_ALERTAS_PREV
FROM TMP_YAPE_TABLONFINAL;

SPOOL OFF;

QUIT;